### ISSUE TITLE
'expires_in' missing from the authorization response when using the implicit or hybrid flow

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#100]
> I've been working on the Angular demo client and noticed when using implicit flow as configured in the default Mvc.Server sample, expires_in is not send back to the client as you can see from this query fragment:

> nonce=feb1277c73b51903511c5e05696ae8ca&state=5adf45fcf96e6d02236dd534b08418b0&token_type=bearer&access_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjA1MkM1RTQyMTVDRDBDMUUxNTA1RTA4RTZBRjNBREJFRkJGRDc4MjIifQ.eyJuYW1laWQiOiIxNjI4NzE1MiIsInVuaXF1ZV9uYW1lIjoiYWxleHplaXRsZXJfIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1NDU0MC8iLCJleHAiOjE0MzU4NzY1MjQsIm5iZiI6MTQzNTg3MjkyNCwiYWN0b3J0IjoiZXlKMGVYQWlPaUpLVjFRaUxDSmhiR2NpT2lKdWIyNWxJbjAuZXlKdVlXMWxhV1FpT2lKdGVVTnNhV1Z1ZENJc0luVnVhWEYxWlY5dVlXMWxJam9pVFhrZ1kyeHBaVzUwSUdGd2NHeHBZMkYwYVc5dUluMC4ifQ.NbkKPXxQpblq0AzbKw3c8EiOuVsHGSxbwXz5I6CqV35UN42wa-ZHC6UGOQYz7jfjYFUOWSES3AiBwr2dk4cUJKqrLPPICxwqW_K0LAsvNhXFpmJaeGnM6YrJt8d-ygQCtGiLMMF6aqzuuAqeIEbcLWvx3fBnUg2P4BCxxzkoj_VHIvC8Jr1gYNqO_C4gxAUHF-1XiR2kG-6A8d61FNCjqQEU_2cGC1JgHDx97P0WRGJ8zyHIKemj018WPQAvrtu6mGsTlxDcwTOn5bw-9aB4HFx1UAmRK4bc-5JGevndxMu5pXZXpSj_zuuYg26hY9uU-6cP6An2rlfleWZ8sn_ARg&id_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjA1MkM1RTQyMTVDRDBDMUUxNTA1RTA4RTZBRjNBREJFRkJGRDc4MjIifQ.eyJuYW1laWQiOiIxNjI4NzE1MiIsInVuaXF1ZV9uYW1lIjoiYWxleHplaXRsZXJfIiwiaWF0IjoiMTQzNTg3MjkyNCIsImF0X2hhc2giOiI5NnRqdlpVMlNQaTZHMUF6bnJYekx3Iiwibm9uY2UiOiJmZWIxMjc3YzczYjUxOTAzNTExYzVlMDU2OTZhZThjYSIsInN1YiI6IjE2Mjg3MTUyIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1NDU0MC8iLCJhdWQiOiJteUNsaWVudCIsImV4cCI6MTQzNTg3NDEyNCwibmJmIjoxNDM1ODcyOTI0LCJhY3RvcnQiOiJleUowZVhBaU9pSktWMVFpTENKaGJHY2lPaUp1YjI1bEluMC5leUp1WVcxbGFXUWlPaUp0ZVVOc2FXVnVkQ0lzSW5WdWFYRjFaVjl1WVcxbElqb2lUWGtnWTJ4cFpXNTBJR0Z3Y0d4cFkyRjBhVzl1SW4wLiJ9.qUlqH5SQn4b02UOG94wHsh67NZubdPnKrNz-63S2JqnxFFYGjFEQGYbenkje1vObT_WNjf716uTrKvKsKfLeR-HJKKyy_8_dRprYtzUEU_DvjZazCKYY3AxwLb1KSVZINClTfy-gHU3Ya3WEiAT-ogCkrTz7-ErZKAllvLEpzzY2v4NoS8MBTp9GfthHrV8idGbKdAMBw7dl7XN21k7JfUd_qnr2S-PfXuaqeWXWmzWW4LG9bJkr4Ru6WMZv2fyXG13jmkOIZCEQQAzdhuBKibswKVAHL7EZrJKToBHV17NGdd57sUZPB6eZAurYoTPdRyXtFZfuR4rGzvAFE5-6QQ

> Is there a way to activate the expiration for implicit flow?

Ported from https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/issues/94#issuecomment-118176728

**Comment by AlexZeitler** [comment]
:+1:

**Comment by PinpointTownes** [comment]
Fixed (OWIN/Katana: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/429bcdfec895379f3dffc2a0952c170fc9c7c3b7 ; ASP.NET 5: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/6498361a778c7ab3f6a686e087b0730daa3256a9)
