### ISSUE TITLE
Validating the token using jwt.io

### ISSUE THREAD

**Issue by AlexZeitler** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#105]
I just tried to validate the token signature of `Certificate.cer` using http://jwt.io but it didn't.
I extracted this public key: 

`0xC03FF8B8C35222EF8994F46BB4547C4E6D8B03048E9A096F25A8BA79D16B76F0EF93AC56CF162432822DE2FD779458880147C8D6FC99D4CD215907EB89FCB07AECD9BB4E83C964D4664A7D7ABBE14F12B6EC714DED74EE691C476972D1E0A9E103E364F1B05737CF7939987D83D1DFE7ECEC1E97B5EF382293073266D17EF4E106D7AA33EE529181718221E79566E499E507F8C9E3F028C66AB31FA54CE89927724CB3E832B6F229759D4D5B370C5F45D37154E0BE705E5343B7351E83438D7E4AB1ACA23935D5B77A90FEA65660E40342BD91CD9E87BAB5C3224E79336E08A46A2ED8702799B8EBF291B31818ECD0FAA877352FAD12AAC16560224D132EC477`

I also tried using the content of the `Certificate.keys` and failed...

**Comment by PinpointTownes** [comment]
Indeed, it doesn't work... and after 2 hours trying to debug it, I still don't know why :sob: 

It could be a bug in the way `JwtSecurityTokenHandler` generates the signature or a bug in the JWS library used by jwt.io, that may fail to read the RSA public key (I tried every possible format... but it's the most probable cause) or may fail to verify the signature.

**Comment by AlexZeitler** [comment]
I also tried validating it using express-jwt (Node.js middleware) from Auth0 and it told me 'invalid algorythm'...?

**Comment by PinpointTownes** [comment]
Okay, it definitely sounds like a jwt.io bug: either because they don't support all the certificate formats I've used or because they don't use the appropriate `KJUR.jws.JWS` method.

Directly using `verifyJWSByPemX509Cert` works correctly: :smile:  

```js
var id_token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjA1MkM1RTQyMTVDRDBDMUUxNTA1RTA4RTZBRjNBREJFRkJGRDc4MjIifQ.eyJuYW1laWQiOiIxMDk4MTEyMzAxNjUwMDUyNzk0OTAiLCJ1bmlxdWVfbmFtZSI6IkvDqXZpbiBDaGFsZXQiLCJzdWIiOiJzdWIiLCJpYXQiOiIxNDM2Mzk4MzM3IiwiYXRfaGFzaCI6InozQ0NBY3FyZzRTVGFoZVZjVGlTY3ciLCJub25jZSI6IjY1MTA1MjcwODg0MzU5NSIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTQ1NDAvIiwiYXVkIjoiaW1wbGljaXRfY2xpZW50IiwiZXhwIjoxNDM2Mzk5NTM3LCJuYmYiOjE0MzYzOTgzMzd9.TC6TPmlH20WW7SXvzHRhQ1eOA3wnQKB2f7MxE_qMs5chtlUp-85mEtC8ubzay1QaGDWtGkPItr6FFTf6hWWI3rQf5yrx_eRbhvFrUla6voqFD4dGJsDFS543I7UbJ5B9J3pkMB7FWCrjQUFAg_bmmSMGPQ_HL-AFcuoAsqLGBcekxDpMlUUyM8p1hTmfuoztDa6BvPGJp96wpzDzsNOH_1DJ5UlsDTgbkhMrVgxF3SdfbA2k4wer4UW0rC1tYOdc542TBcQm20g_8T23RpkTKypdxwuuUHk1GRZtwaqbAgMtc59pvGcY3KU4142-npru6qqMlWNgJhuB4ntCaJvMPA";
var certificate = "MIIDPjCCAiqgAwIBAgIQlLEp+P+WKYtEAemhSKSUTTAJBgUrDgMCHQUAMC0xKzApBgNVBAMTIk93aW4uU2VjdXJpdHkuT3BlbklkQ29ubmVjdC5TZXJ2ZXIwHhcNOTkxMjMxMjIwMDAwWhcNNDkxMjMxMjIwMDAwWjAtMSswKQYDVQQDEyJPd2luLlNlY3VyaXR5Lk9wZW5JZENvbm5lY3QuU2VydmVyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwD/4uMNSIu+JlPRrtFR8Tm2LAwSOmglvJai6edFrdvDvk6xWzxYkMoIt4v13lFiIAUfI1vyZ1M0hWQfrifyweuzZu06DyWTUZkp9ervhTxK27HFN7XTuaRxHaXLR4KnhA+Nk8bBXN895OZh9g9Hf5+zsHpe17zgikwcyZtF+9OEG16oz7lKRgXGCIeeVZuSZ5Qf4yePwKMZqsx+lTOiZJ3JMs+gytvIpdZ1NWzcMX0XTcVTgvnBeU0O3NR6DQ41+SrGsojk11bd6kP6mVmDkA0K9kc2eh7q1wyJOeTNuCKRqLthwJ5m46/KRsxgY7ND6qHc1L60SqsFlYCJNEy7EdwIDAQABo2IwYDBeBgNVHQEEVzBVgBDQX+HKPiztLNvT3jQeBXqToS8wLTErMCkGA1UEAxMiT3dpbi5TZWN1cml0eS5PcGVuSWRDb25uZWN0LlNlcnZlcoIQlLEp+P+WKYtEAemhSKSUTTAJBgUrDgMCHQUAA4IBAQCxbCF5thB+ypGpudLAjv+l3M2VhNITJeR9j7jMlCSMVHvW7iMOL5W++zKvHMMAWuITLgPXTZ4ktsjeVQxWdnS2IcU7SwB9SeLbOMk4lLizoUevkiNaf6v+Hskm5LiH6+k8Zsl0INHyIjF9XlALTh91EqQ820cotDXaQIhHabQy892+dBmGWhSE1kP56IvOPzlLdSTkrcfcOu9gzwPVfuTDWH8Hrmo3FXz/fADmE7ea+yE1ZBeKhaN8kaFTs5zrprJ1BnmegnrjDY3RFgqcTTetahv0VBS0/jHSTIsAXflEPGW7LbHimzcgMytFU4fFtPVbek5eunakhu/JdENbbVmT";

var jws = new KJUR.jws.JWS();
var result = jws.verifyJWSByPemX509Cert(id_token, certificate);
```

**Comment by PinpointTownes** [comment]
One last note: `verifyJWSByPemX509Cert` is declared as 'deprecated' since version 3.0 and `verify` is listed as the recommended alternative (http://kjur.github.io/jsjws/api/symbols/KJUR.jws.JWS.html#.verifyJWSByPemX509Cert)

Sadly, after much testing, it seems that `verify` doesn't really like certificates. If you don't want to use the deprecated `verifyJWSByPemX509Cert`, I found an alternative:

```js
var key = X509.getPublicKeyFromCertPEM(certificate);
var result = KJUR.jws.JWS.verify(id_token, key, ['RS256']);
```

What a bummer! :facepunch:

**Comment by AlexZeitler** [comment]
Thanks for looking into it - but how can the RS256 algo be different between KJUR.jws and jwt.io?

**Comment by PinpointTownes** [comment]
Actually, it's not (luckily :smile:), but the `verify` method used internally by `jwt.io` (https://github.com/jsonwebtoken/jsonwebtoken.github.io/blob/master/js/jwt.js#L118) doesn't like the PEM format of the RSA public key and throws an exception caught by `jwt.io` (that never displays it btw...).

The issue is not about the algorithm, it's about the key format.

**Comment by AlexZeitler** [comment]
:smile: 

Ok, I'm trying to understand - I tried this:
Using the `Certificate.cer` from the `Mvc.Server` folder I did this:

`openssl x509 -inform pem -in Certificate.cer -outform der -out Certificate.pem` 

Then I tried this:

````
var r = require('jsrsasign'); // the successor to KJUR.jws

var fs = require('fs');
var pem = fs.readFileSync('Certificate.pem', 'binary');
var prvKey = r.KEYUTIL.getKey(pem, '');
````

This results in:
````
/home/alex/src/nodetokenvalidation/node_modules/jsrsasign/lib/jsrsasign.js:1473
PRIVATE KEY-")!=-1){return KEYUTIL.getKeyFromEncryptedPKCS8PEM(f,e)}throw"not 
                                                                    ^
not supported argument
````

The second param for `getKey` is a password - did you use one to create the cert?

**Comment by PinpointTownes** [comment]
I wonder why I spend so much time writing code comments :smile: 

Unlike the .pfx container, the .cer certificate doesn't contain the private key.
The .pfx certificate is indeed protected by a password: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/blob/vNext/samples/Mvc/Mvc.Server/Startup.cs#L164

**Comment by AlexZeitler** [comment]
:grin: 

Now I tried this

`openssl pkcs12 -in Certificate.pfx -out Certificate.pem -clcerts`

Then using the `jsonwebtoken` package (on top of which `express-jwt` is build) I tried this:

````js
var jwt = require('jsonwebtoken')
var fs = require('fs');

var token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjA1MkM1RTQyMTVDRDBDMUUxNTA1RTA4RTZBRjNBREJFRkJGRDc4MjIifQ.eyJ1bmlxdWVfbmFtZSI6InRlc3QiLCJuYW1laWQiOiJ0ZXN0IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1NDU0MC8iLCJleHAiOjE0MzY0NzYyODMsIm5iZiI6MTQzNjQ3MjY4MywiYWN0b3J0IjoiZXlKMGVYQWlPaUpLVjFRaUxDSmhiR2NpT2lKdWIyNWxJbjAuZXlKdVlXMWxhV1FpT2lKaGJtZDFiR0Z5UTJ4cFpXNTBJaXdpZFc1cGNYVmxYMjVoYldVaU9pSk5lU0JCYm1kMWJHRnlTbE1nWTJ4cFpXNTBJR0Z3Y0d4cFkyRjBhVzl1SW4wLiJ9.LUgnHaUAtHoTQNSemseu_-Fi7MYS0sC4t3W-BmwhigPDFxsaUmpDEtneXEmBWvflWHJWFttIoZiSa-R7Ho2RAdzCCsXFDvZN4AgPSwSjQWvy1sOm2pxNFlsxWCduZuoOBgf5haYCkCoLTTSFHKcYyV_aL3j6CMjMIVj4nCECg44mVZITaPZJ5h49dsEG4qd4VlFF-2e-BI70j3qIFbEb1tOXgaBCid2Ih5NDSTyrF-DZklEF5ofQsj4UoZT8XW0JOocLEDhSuCC01YA_IKtmc629wlQtoOvKDXp7ugy9S26fVG4YdrDTlltC75yvG3xCWZldyN9TrgvMv_7xOLRoVQ"

var cert = fs.readFileSync('Certificate.pem');  // get public key
jwt.verify(token, cert,{ algorithms: ['RS256'] }, function(err, decoded) {
    console.log(decoded) 
});
````

Result:

````
{ unique_name: 'test',
  nameid: 'test',
  iss: 'http://localhost:54540/',
  exp: 1436476283,
  nbf: 1436472683,
  actort: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJuYW1laWQiOiJhbmd1bGFyQ2xpZW50IiwidW5pcXVlX25hbWUiOiJNeSBBbmd1bGFySlMgY2xpZW50IGFwcGxpY2F0aW9uIn0.' }
````

:sunglasses:

**Comment by AlexZeitler** [comment]
I tried another one (as I don`t want to share the private key / cert with another party):

`openssl x509 -pubkey -noout -in Certificate.pem  > pubkey.pem`

````js
var cert = fs.readFileSync('pubkey.pem');  // get public key
jwt.verify(token, cert,{ algorithms: ['RS256'] }, function(err, decoded) {
    console.log('error:', err);
    console.log('decoded', decoded) // bar
});
````

Result:

````
error: null
decoded { unique_name: 'test',
  nameid: 'test',
  iss: 'http://localhost:54540/',
  exp: 1436480494,
  nbf: 1436476894,
  actort: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJuYW1laWQiOiJhbmd1bGFyQ2xpZW50IiwidW5pcXVlX25hbWUiOiJNeSBBbmd1bGFySlMgY2xpZW50IGFwcGxpY2F0aW9uIn0.' }
````

**Comment by PinpointTownes** [comment]
This is definitely the way to go: the private key is only needed to sign the tokens, not to verify them :smile:

**Comment by AlexZeitler** [comment]
Ok, so now we also can have a sample where we protect a Node.js based API using AspNet.Security.OpenIdConnect.Server :smile:

**Comment by PinpointTownes** [comment]
Fantastic :smile: 

On a side note, it seems that `jsrsasign` now supports JWK (https://kjur.github.io/jsrsasign/api/symbols/KEYUTIL.html#.getKey).

It might be a great way to load the public key using the JWKS endpoint offered by `AspNet.Security.OpenIdConnect.Server`. Sadly, there's no sample showing how to use this API :cry:

**Comment by AlexZeitler** [comment]
I'll give it a try tomorrow.
