### ISSUE TITLE
adding to dnx 1.0.0-beta5

### ISSUE THREAD

**Issue by mburumaxwell** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#106]
Hello,
I tried adding this package to my project that using dnx 1.0.0-beta5. To my dependencies I added
```json
"AspNet.Security.OpenIdConnect.Extensions": "1.0.0-beta2",
"AspNet.Security.OpenIdConnect.Server": "1.0.0-beta2"
```

But the application could not run. I figured it was due to different dnx versions.
I cloned the repository locally and updated all dependencies to use beta5 version but there were a number of error in OpenIdConnectServerHandler.cs

How can I use this library with dnx beta5?

**Comment by PinpointTownes** [comment]
Hey, and thanks for your interest :smile: 

`aspnet-contrib` projects are only guaranteed to work with the latest DNX and ASP.NET 5 bits (currently, beta6) and sadly, we don't offer any "beta release" version.

You have two options:
* Migrating to the latest beta6 (it's not that unstable :smile:)
* Cloning `AspNet.Security.OpenIdConnect.Server` and reverting the changes added to make it compatible with beta6: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/pull/88.

Good luck :four_leaf_clover:
