### ISSUE TITLE
Enhance support for scope handling

### ISSUE THREAD

**Issue by ilmax** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#109]
I would like to have a fine graded control over scope, it would be cool if we can automatically embed scope into token (when applicable), I would like to opt/in change this default behavior maybe via some method override? Open to suggestion here.

Essentially we should make it super easy to validate (and hence limit) requested scope after the end user/client has been authenticated, and by default I would like to have the validated scopes (if any) to be automatically included in the result token (when applicable)

**Comment by mebehagen** [comment]
This would be a great feature! But as you have to implement a UI that allows the user to opt out some scopes anyway, you could simply add a line like this to the accept code of the consent dialog:
`identity.AddClaims(validatedScopes.Select(scope => new Claim(MyClaimTypes.Scope, scope.Name).WithDestination("token")));`

Works great for me, I have these scope claims available later, wherever the access token is used.

**Comment by PinpointTownes** [comment]
Done: scope values will now be automatically added as `scope` claims in the access token :+1:
You can limit the final scopes by replacing `request.Scope` with the scope value you want to use. 

ASP.NET 5: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/3e66bb8779fb621f6ef6bee9d2285a40703bd77c
OWIN/Katana: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/544854899a34dd91e5abeba77dec6fee38288860

**Comment by PinpointTownes** [comment]
FYI, I just pushed a commit that should help making the modification of the final `scope`/`resource` easier thanks to `SetScopes()` and `SetResources()`: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/blob/vNext/samples/Mvc/Mvc.Server/Controllers/AuthorizationController.cs#L132-L144

**Comment by ilmax** [comment]
Great :+1:
