### ISSUE TITLE
Fix claims filtering bug in CreateIdentityTokenAsync

### ISSUE THREAD

**Issue by mebehagen** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#114]
In OpenIdConnectServerHandler.cs in method `CreateIdentityTokenAsync`, the claim-filter expression refers to `OpenIdConnectConstants.ResponseTypes.Token` instead of `IdToken`!
Also I encountered that my cache grows continuously, which results from the caching of each authorization request (in `InvokeAuthorizationEndpointAsync`) without removing the the currently cached request before.

**Comment by PinpointTownes** [comment]
> In OpenIdConnectServerHandler.cs in method CreateIdentityTokenAsync, the claim-filter expression refers to OpenIdConnectConstants.ResponseTypes.Token instead of IdToken!

Nice catch, thanks! :smile:

Bug fixed (OWIN/Katana: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/f12a5765406a25feb69ed4c351fe8aff53c6d157; ASP.NET 5: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/da0559b08aab3a98bc46b177798d648d732ee26b)

> Also I encountered that my cache grows continuously, which results from the caching of each authorization request (in InvokeAuthorizationEndpointAsync) without removing the the currently cached request before.

In the current bits, the authorization request is removed from the cache when the user is redirected to the client application: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/blob/vNext/src/AspNet.Security.OpenIdConnect.Server/OpenIdConnectServerHandler.cs#L612-L616.

When the user doesn't complete the authentication flow, the authorization request is automatically removed after 1 hour: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/blob/vNext/src/AspNet.Security.OpenIdConnect.Server/OpenIdConnectServerHandler.cs#L459

Actually, this is how nonce handling works with the MSFT OpenID Connect client middleware when you enable caching storage. I agree it's not ideal, so feel free to share your ideas (or better, submit a PR) if you can think of a better approach :smile:

**Comment by mebehagen** [comment]
It is correct that the cache should clean up itself, but as I have to use a distributed cache implementation (scalable site in Azure), the auto-cleanup is a bit more expensive. I also have seen that the last authorization request is removed, but the "in between" requests (during redirects to login, consent dialog etc.) are kept in the cache. So I could think about simply removing the cache entry as soon as an existing authentication request has been re-assembled.

**Comment by PinpointTownes** [comment]
> I also have seen that the last authorization request is removed, but the "in between" requests (during redirects to login, consent dialog etc.) are kept in the cache.

I'll update `InvokeAuthorizationEndpointAsync` to avoid generating a new entry when the authorization request is already stored in the cache, which should help reducing the number of items stored for a single request.

> So I could think about simply removing the cache entry as soon as an existing authentication request has been re-assembled.

That's something I had in mind when developing the cache feature, but sadly, it has one major downside: it prevents the user from being able to refresh the consent page.

**Comment by PinpointTownes** [comment]
> I'll update InvokeAuthorizationEndpointAsync to avoid generating a new entry when the authorization request is already stored in the cache, which should help reducing the number of items stored for a single request.

Done (OWIN/Katana: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/9b9a30cfb39c012796f0f42b96a8766b17497f31 ; ASP.NET 5: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/1b559817a4fbcf6034f7f1765e544c70a1affb1d).

**Comment by mebehagen** [comment]
Thanks, works very well for me.
