### ISSUE TITLE
Response property of LogoutEndpointResponseNotification is not initialized

### ISSUE THREAD

**Issue by mebehagen** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#116]
The ctor of the `LogoutEndpointResponseNotification` class takes four arguments, but the response parameter is never assigned to the `Response` property.

**Comment by PinpointTownes** [comment]
Thanks for reporting this (awful) bug :smile: 

FYI, only the OWIN/Katana version was affected (probably a copy/paste bug).

Fixed: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/2d73e9722c54fbcb569ef09beed73f0f83a2e1f0

**Comment by PinpointTownes** [comment]
FYI, the fixed bits are now on MyGet :sake:
