### ISSUE TITLE
No id_token_hint identity in logout endpoint.

### ISSUE THREAD

**Issue by mebehagen** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#117]
I have some problems with the `end_session_endpoint`. I want to redirect to the optionally provided `post_logout_redirect_uri` only if this URL has been registered with the calling client. Therefore the client has to provide the `id_token_hint` as well. I am calling `context.Authentication.AuthenticateAsync(OpenIdConnectDefaults.AuthenticationType)` in my Logout action (as you recommend in your MVC Server sample) to retrieve the identity, but this does not work :-(

Stepping through your `OpenIdConnectServerHandler`, my assumption is, that the `AuthenticateCoreAsync` method is always called before `InvokeAsync`. Therefore `Context.GetOpenIdConnectRequest()` always returns null in `AuthenticateCoreAsync` and the `id_token_hint` is never read (although it is in the request)?

(I am using active authentication mode for the OpenIDConnectServer.)

**Comment by PinpointTownes** [comment]
Yup, that's a known limitation that will be fixed soon, as part of the userinfo endpoint support PR: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/pull/97/files#diff-6481f3d22656613ec6487a18fb7e2177R57

In the meantime, you can disable active authentication.

**Comment by PinpointTownes** [comment]
I finally extracted the active/automatic authentication support from the userinfo PR and merged it in both versions (OWIN/Katana: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/3a6b3be4c80ffebc53eff86c61471a3b68c97237; ASP.NET 5: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/a7f074dff97d72fb3f33011cb0e33156492818ce) :tada:
