### ISSUE TITLE
Can't build project after cloning locally

### ISSUE THREAD

**Issue by Sharpiro** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#125]
I cloned the Repo, installed dnx 1.0.0 beta 8, allowed the packages to restore, but the project will not build for me.

The main (perhaps only) error I'm getting is that "BaseNotification" class is not found.  Where does this class come from?

Can you provide some insight on how to fix this, as I can't figure it out.

Thanks.

**Comment by PinpointTownes** [comment]
The errors you're seeing are due to the massive naming changes that have been merged in aspnet/Security: https://github.com/aspnet/Security/issues/47

It will be fixed - soon - by https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/pull/124 :+1:

**Comment by PinpointTownes** [comment]
Done. OWIN/Katana: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/f65719bd086e2840456790415877a5840c1f3fd9; ASP.NET 5: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/a971528ef1386002a8a0cf93a7b199f823323cd4 :palm_tree:
