### ISSUE TITLE
Omit Refresh token (automatic offline_access)

### ISSUE THREAD

**Issue by stephenstroud** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#128]
I will be overriding create refresh token, can we have automatic offline_access support?

**Comment by PinpointTownes** [comment]
That's definitely on my todo list.

Actually, the main concern I have with `offline_access` is that it will break pure OAuth2 clients using a refresh token without specifying an explicit scope. Not sure if it's really a big deal, though.

**Comment by PinpointTownes** [comment]
Merged (OWIN/Katana: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/5dba65ee382805eef6665d31df4d21d04d202088 ; ASP.NET 5: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/29916f7732d1a5ebc4b4756e53d2e9d0ea33ac28)
