### ISSUE TITLE
Automatically generate and persist a default RSA key when SigningCredentials is null

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#129]
* The keys will be stored in the TEMP folder of the account running the ASP.NET host.
* The keys will be protected by the data protection block before being persisted on the disk.

**Comment by csunali** [comment]
This will be a nice enhancement. Thanks!

**Comment by PinpointTownes** [comment]
Done :tada: 

ASP.NET 5: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/4e52ea4b8eef0256f1a9956fe97480beac8b1df1
OWIN/Katana: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/5aa93be751f177edf4ad96f647fc20491b4794d2

**Comment by damccull** [comment]
This means I don't have to make a pfx or store a serialized key anymore? Can I back this key up after generation for moving servers?

**Comment by PinpointTownes** [comment]
> This means I don't have to make a pfx or store a serialized key anymore?

Yep, exactly. If you don't specify at least one `SigningCredentials` instance in `Options.SigningCredentials`, ASOS will automatically generate a RSA key, protect it with the data protection block and store it in the same folder as the one used by data protection.

> Can I back this key up after generation for moving servers?

Indeed, you can (though I'd recommended using a X509 certificate stored in the machine store when going live).

By default, keys are stored in `C:\Users\[username]\AppData\Local\ASP.NET\aspnet-contrib\aspnet-oidc-server` on Windows and in `/home/[username]/.local/share/ASP.NET/aspnet-contrib/aspnet-oidc-server` on Linux. If we can't find an appropriate place, the current directory will be used as the fallback value (which is harmless, since the keys are encrypted).

You can also specify your own directory using `options.UseKeys(directory, protector)` but in this case, you'll have to manually create a protector. I'm planning to simply that by adding new hooks in future versions.
