### ISSUE TITLE
When an external login (e.g. Google) is denied, how do I recognize this?

### ISSUE THREAD

**Issue by sunsided** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#131]
I was toying around with your library on ASP.NET 5 (beta 8-ish on nightlies) with little experience there so far, however the sample server project seems to works fine in general. I stripped out the Entity Framework part, as I'm planning to use a different data store later on.

Maybe I'm missing something obvious, but when I try to login with Google by doing a little

    http://localhost:51497/signin?returnUrl=http://localhost:51497/api/message

dance, I'll get to the consent page on Google, as expected. When I _deny_ the login there, I'm being redirected to 

    http://localhost:54540/signin-google?error=access_denied&state=CfDJ8M_e...foobar....Rdh5iyg#

and find the message

    Microsoft.AspNet.Authentication.Google.GoogleMiddleware: Warning: Invalid return state, unable to redirect.

in the debug output, along with a `500 Internal Server Error`.

Can you guide me on what's going on here and how I would react to that?

**Comment by PinpointTownes** [comment]
I moved your question to the **aspnet/Security** repository, where questions/features concerning the OAuth2 generic middleware (and its derivatives) are discussed by the ASP.NET team.

https://github.com/aspnet/Security/issues/451

See you there :smile:

**Comment by sunsided** [comment]
:+1:
