### ISSUE TITLE
Fixing a release to a specific DNX build (e.g. beta7)

### ISSUE THREAD

**Issue by tugberkugurlu** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#133]
As far as I can see, you are working with the latest build of DNX runtime. Is it possible to tie a specific release to a stable{ish} runtime released on NuGet.org like beta7? 

I would like to start using this but in that project, we use only stable beta releases.

**Comment by csunali** [comment]
You should check the Nuget repository as far as I know. Myget contains dev releases and Nuget contains stable-ish releases.

**Comment by PinpointTownes** [comment]
Yup, @csunali is right, our "stable" releases are on NuGet.org: https://www.nuget.org/packages/AspNet.Security.OpenIdConnect.Server/ :tada: 

Note: the beta2 package is meant to be used with ASP.NET 5 beta7.

**Comment by tugberkugurlu** [comment]
@PinpointTownes ah, didn't know that. Cool! Will get that.

**Comment by PinpointTownes** [comment]
I'll update all the aspnet-contrib repositories to indicate we're also on NuGet.org :+1:
