### ISSUE TITLE
/signin route in Sample Client fails on docker and Windows

### ISSUE THREAD

**Issue by sunsided** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#136]
If the authentication server is offline, when I start the **client** sample on Windows or using a `1.0.0-beta8-15618` docker image (e.g. `sunside/aspnet:1.0.0-beta8-15618` from today), the client application renders the home page, but fails as soon as the `sign in` button is clicked.

This does a `GET /signin` which results in a `500 Internal Server Error`. On Kestrel, no exception output is given. On Windows (both HTTP Listener and IIS Express), an exception is printed stating that the authentication server's `.../.well-known/openid-configuration` cannot be reached.

If I try that again within a short time (or simply go to `/signin` manually), on both Windows and Linux Chrome detects an infinite redirect and terminates the request.

Fiddler states that the response is a `302 Found` with the Location

```http
Location: ?client_id=myClient&redirect_uri=http%3A%2F%2Fclient-dev.wundercart.de%3A53507%2Foidc&resource=http%3A%2F%2Fresource-dev.wundercart.de%3A54540%2F&response_type=code%20id_token&scope=openid%20profile&response_mode=form_post&nonce=6357820672...QxZTNh&state=CfDJ8BR0J...KPygjHp62icn0JQ
```

The console is then spammed with

```
client_1 | warning : [Microsoft.AspNet.Authentication.OpenIdConnect.OpenIdConnectMiddleware] OIDCH_0036: Uri.IsWellFormedUriString(redirectUri, UriKind.Absolute) returned 'false', redirectUri is: '?client_id=myClient&redirect_uri=http%3A%2F%2Fclient%3A53507%2Foidc&resource=http%3A%2F%2Fresource%3A54540%2F&response_type=code%20id_token&scope=openid%20profile&response_mode=form_post&nonce=635782067223014590...MjMtZmUxMjgwODhkMzY2&state=CfDJ8BR0JH1siad...PGKXve4TivaWEs_XwBKydF3HY'.
client_1 | warning : [Microsoft.AspNet.Authentication.OpenIdConnect.OpenIdConnectMiddleware] OIDCH_0036: Uri.IsWellFormedUriString(redirectUri, UriKind.Absolute) returned 'false', redirectUri is: '?client_id=myClient&redirect_uri=http%3A%2F%2Fclient%3A53507%2Foidc&resource=http%3A%2F%2Fresource%3A54540%2F&response_type=code%20id_token&scope=openid%20profile&response_mode=form_post&nonce=635782067223118170....YzAtMDM5ZDBjMDdkY2My&state=CfDJ8BR0JH1siad...WFEmnNDv9xfV3wWCi1bA6t9a8'.
client_1 | warning : [Microsoft.AspNet.Authentication.OpenIdConnect.OpenIdConnectMiddleware] OIDCH_0036: Uri.IsWellFormedUriString(redirectUri, UriKind.Absolute) returned 'false', redirectUri is: '?client_id=myClient&redirect_uri=http%3A%2F%2Fclient%3A53507%2Foidc&resource=http%3A%2F%2Fresource%3A54540%2F&response_type=code%20id_token&scope=openid%20profile&response_mode=form_post&nonce=635782067223231680...iNWUtYjMyOWZlNzcxY2Fi&state=CfDJ8BR0JH1siad5J...NhLwk4HBXaGWHLJNOIFZ3sE'.
client_1 | warning : [Microsoft.AspNet.Authentication.OpenIdConnect.OpenIdConnectMiddleware] OIDCH_0036: Uri.IsWellFormedUriString(redirectUri, UriKind.Absolute) returned 'false', redirectUri is: '?client_id=myClient&redirect_uri=http%3A%2F%2Fclient%3A53507%2Foidc&resource=http%3A%2F%2Fresource%3A54540%2F&response_type=code%20id_token&scope=openid%20profile&response_mode=form_post&nonce=635782067223231680...iNWUtYjMyOWZlNzcxY2Fi&state=CfDJ8BR0JH1siadL..._NhLwk4HBXaGWHLJNOIFZ3sE'.
```

In `Startup.cs` the middleware is configured with

```csharp
app.UseOpenIdConnectAuthentication(options => {
    options.AuthenticationScheme = OpenIdConnectDefaults.AuthenticationScheme;

    options.ClientId = "myClient";
    options.ClientSecret = "secret_secret_secret";
    options.RedirectUri = "http://client:53507/oidc";
    options.PostLogoutRedirectUri = "http://client:53507/";

    options.Authority = "http://server:54540/";
    options.Resource = "http://resource:54540/";

    // ...
```

This generally works at least on Windows when both servers are on.

**Comment by PinpointTownes** [comment]
This is likely a bug in the OIDC client middleware (owned by MSFT). I moved your issue to the aspnet/Security repository: https://github.com/aspnet/Security/issues/467.

**Comment by manbearwiz** [comment]
@sunsided were you ever able to get these samples working in docker containers?

**Comment by PinpointTownes** [comment]
@manbearwiz any particular error you're seeing?

**Comment by manbearwiz** [comment]
I'm attempting to run the mvc sample client and server each in their own container and wired together with compose. [Here is my latest code](https://github.com/manbearwiz/AspNet.Security.OpenIdConnect.Samples). 

Running `docker-compose -f docker-compose.debug.yml up` in the mvc client successfully launches the client and server and I am able to access each of them at `http://localhost:53507/` and `http://localhost:54540/` respectively. When I click the "Sign In" button on the client I am brought to `http://localhost:53507/signin` which displays the following error:

```
CurlException: Couldn't connect to server
HttpRequestException: An error occurred while sending the request.
IOException: IDX10804: Unable to retrieve document from: 'http://localhost:54540/.well-known/openid-configuration'.
InvalidOperationException: IDX10803: Unable to obtain configuration from: 'http://localhost:54540/.well-known/openid-configuration'.
```

What stand out to me is that the client is attempting to contact `localhost:54540` rather than `mvc.server:54540` like I have set in the client.

There is a pretty good possibility that I am doing something wrong as this is my first time using this library and do not yet understand any of the details.

**Comment by PinpointTownes** [comment]
@manbearwiz this sounds like a firewall/isolation issue. Unfortunately, I'm not a Docker expert, so I won't be really helpful.

**Comment by sunsided** [comment]
@manbearwiz From what it looks to me, `external_links` in the client'y compose file might be what you are looking for. Otherwise, try creating a compose file up in the solution and define both servers there, then you use `depends_on` and/or `links` to actually link the containers. After that, you use the configured alias as the server name in the configuration (e.g. set `http://openid` as the authority). The [comoose file reference](https://docs.docker.com/compose/compose-file/) has some examples. In essence, the containers run in separate networks unless you explicitly tell them not to and there is no name resolution between these networks.
