### ISSUE TITLE
UseWhen vs MapWhen in the sample

### ISSUE THREAD

**Issue by sunsided** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#137]
Regarding the samples - is there a reason the `UseWhen(...)` extension method ([defined here](https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/blob/vNext/samples/Mvc/Mvc.Server/Extensions/AppBuilderExtensions.cs#L17)) is used instead of `IApplicationBuilder`'s `MapWhen(...)`?

**Comment by PinpointTownes** [comment]
Everything has a reason, and this `UseWhen` extension is no exception :smile: 

Unlike `MapWhen`, this extension doesn't stop executing the rest of the pipeline when the delegate returns `true`, which makes "conditional middleware execution" much easier, specially in our MVC sample where MVC is always executed, but with different authentication schemes.

**Comment by sunsided** [comment]
Ah-hah! 

... I guess ... :smile:
(Thanks)

**Comment by zwbdzb** [comment]
thankyou @PinpointTownes 
it is a  resultful comment to explain the difference between mapwhen and usswhen .
The metadata say 
[usewhen]:Conditionally creates a branch in the request pipeline that is rejoined to the  main pipeline.
[mapwhen]: Branches the request pipeline based on the result of the given predicate.
