### ISSUE TITLE
If the user denies resource access, redirect to home doesn't work in client sample

### ISSUE THREAD

**Issue by sunsided** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#138]
When the user denies consent after successfully authenticating, this is signaled to the client. The `OnAuthenticationFailed` event of `OpenIdConnectEvents` is triggered correctly. Apart from the big red exception printed out being somewhat nasty, the `context.Response.Redirect("/")` part [here](https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/blob/vNext/samples/Mvc/Mvc.Client/Startup.cs#L70) doesn't seem to work and an `404 Not Found` is returned instead (actually everytime the `/oidc` endpoint `GET`s visited).

After this message:

```
error   : [Microsoft.AspNet.Authentication.OpenIdConnect.OpenIdConnectMiddleware] OIDCH_0006: Message contains error: 'access_denied', error_description: 'The authorization grant has been denied by the resource owner', error_uri: 'ErrorUri null'.
error   : [Microsoft.AspNet.Authentication.OpenIdConnect.OpenIdConnectMiddleware] OIDCH_0017: Exception occurred while processing message.
Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectProtocolException: OIDCH_0006: Message contains error: 'access_denied', error_description: 'The authorization grant has been denied by the resource owner', error_uri: 'ErrorUri null'.
   bei Microsoft.AspNet.Authentication.OpenIdConnect.OpenIdConnectHandler.<HandleAuthenticateAsync>d__13.MoveNext()
```

This part results in the `404`.

```csharp
OnAuthenticationFailed = context => {
    if (string.Equals(context.ProtocolMessage.Error, "access_denied", StringComparison.Ordinal))
    {
        context.HandleResponse();
        context.Response.Redirect("/signin");
    }
    return Task.FromResult<object>(null);
},
```

**Comment by sunsided** [comment]
Just poking around there, but if I `await context.Response.WriteAsync("lol", Encoding.UTF8)` instead of `context.Response.Redirect(...)`ing, I'm getting a `InvalidOperationException: Headers already sent`.

**Comment by PinpointTownes** [comment]
We're aware of this bug. Sadly, there's absolutely nothing we can do to fix it in the sample itself, since it's caused by the OIDC client middleware. This bug is far from being recent and was introduced after a huge refactoring of the OIDC middleware (it doesn't exist in the Katana version).

It should be fixed as part of https://github.com/aspnet/Security/issues/55.

**Comment by sunsided** [comment]
Funky, I hit that bug twice in the last four days - in two different locations. :smile:

**Comment by PinpointTownes** [comment]
Yeah, I agree it's annoying.

FYI, @Tratcher recently modified the milestone of https://github.com/aspnet/Security/issues/55: it should be fixed in beta8.

**Comment by sunsided** [comment]
That sounds perfect.
