### ISSUE TITLE
AddOpenIdConnectServer missing.

### ISSUE THREAD

**Issue by Bartmax** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#139]
Since OpenIdConnectServer have a dependency on Caching, I thing it will be appropiate to have a AddOpenIdConnectServer() method that adds the caching.

**Comment by PinpointTownes** [comment]
I knew there was a reason why I had not created such an extension... I now remember why :smile: 

`services.AddCaching()` is part of `Microsoft.Framework.Caching.Memory`. We don't depend on this package and only use `Microsoft.Framework.Caching.Abstractions` to avoid pulling too many packages.
