### ISSUE TITLE
Unable to obtain token on Docker: An exception occured when serializing an access token

### ISSUE THREAD

**Issue by sunsided** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#142]
I implemented the resource owner credential flow by customizing `GrantResourceOwnerCredentials()`. In there I basically just look up the user, create a new `ClaimsIdentity` and add a `ClaimTypes.NameIdentifier`, then create a `ClaimsPrincipal`, after which I hit the `Validated` button on the context.

This works on Windows - I'm getting an `access_token`, although recent versions (I'm currently running on `1.0.0-rc1-15838` with nightlies) seem to exclude the `refresh_token` which was there before in `beta8`.

When I run this on Docker using the `microsoft/aspnet` image and an upgraded DNX to `1.0.0-rc1-15838`, this is what happens:

```log
server_1 | info    : [Project.Authentication.Server.Providers.AuthorizationProvider] Created Authorization Provider
server_1 | info    : [Microsoft.Extensions.DependencyInjection.DataProtectionServices] User profile is available. Using '/root/.local/share/ASP.NET/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
server_1 | info    : [Microsoft.AspNet.DataProtection.KeyManagement.XmlKeyManager] Creating key {e923c2fd-4e82-4968-9d1c-0f7e5757d78b} with creation date 2015-10-12 17:06:16Z, activation date 2015-10-12 17:06:16Z, and expiration date 2016-01-10 17:06:16Z.
server_1 | warning : [Microsoft.AspNet.DataProtection.KeyManagement.XmlKeyManager] No XML encryptor configured. Key {e923c2fd-4e82-4968-9d1c-0f7e5757d78b} may be persisted to storage in unencrypted form.
server_1 | info    : [Microsoft.AspNet.DataProtection.Repositories.FileSystemXmlRepository] Writing data to file '/root/.local/share/ASP.NET/DataProtection-Keys/key-e923c2fd-4e82-4968-9d1c-0f7e5757d78b.xml'.
server_1 | Hosting environment: Development
server_1 | Now listening on: http://auth.project.de:54540
server_1 | Application started. Press Ctrl+C to shut down.
server_1 | info    : [Project.Authentication.Server.Providers.AuthorizationProvider] In MatchEndpoint
server_1 | info    : [Project.Authentication.Server.Providers.AuthorizationProvider] In ValidateClientAuthentication
server_1 | info    : [Project.Authentication.Server.Providers.AuthorizationProvider] In ValidateTokenRequest
server_1 | info    : [Project.Authentication.Server.Providers.AuthorizationProvider] In GrantResourceOwnerCredentials
server_1 | info    : [Project.Authentication.Server.Providers.AuthorizationProvider] In TokenEndpoint
server_1 | warning : [AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerMiddleware] An exception occured when serializing an access token.
server_1 | System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
server_1 |   at System.ThrowHelper.ThrowInvalidOperationException (ExceptionResource resource) [0x00000] in <filename unknown>:0
server_1 |   at System.Collections.Generic.List`1+Enumerator[System.Security.Claims.Claim].MoveNextRare () [0x00000] in <filename unknown>:0
server_1 |   at System.Collections.Generic.List`1+Enumerator[System.Security.Claims.Claim].MoveNext () [0x00000] in <filename unknown>:0
server_1 |   at System.Security.Claims.ClaimsIdentity+<FindAll>c__Iterator1.MoveNext () [0x00000] in <filename unknown>:0
server_1 |   at AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerHandler+<CreateAccessTokenAsync>d__21.MoveNext () [0x00000] in <filename unknown>:0
server_1 | error   : [AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerMiddleware] CreateAccessTokenAsync returned no access token.
```

Within the Dockerfile the SDK version is extracted from `global.json` and installed as default, which in this case results in

```bash
root@1621df85eec4:/app/src/Project.Authentication.Server# dnvm list

Active Version              Runtime Arch OperatingSystem Alias
------ -------              ------- ---- --------------- -----
       1.0.0-rc1-15838      mono         linux/darwin    default
       1.0.0-beta7          mono         linux/darwin
```

Dockerfile and upgrade script [in this gist](https://gist.github.com/sunsided/fb2341fa3826ffa8cbae).

**Comment by PinpointTownes** [comment]
> This works on Windows - I'm getting an access_token, although recent versions (I'm currently running on 1.0.0-rc1-15838 with nightlies) seem to exclude the refresh_token which was there before in beta8.

FYI: you now need to include the `offline_access` scope to get a refresh token (https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/issues/128).

I'm pretty sure this error is caused by the fact old versions of Mono use an iterator (https://github.com/mono/mono/blob/mono-4.0.0-branch/mcs/class/corlib/System.Security.Claims/ClaimsIdentity.cs#L216-L223) while MSFT's implementation uses a list (http://referencesource.microsoft.com/#mscorlib/system/security/claims/ClaimsIdentity.cs,770). When we call `RemoveClaim`, the inner collection iterated by `FindAll` is modified and an exception is thrown.

The immediate fix is to call `ToArray()` to avoid working on the original collection (I'll upload a commit for that).

That said, I'm convinced you'll face other obscure errors due to the horrible *Claims* implementation in Mono <4.2: try to migrate to the latest alpha versions, that include MSFT's implemtnation.

**Comment by sunsided** [comment]
Dude, that's the best thing I heard all day! Some hope at last! :sweat_smile:

**Comment by PinpointTownes** [comment]
Fixed in both versions (ASP.NET 5: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/7be2562473f53aed2c045fc28d7ad2fd254f6666 ; OWIN/Katana: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/e9dd0055922e50a70b44c30e16a08813a8991233)

The fixed packages should now be on MyGet. Don't hesitate to run `dnu restore --no-cache` if DNU refuses to download the latest package :smile:

**Comment by sunsided** [comment]
Yah, that trick I learned early. :D I'll give it a shot once I'm at home.

**Comment by PinpointTownes** [comment]
FYI: it works fine on Mono JIT compiler version 4.3.0 (Nightly 4.3.0.372/0f9f44e Thu Jul  9 17:08:26 UTC 2015) even without this fix.

**Comment by sunsided** [comment]
I can't currently get `dnu restore` to work in a mono 4.2 and mono 4.3.0 nightly container, always fails with timeouts on FindPackageById and sometimes connection losses. MyGet seems to be terribly slow (60 seconds response time?) and the `MONO_THREADS_PER_CPU` hack doesn't seem help. It was worse during the nighttime but is only marginally better at the moment - yooouuuu don't happen to have a working docker image floating around? :sweat:

**Comment by PinpointTownes** [comment]
> yooouuuu don't happen to have a working docker image floating around?

Nope, sorry, I haven't played with Docker yet and test the ASOS bits directly on my Ubuntu machine. That said, we experienced similar timeouts in our CI builds. Retrying a few times seems to help... a bit.

**Comment by sunsided** [comment]
Did that for about a day now. When I replaced the nuget.org v3 API with the v2 one things get better. I'll try to get it running this way.

**Comment by sunsided** [comment]
Okay, I can confirm this works. Thanks again man, also for the `offline_access` hint!
