### ISSUE TITLE
Time to build a beta8 package

### ISSUE THREAD

**Issue by singlewind** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#143]
asp.net beta8 has been released the day before yesterday. So, it may be a good time to launch a new package as well.

**Comment by PinpointTownes** [comment]
It's on my todo list :+1: 

Off-topic: I'm looking for documentation contributors. As a long-time ASOS user, would you like to participate? :smile:

**Comment by PinpointTownes** [comment]
Done: https://www.nuget.org/packages/AspNet.Security.OpenIdConnect.Server/1.0.0-beta3

**Comment by PinpointTownes** [comment]
@singlewind please ping me if you wanna contribute :clap:

**Comment by singlewind** [comment]
@PinpointTownes no problem at all. I'd like to contribute back. At the moment, I'm still learning. However, the application I'm currently building is cover most of the flows. The challenge for documentation is how to describe the openid theory part with the library you have built. Possible make some user cases and have a ready be used sample server with shinning look. Our front-end guy is currently building the backend management portal for me. We just need change the theme. I've compared your library with IdentityServer before, the reason why I chooseAspNet.Security.OpenIdConnect.Server because developers can have fully controlled, easier understood and lightweight library. 

Tell me what I can do and your requirements for the documentation. Although I'm not a native English speaker, I'd like to contribute the project and help it grow.

**Comment by CallMeLaNN** [comment]
Hi @PinpointTownes, I'm not really sure here on the version naming, so this 1.0.0-beta3 is compatible to official asp.net beta8?

**Comment by PinpointTownes** [comment]
Yep, exactly: https://www.nuget.org/packages/AspNet.Security.OpenIdConnect.Server/1.0.0-beta3
