### ISSUE TITLE
DNX migration/build issues

### ISSUE THREAD

**Issue by MonkeyJamboree** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#149]
Since the migration to DNX/C#6, I've been having a heck of a time building.

1. The projects don't have "Produce Outputs on build" enabled, so by default Visual Studio doesn't produce any kind of binaries for any of the projects.

2. Also, the OutputPath in both Nancy.Client.xproj and Nancy.Server.xproj end up pathing to $(SolutionDir)\..\artifacts\ instead of $(SolutionDir)\artifacts\, yet the pathing seems to be ignored by the build.cmd script for the samples.

3. Finally, the nightly DNX release seems pretty unstable and either works via build.cmd or Visual Studio, but not both. Using build.cmd seems to have messed up my local visual studio's DNX as it can't find Microsoft.DNX.PackageManager (current version 1.0.0-rc1-15978).

For the first part of this issue and the Visual Studio portion of the second part, I've created a pull request from my fork of the project.

**Comment by PinpointTownes** [comment]
Thanks for the path fix, I'll merge it! :+1: 

Curious: why do you need to enable "Produce outputs on build"?
build.cmd or dnu pack should be enough to produce .nupkg packages.

**Comment by MonkeyJamboree** [comment]
Honestly, I'm not quite sure, but VS didn't seem to output any sort of binaries or nupkg files on build when building the solution. build.cmd does, sure, but I'm not seeing VS hook into build.cmd or dnu pack automatically in any way on its own.

**Comment by PinpointTownes** [comment]
Curious: why do you need packages when building in VS?

**Comment by MonkeyJamboree** [comment]
Perhaps my feature testing workflow is flawed... I don't have a CI process, and like to test the features in an application, so I'm actually using the dll binaries themselves as assembly references in a test project locally. That's really about the only reason for it (beyond the fact that initially when I encountered this repo, NuGet releases weren't set up yet, but that's a non-issue now).

**Comment by PinpointTownes** [comment]
Yeah, you should use our packages for that (either the nightly builds on MyGet or the official releases on NuGet) :clap:

**Comment by MonkeyJamboree** [comment]
Of course, though the packages won't necessarily work for not-yet-implemented OIDC spec features I'm attempting to help develop on branches (off of my fork of the project) that aren't in the packages yet. :open_mouth:

**Comment by ilmax** [comment]
That was my fault :(

**Comment by PinpointTownes** [comment]
@MonkeyJamboree nice coincidence, I was about to rework the validation endpoint to implement the introspection specs! :+1: 
This is really something I'd like to implement in the next beta, so feel free to ping me if you need help.

FYI: to reference ASOS from a project you're working on, you can use the `src` section in `global.json` and point to your local copy of ASOS.

**Comment by MonkeyJamboree** [comment]
Work on introspection is in progress and shouldn't take too long to implement.

Re: local references: Ahh, well that would work great then, just need to update it from a 2013 project/solution. Thanks!

**Comment by MonkeyJamboree** [comment]
Okay, so I just updated my DNX to 1.0.0-rc1-16031 while trying to build my own branch of the vNext branch, and Visual Studio is no longer able to find `Microsoft.DNX.PackageManager` for whatever reason. I did not save the solution after the update, could this be causing my issue? build.cmd works just fine. Any help with this would be greatly appreciated.

**Comment by MonkeyJamboree** [comment]
I seem to have found a way to duplicate the issue. If you do `git clean -dxf` on the repository, then open up the solution in Visual Studio as a freshly-cloned repo, it throws a `System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.DNX.PackageManager' or one of its dependencies.` when trying to pull it from the dnx-clr-win-x86.1.0.0-rc1-16031 directory (or 15838, 15978, etc).

Could this be a Visual Studio bug of some kind?

**Comment by MonkeyJamboree** [comment]
Alright, this definitely seems to be a weird intermittent tooling issue on clean repos, because while I'm on the same branch, after getting it to build initially (usually using build.cmd) I have no problems building. Switching branches and cleaning sometimes brings the issue up, but not always.

Related to part 1 of the initial issue, should the `ProduceOutputsOnBuild` option be reverted for the projects?

**Comment by PinpointTownes** [comment]
Glad you finally sorted it out!

> Related to part 1 of the initial issue, should the ProduceOutputsOnBuild option be reverted for the projects?

I already reverted these changes in my local copy of your PR :+1:

**Comment by MonkeyJamboree** [comment]
Cool, I'll go with that once it's merged in. Feel free to close this since it's not (directly) related to the codebase, unless you see a need to keep it open for whatever reason.

**Comment by PinpointTownes** [comment]
Fixed: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/2f8d6436f5783a0972671f44325e10d028fe8821
