### ISSUE TITLE
Reacting to changes on BaseControlContext

### ISSUE THREAD

**Issue by csunali** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#161]
Hello,

When do you think you would have some time to check OIDC server against the latest Microsoft.AspNet.Authentication packages? :)

There seems to be a change with BaseControlContext<T> which breaks the whole compilation as soon as I integrate OIDC server into my applications.

https://github.com/aspnet/Security/commit/409b50269a9d85618a31f84a3ffc2868abb3eeea

**Comment by PinpointTownes** [comment]
Done: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/8a407dd0471c98956b499647b9f391cfbdd792df :tada:

**Comment by csunali** [comment]
Were you waiting for me to create an issue before committing? :))

Great work! Thanks.

**Comment by PinpointTownes** [comment]
> Were you waiting for me to create an issue before committing? :))

Yeah!
Nah, I'm kidding. I was testing the changes before committing them when you created your ticket :+1:

**Comment by csunali** [comment]
How long does it approximately take before I can see the new version on your myget feed?

**Comment by PinpointTownes** [comment]
You can track the progress here: https://ci.appveyor.com/project/aspnet-contrib/aspnet-security-openidconnect-server/build/1.0.0-beta4-464 :tada:

**Comment by csunali** [comment]
Learned one more thing! :) 

Cheers

**Comment by csunali** [comment]
Feedback: things build successfully again :+1:

**Comment by PinpointTownes** [comment]
Great, thanks for the confirmation! :+1:
