### ISSUE TITLE
Support for "SAML2 Bearer" grant type (RFC7522)

### ISSUE THREAD

**Issue by MonkeyJamboree** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#163]
Add support for the [Security Assertion Markup Language (SAML) 2.0 Profile](https://tools.ietf.org/html/rfc7522) grant type, referenced by the [OAuth 2.0 Dynamic Registration](https://tools.ietf.org/html/rfc7591) spec.

**Comment by aaronpk** [comment]
Has this ever been implemented?

**Comment by kevinchalet** [comment]
@aaronpk no. [ASOS is being merged into OpenIddict](https://github.com/openiddict/openiddict-core/issues/736) and there's currently no plan to implement such a feature, for which the demand is too low.

**Comment by aaronpk** [comment]
Thank you for confirming!
