### ISSUE TITLE
Support for Dynamic Client Registration

### ISSUE THREAD

**Issue by MonkeyJamboree** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#164]
Add support for [OAuth 2.0 Dynamic Registration](https://tools.ietf.org/html/rfc7591) and [OpenID Connect Dynamic Registration](http://openid.net/specs/openid-connect-registration-1_0.html)

**Comment by MonkeyJamboree** [comment]
I've started some preliminary work for this on my fork, but it's not anywhere near finished. I hope to get to implementing it sometime this week.

**Comment by ghost** [comment]
@PinpointTownes could you please provide an update on this enhancement?

**Comment by kevinchalet** [comment]
Well, though I agree it would be a nice feature, I personally don't have any plan to implement it in the near future. Of course, if someone was willing to fund it, I'd surely consider spending some time on it :sweat_smile:
