### ISSUE TITLE
Support for Dynamic Registration Management (RFC7592)

### ISSUE THREAD

**Issue by MonkeyJamboree** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#170]
Add support for the [OAuth 2.0 Dynamic Client Registration Management Protocol](https://tools.ietf.org/html/rfc7592) spec.

Requires [Dynamic Client Registration](https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/issues/164) support.

**Comment by MonkeyJamboree** [comment]
I'd like some opinions: Thoughts on calling this the Client Configuration endpoint internally? Or about using the same endpoint that registration uses for updating client metadata, since the HTTP method determines the action executed in the specs?

**Comment by PinpointTownes** [comment]
IMHO, we should definitely use the same endpoint for the exact reason you mentioned :+1:

**Comment by MonkeyJamboree** [comment]
FYI: This is being implemented along with https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/issues/164 as I go.
