### ISSUE TITLE
Missing reference exceptions 

### ISSUE THREAD

**Issue by csunali** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#171]
Hi,

I am having a strange compilation issue where VS says that Microsoft.AspNet.Authentication should be added as a reference. Please see the screenshot.

![image](https://cloud.githubusercontent.com/assets/6509380/11040209/cc6f5d12-8713-11e5-9ea9-4a9ec014955d.png)

I am certain that I have it as a reference though, please see the following:

```
{
    "version": "1.0.0-*",
    "authors": [ "Coskun" ],
    "tags": [ "" ],
    "projectUrl": "",
    "licenseUrl": "",

    "dependencies": {
        "AspNet.Security.OpenIdConnect.Server": "1.0.0-beta4-0484",
        "Microsoft.AspNet.Authentication": "1.0.0-rc2-15985"
    },

    "frameworks": {
        "dnx451": { },
        "dnxcore50": {
            "dependencies": {
                "System.Linq": "4.0.1-beta-23506"
            }
        }
    }
}
```

What do you think I might be missing?

![image](https://cloud.githubusercontent.com/assets/6509380/11040286/24823a56-8714-11e5-976b-5957327d8430.png)

**Comment by PinpointTownes** [comment]
Hi,

Sounds like you're using a really recent version of `Microsoft.AspNet.Authentication` (probably downloaded from the `aspnetcidev` CI feed). aspnet-contrib projects only use the `aspnetvnext` feed, that break less often: https://www.myget.org/gallery/aspnetvnext.

Try clearing your `.dnx\packages` folder to remove the newest packages and go back to the supported builds :+1:

**Comment by csunali** [comment]
Sounds reasonable :) Thank you!

**Comment by PinpointTownes** [comment]
2 pro-tips :smile: 
  * Ensuring `username` and `password` are non-null in `GrantResourceOwnerCredentials` is no longer necessary. ASOS will automatically return an error if one of these parameters is null or empty.
  * ASOS has a whole new `context.Skipped()` method you're **strongly** encouraged to use in `ValidateClientAuthentication` when `client_id` and/or `client_secret` is/are null (basically, for non-confidential client applications). Using `Skipped()` instead of `Validated()` allows you to ensure client authentication is not "abusively" validated for confidential application when credentials are not flowed.

**Comment by csunali** [comment]
Very useful tips :) Thank you!

**Comment by csunali** [comment]
I just remembered why I switched to the CI nightly builds.

Whenever I add the following reference:

```
"AspNet.Security.OpenIdConnect.Server": "1.0.0-beta4-0484"
```

I start getting exceptions:

```
    Unable to locate Dependency System.Security.Cryptography.Csp >= 4.0.0-beta-23506
    Unable to locate Dependency System.Security.Cryptography.Cng >= 4.0.0-beta-23506
    Unable to locate Dependency System.Collections >= 4.0.11-beta-23506
    Unable to locate Dependency System.Diagnostics.Tools >= 4.0.1-beta-23506
    Unable to locate Dependency System.IO >= 4.0.11-beta-23506
    Unable to locate Dependency System.Runtime.Extensions >= 4.0.11-beta-23506
    Unable to locate Dependency System.Runtime.InteropServices >= 4.0.21-beta-23506
    Unable to locate Dependency System.Security.Claims >= 4.0.1-beta-23506
    Unable to locate Dependency System.Security.Cryptography.Algorithms >= 4.0.0-beta-23506
    Unable to locate Dependency System.Security.Cryptography.X509Certificates >= 4.0.0-beta-23506
    Unable to locate Dependency System.Security.Principal >= 4.0.1-beta-23506
    Unable to locate Dependency System.Text.RegularExpressions >= 4.0.11-beta-23506
    Unable to locate Dependency System.Threading >= 4.0.11-beta-23506
    Unable to locate Dependency System.Collections.Specialized >= 4.0.1-beta-23506
    Unable to locate Dependency System.Diagnostics.Contracts >= 4.0.1-beta-23506
    Unable to locate Dependency System.IO.FileSystem >= 4.0.1-beta-23506
    Unable to locate Dependency System.Net.Http >= 4.0.1-beta-23506
    Unable to locate Dependency System.Xml.ReaderWriter >= 4.0.11-beta-23506
    Unable to locate Dependency System.Diagnostics.Tracing >= 4.0.21-beta-23506
    Unable to locate Dependency System.Globalization >= 4.0.11-beta-23506
    Unable to locate Dependency System.Dynamic.Runtime >= 4.0.11-beta-23506
```

However, the above versions (23506) are only found within the CI feed.

If I remove the reference to OIDC Server, I don't get any package errors and my project compiles successfully.

Does it ring any bells on your mind?

**Comment by PinpointTownes** [comment]
Hum, I guess that's because the IdentityModel nightly builds pulls the latest packages. Anyway, you can find them on CLR team's feed: https://www.myget.org/gallery/dotnet-core

**Comment by csunali** [comment]
That sounds like a much better solution than switching to the CI builds.

Thanks!
