### ISSUE TITLE
Nuget package for RC1?

### ISSUE THREAD

**Issue by dlob** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#178]
Will there be a Nuget package for the 1.0.0-rc1-final release of ASP.NET 5 in the near future?

**Comment by PinpointTownes** [comment]
Yep. A last minute Mono bug delayed the beta4 release, but it shouldn't be long.

**Comment by onesmartguy** [comment]
Awesome. I was wondering about this as well.

**Comment by PinpointTownes** [comment]
FYI, all the aspnet-contrib packages for RC1 have been pushed to NuGet.org. They are now being indexed :clap:

**Comment by dlob** [comment]
Ty for this very fast response :smile:
