### ISSUE TITLE
Proposal: Simplify OAuthValidateClientAuthenticationContext class

### ISSUE THREAD

**Issue by SetTrend** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#182]
The `OAuthValidateClientAuthenticationContext` class comes with two functions which both output a `ClientID` although the class itself (by means of its base class) provides a ClientId property.

I proprose to remove this ambiguity and to render both methods, `TryGetBasicCredentials()` and `TryGetFormCredentials` parameterless. The class itself should provide a `ClientSecret` property in order to harmonize with the base class's `ClientId` property.
<br/>
The resulting class definition would resemble the following:

```c#
public class OAuthValidateClientAuthenticationContext : BaseValidatingClientContext
{
  public string ClientSecret { get; protected set; }

  [Flags]
  public enum CredentialSource { HttpBasic, HtmlForm };

  public bool GetClientCredentials(CredentialSource sourceType)
  {
    if ((sourceType & CredentialSource.HttpBasic) == CredentialSource.HttpBasic)
    {
      ClientId = ... ;
      ClientSecret = ... ;
    }

    if ((sourceType & CredentialSource.HtmlForm) == CredentialSource.HtmlForm) ...
    {
      ClientId = ... ;
      ClientSecret = ... ;
    }

    return !string.IsNullOrEmpty(ClientId);
  }
}
```
<br/>
I suspect it's unnecessary to distinguish the source of client identification. So the class's interface could be even simplified by retrieving the values by querying the properties themselves:

```c#
public class OAuthValidateClientAuthenticationContext : BaseValidatingClientContext
{
  private string _clientId;     // alternatively move this implementation to the base class
  public new string ClientId     // alternatively move this implementation to the base class
  {
    get
    {
      if (_clientId == null) getClientCredentials();
      return _clientId;
    }
  }

  private string _clientSecret;
  public new string ClientSecret
  {
    get
    {
      if (_clientId == null) getClientCredentials();   // _clientId is used intentionally here because it's mandatory whereas _clientSecret is optionally provided by client
      return _clientSecret;
    }
  }

  private void getClientCredentials()
  {
    _clientId = ... ;   // query each of the available sources here (Basic, Forms, etc.)
    _clientSecret = ... ;   // query each of the available sources here (Basic, Forms, etc.)
  }
}
```

**Comment by PinpointTownes** [comment]
These 2 methods have been removed from ASOS for the exact reason you mentioned: they were terribly confusing :confused: 

Their logic has been directly integrated in the handler itself: by default, the credentials are extracted from the request form or from the Authorization header: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/blob/vNext/src/AspNet.Security.OpenIdConnect.Server/OpenIdConnectServerHandler.Endpoints.cs#L778

Of course, nothing prevents you from manually setting `ClientId`/`ClientSecret` via `Validate(...) `if you want to extract the credentials from a different source: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/blob/vNext/src/AspNet.Security.OpenIdConnect.Server/Events/ValidateClientAuthenticationContext.cs

You can find more information here: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/issues/102
