### ISSUE TITLE
How do I validate external access token with ASOS?

### ISSUE THREAD

**Issue by SetTrend** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#183]
In 
http://bitoftech.net/2014/08/11/asp-net-web-api-2-external-logins-social-logins-facebook-google-angularjs-app/ Taiseer implements a method to validate external access tokens (originated by Google, Facebook etc.) received from a client application.

Apparently, validating external access tokens is done provider specific. Does ASOS provide a provider-agnostic member function to validate external access tokens, e.g. `GetOwinContext().ValidateExternalToken(string externalAccessToken, string loginProvider)` ?

**Comment by PinpointTownes** [comment]
There's no such thing in ASOS and IMHO, it's not really something you should implement, as it's totally provider-specific and won't work with providers that don't offer a validation endpoint like Dropbox.

To add new social providers, the new Identity 3 template offers a MUCH better way to do that:

https://github.com/openiddict/core/blob/dev/samples/Mvc.Server/Controllers/ManageController.cs#L251-L277
