### ISSUE TITLE
Equivalent to "/token" for external access tokens?

### ISSUE THREAD

**Issue by SetTrend** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#184]
I'm not quite clear about what
```c#
ClaimsIdentity oAuthIdentity = new ClaimsIdentity(claims, OAuthDefaults.AuthenticationType);
Authentication.SignIn(oAuthIdentity);
```
does in Web API's `AccountController.GetExternalLogin()`. It doesn't issue a local access token to the client as far as I can see.

What is required to return a response to the client which is resembling the response of the `/token` endpoint, as if it had parameter `grant_type: password` set, after having the external access token received?

My imagination is that there was an ASOS function I can call in `AccountController.GetExternalLogin()` which returned a (JSON?) object like this, which I can then add to the header of the response:
```JSON
{ "access_token": "abcde"
, "token_type": "bearer"
, "expires_in": 12345
}
```
... or like this:
```JSON
{ "access_token": "abcde"
, "token_type": "bearer"
, "expires_in": 12345
, "refresh_token": "xyz"
, ".issued": "Fri, 27 Nov 2015 22:54:23 CET"
, ".expires": "Fri, 27 Nov 2015 23:54:23 CET"
}
```

**Comment by PinpointTownes** [comment]
> My imagination is that there was an ASOS function I can call in AccountController.GetExternalLogin() which returned a (JSON?) object like this, which I can then add to the header of the response:

No, there's no such (totally not standard) thing, I'm afraid :smile:

**Comment by PinpointTownes** [comment]
> does in Web API's AccountController.GetExternalLogin(). It doesn't issue a local access token to the client as far as I can see.

AFAIK, it should (at least, it should redirect the user agent to the client application with the access token appended to the fragment URL).

**Comment by SetTrend** [comment]
Oh, gee, yes, I can see it now. I got lost in searching at the server side and looking at Fiddler's raw response.

Please pardon my confusion! :blush:
