### ISSUE TITLE
Use opaque access tokens by default and update the MVC sample to use the new validation middleware

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#185]
Starting with ASOS beta5, we'll stop using JWT as the default format for access tokens and go back to opaque tokens (serialized by the data protection block), exactly like `OAuthAuthorizationServerMiddleware`. Of course, JWT tokens will still be supported (via `options.UseJwtTokens()`), but will no longer be enabled by default (opting for JWT tokens for specific clients only will also be supported).

Since ASP.NET 5 offers no native support for opaque tokens, I developed 2 new middleware:

* An [introspection middleware] (https://github.com/aspnet-contrib/AspNet.Security.OAuth.Extensions/tree/vNext/src/AspNet.Security.OAuth.Introspection): as the name suggests, this middleware will use ASOS' introspection/validation endpoint to determine whether an access token is still valid and retrieve the corresponding authentication ticket. To avoid flooding the introspection endpoint, this middleware comes with native distributed/local caching support. Though primarily designed to work with ASOS, it can be used with virtually any OAuth2 server supporting the introspection RFC. Using this middleware is recommended if the resource server(s) is/are not in the same application as the authorization server. 

* A [validation middleware] (https://github.com/aspnet-contrib/AspNet.Security.OAuth.Extensions/tree/vNext/src/AspNet.Security.OAuth.Validation): this middleware is far simpler (and more efficient) than the introspection middleware as it directly decrypts the access token using the data protection block, instead of making an HTTP call to the authorization server. This middleware offers a much easier experience compared to `JwtBearerMiddleware` and `OAuthIntrospectionMiddleware` as it doesn't need any configuration by default but will only work if the resource servers and the authorization servers are part of the same application or share the same data protection keys. Of course, this middleware is only designed to support the opaque tokens produced by the data protection block and doesn't natively support JWT tokens. For such tokens, `JwtBearerMiddleware` is still the best choice.

The MVC sample will be updated to reflect those changes.

**Comment by PinpointTownes** [comment]
`OAuthIntrospectionMiddleware` and `OAuthValidationMiddleware` have been backported to OWIN/Katana: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Extensions/tree/dev

**Comment by PinpointTownes** [comment]
@louislewis2 please ping me on JabbR when you have a minute, I'd like to ensure the new validation middleware works with your zero-conf scenario :clap:

**Comment by PinpointTownes** [comment]
Done (for 4 days now :smile:).

ASP.NET 5: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/939067dfa7e50e020b5cbc09c84213f7174f3ab8
OWIN/Katana: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/5f3ba524cd6cdfac5e1af55c8268d4afec369ffa

**Comment by singlewind** [comment]
Great job. @PinpointTownes Forgive my ignorance, to replace with opaque tokens to replace JWT token as 1st choice option, is this something you consider more generic as an API or a more secure option?

**Comment by PinpointTownes** [comment]
Opaque tokens are actually the best compromise between security (as they are fully encrypted) and simplicity, because you don't have to configure anything to use them (as long as the authorization server and the resource server are part of the same application and share the same data protection keys, which should cover most basic cases).

This is particularly true with the validation middleware (aka the zero-conf middleware :smile:), that doesn't require an audience by default, unlike the JWT bearer middleware. 

One could argue that we could achieve the same security objective by using JWE (that should be supported by IdentityModel soon). It's true, but JWE token encryption comes with a downside: you have to manage a list of public keys corresponding to the resource servers (when using asymmetric keys) or share a symmetric key between the authorization server and the resource servers, which requires some advanced configuration, incompatible with the simplicity-by-default approach (that said, this is definitely something we'll support when JWE is implemented, it just won't be the default format).

**Comment by PinpointTownes** [comment]
Oh and it has another merit: since we now have our own validation and introspection middleware, we no longer depend on the goodwill of the ASP.NET team... :smile:
