### ISSUE TITLE
Relax the refresh token policy to exclude client_id & client_secret

### ISSUE THREAD

**Issue by capesean** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#196]
A public client needs to send the client_id and client_secret in order to refresh a token. It would be much better to relax this constraint and let the refresh token be used without needing to send this information, or using workarounds like hidden frames and cookies, etc.

**Comment by PinpointTownes** [comment]
Moved to https://github.com/openiddict/core/issues/40 :clap:
