### ISSUE TITLE
Making ASOS More Unit Test Friendly

### ISSUE THREAD

**Issue by emilyclairelewis42** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#197]
I thoroughly appreciate your efforts with ASOS and we're having very good luck with this software in our API environment, so nice work! 

Now we're at the point in our own ASOS usage we are finding some friction points in unit testing our code because certain ASOS types are not easily mocked. 

For example - all the OpenIdConnectServerProvider events pass ASOS types like LogoutEndpointContext and ValidateClientAuthenticationContext as parameters to event handlers. This means my unit tests for my OpenIdConnectServerProvider event handlers need to pass instances of those primitives (e.g. LogoutEndpointContext) to the code under test. The problem is all these primitives are sealed and have internal constructors. Normally I would use fakes to mock out these types but fakes doesn't appear to be available for DNX, at least not yet. I can't use MOQ because the ASOS types (e.g. LogoutEndpointContext) aren't abstract and they aren't interfaces either. 

This has forced me to use reflection to construct these types manually which of course is brittle and clearly working around your design objectives.

Though I know you might suggest we do more integration style testing a simple change in the ASOS code base would accommodate unit testing. One approach would be that you simply make your public types such as LogoutEndpointContext and ValidateClientAuthenticationContext abstract, taking a page from basic types in the Microsoft.AspNet.* namespace such as HttpRequest and HttpContext, which are all abstract and therefore mockable.

Another approach would be to slap an interface in front of all your concretes, like ILogoutEndpointContext and IValidateClientAuthenticationContext, and change the OpenIdConnectServerProvider event signatures to match.

Thanks again for your hard work, and I hope this suggestion makes it into your main line soon!

**Comment by PinpointTownes** [comment]
I'm not opposed to revert the changes applied to the various context classes (i.e unsealing the classes and making their constructor public) if it helps make unit testing easier, but introducing new interfaces/abstract base classes would be extremely noisy and harder to maintain (and I plan to add new events in the future... :smile:)

Though convenient, marking everything virtual would be a bit cumbersome (and a bit dangerous :smile:). If we agreed to revert the visibility changes - but not to mark everything virtual - would it be enough for you?

**Comment by PinpointTownes** [comment]
If you want these changes to be included in ASOS, feel free to send a PR :clap:

**Comment by emilyclairelewis42** [comment]
Reverting the visibility changes would be great, I could then construct those types and do away with my reflection in the unit tests.

**Comment by PinpointTownes** [comment]
@emilyclairelewis42 would you like to submit a PR? :smile:

**Comment by emilyclairelewis42** [comment]
I'll talk to my team and see if they'll give me some bandwidth to work on this.

**Comment by PinpointTownes** [comment]
:watch:

**Comment by emilyclairelewis42** [comment]
We're sprint planning today, I'll get this into our sprint and submit a PR
in a week or so 🙂

**Comment by PinpointTownes** [comment]
Done.

ASP.NET Core: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/e97a392301327cb8edcf7cbb1319c3dae96cd452
OWIN/Katana: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/39f609e9d942a442f06f6d9fa0234462179e4f5c
