### ISSUE TITLE
sub and aud claims missing in access_token

### ISSUE THREAD

**Issue by sunsided** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#198]
Maybe I'm missing something obvious, but I just upgraded my authentication server (separate from API server) to ASOS beta5-0562 and am now unable to obtain a valid `access_token` for `password` grants.
 
This is basically the implementation for the resource owner credential flow:
```csharp
public override async Task GrantResourceOwnerCredentials([NotNull] GrantResourceOwnerCredentialsContext context) 
{
    // ... 
    var identity = new ClaimsIdentity(OpenIdConnectServerDefaults.AuthenticationScheme);
    identity.AddClaim(ClaimTypes.NameIdentifier, user.Id.Value, "token id_token");
    identity.AddClaim(ClaimTypes.Name, user.DisplayName, "id_token token");
    identity.AddClaim(ClaimTypes.GivenName, user.Name.GivenName, "id_token");
    identity.AddClaim(ClaimTypes.Surname, user.Name.Surname, "id_token");

    var principal = new ClaimsPrincipal(identity);
    var ticket = new AuthenticationTicket(
        principal, new AuthenticationProperties(),
        context.Options.AuthenticationScheme);

    if (!string.IsNullOrWhiteSpace(context.Request.ClientId))
    {
        ticket.SetPresenters(context.Request.ClientId);
    }

    ticket.SetScopes(context.Request.GetScopes());

    ticket.SetResources(context.Request.GetResources());
    if (string.IsNullOrWhiteSpace(context.Request.Resource))
    {
        Logger.LogDebug("Setting default audience for the ticket ...");
        ticket.SetResources(_defaultAudience);
    }

    context.Validate(ticket);
}
```
Problem is that `sub` and `aud` claims are missing in the `access_token`, while `unique_name` is there (as expected). In the `id_token`, the `sub` is set, while `aud` is still missing.
Example `access_token`:
```json
{
  "nbf": 1452192449, "exp": 1453402049, "iat": 1452192449,
  "unique_name": "Chuck Norris",
  "usage": "access_token", "confidential": true,
  "scope": ["profile", "offline_access", "openid"],
  "azp": "resource_server",
  "iss": "http://localhost:54540/"
}
```
Example `id_token`:
```json
{
  "nbf": 1452192449, "exp": 1452193649, "iat": 1452192449,
  "unique_name": "Chuck Norris", "given_name": "Carlos Chuck", "family_name": "Norris",
  "sub": "a5f32ebc2cd52ff782059294",
  "usage": "id_token", "confidential": true,
  "aud": "resource_server",
  "at_hash": "4OfG6yFpruCkWSFz8GiMvA",
  "azp": "resource_server",
  "iss": "http://localhost:54540/"
}
```
If I patch in the audience with `ticket.SetAudiences(context.Request.GetResources())` at least the `aud` claim is there, but from my understanding this is not what I should be doing.

If the `aud` claim is missing in the `access_token`, it is rejected at my resource server running the introspection middleware. If I patch it in, the authentication succeeds but I'm unable to do something sane with it as the `sub` claim containing the user ID is missing.

**Comment by PinpointTownes** [comment]
Thanks for the detailed report! :smile: 
It's indeed a bug, recently introduced by the refactoring changes in the serialization stuff.

Fixed:
ASP.NET 5: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/d37dea8f1a22e7113aaf68372f19a446baf5cedb and https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/69bf214cc483e6505d6a75eca4401be3219a402d
OWIN/Katana: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/2b13c61eaad0bf8985c40ea935cd8680b8b9c9bf and https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/7beae9ad686cfe2fe7558a00433a6c18a7b06821

**Comment by PinpointTownes** [comment]
FYI, you don't need to call `SetPresenters`: it's done for you by ASOS.

I'll probably hide these methods from Intellisense as part of https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/issues/195.

**Comment by sunsided** [comment]
Awesome, that was quick.

**Comment by PinpointTownes** [comment]
The fixed package is online. That would be great if you could confirm that this bug is now fixed :smile:

**Comment by sunsided** [comment]
Just did that :grin: Seems to work so far.

One thing though: In the `id_token` the `aud` claim is equal to the `azp` one which is the `client_id`. I'm not sure if that is correct.

**Comment by PinpointTownes** [comment]
> One thing though: In the id_token the aud claim is equal to the azp one which is the client_id. I'm not sure if that is correct.

It's the expected behavior: the client application is both the intended audience and the authorized presenter of the identity token.

**Comment by sunsided** [comment]
Ah, wasn't sure about it. Well then, bug's _slain_. :sweat_smile:

**Comment by DovydasNavickas** [comment]
Nice catch, @sunsided! And, awesome response time @PinpointTownes :+1: :smile:
Good job you both!
