### ISSUE TITLE
How to include custom claims in the access/identity tokens?

### ISSUE THREAD

**Issue by tim-cools** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#199]
I try to implement social and username/password authorization for an SPA React application. And I I'm almost there but I still face one issue.

I use the server to generate a token based on the username/password. For this I implement the GrantResourceOwnerCredentials method of a custom provider based on OpenIdConnectServerProvider.

In this method I generate an Identity with claims:

     var identity = new ClaimsIdentity(context.Options.AuthenticationScheme);
            identity.AddClaim(new Claim(ClaimTypes.Name, context.UserName));
            identity.AddClaim(new Claim(ClaimTypes.Role, "user"));

            var properties = new AuthenticationProperties(new Dictionary<string, string>
                {
                    {"as:client_id", context.ClientId ?? string.Empty},
                    {"userName", context.UserName}
                }
            );

            var principal = new ClaimsPrincipal(new[] { identity });
            var ticket = new AuthenticationTicket(principal, properties, context.Options.AuthenticationScheme);
            ticket.SetResources(new [] { "http://localhost:3000/" });
            context.Validated(ticket);

Which I use to validate the context.

Then I use JwtBearerAuthentication for my api which is able to deserialize the token and the authenticate the user:

            branch.UseJwtBearerAuthentication(options =>
            {
                options.AutomaticAuthenticate = true;
                options.AutomaticChallenge = true;
                options.RequireHttpsMetadata = false;
                options.Audience = "http://localhost:3000/";
                options.Authority = "http://localhost:3000/";
            });

But when I check the identity in the controller action it suddenly is an identity of AuthenticationType = "AuthenticationTypes.Federation" and all my claims are gone. Instead I have some cryptic claims:
   
    [0]: {nbf: 1452268726}
    [1]: {exp: 1452270526}
    [2]: {iat: 1452268726}
    [3]: {usage: access_token}
    [4]: {confidential: true}
    [5]: {aud: http://localhost:3000/}
    [6]: {azp: realTimeWebClient}
    [7]: {iss: http://localhost:3000/}

But this is no way to find the UserName back. I probably make a wrong assumption here but I expect to get the same ticket back as I returned from the GrantResourceOwnerCredentials. Is this normal behavior? Can you point me in the good direction?

And advice welcome!

Tim

Edit: 
- authentication configuration: 
https://github.com/tim-cools/RealTimeWeb.NET/blob/master/src/Soloco.RealTimeWeb/Infrastructure/OAuthConfig.cs
- provider: https://github.com/tim-cools/RealTimeWeb.NET/blob/master/src/Soloco.RealTimeWeb/Infrastructure/AuthorizationServerProvider.cs (don't mind the debug statments, this is still a mess)

**Comment by PinpointTownes** [comment]
For the custom claims, read http://stackoverflow.com/a/33806784/542757.

Concerning `AuthenticationTypes.Federation`, it's the default type used by IdentityModel. If you really want to change it, you can replace it in the `TokenValidationParamerers`, in the JWT options.

**Comment by tim-cools** [comment]
That did the job...
I don't mind the AuthenticationTypes.Federation, but it seemed strange...

Thanks for the support and your great contributions!

**Comment by PinpointTownes** [comment]
If you don't mind, I'll leave this ticket open as it's probably the most frequently asked question when using ASOS or OpenIddict :smile:
