### ISSUE TITLE
Is refresh_token and username/password authentication possible?

### ISSUE THREAD

**Issue by tim-cools** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#201]
Is it possible (or a good idea) to get a refresh_token together with the access_token when authenticating with username/password (grant_type=password)? 

I notices some sample code (not from the latest ASOS) that returned them both. But I can't get this working on the latests ASOS.

Any advice welcome!

**Comment by DovydasNavickas** [comment]
Did you pass `scope=offline_access` into request?

**Comment by PinpointTownes** [comment]
Dovydas is right, you now need to ask for the `offline_access` scope to get a refresh token :smile: 

Make sure to also call `SetScopes` on the ticket: it's not mandatory in beta4 but will be in beta5:

    var identity = new ClaimsIdentity(context.Options.AuthenticationScheme);
    identity.AddClaim(new Claim(ClaimTypes.Name, context.UserName));
    identity.AddClaim(new Claim(ClaimTypes.Role, "user"));

    var properties = new AuthenticationProperties();
    var principal = new ClaimsPrincipal(identity);
    var ticket = new AuthenticationTicket(principal, properties, context.Options.AuthenticationScheme);

    ticket.SetResources(new[] { "http://localhost:3000/" });
    ticket.SetScopes(new[] { "openid", "offline_access" });

    context.Validated(ticket);

**Comment by tim-cools** [comment]
But this is not possible in the same call as in which I validate the username/password right? 

The refresh token is returned inside this if branch: (from OpenIdConnectServerHandler)

       if (request.IsAuthorizationCodeGrantType() || request.IsRefreshTokenGrantType())
            {
And username/password is handled by 

       else if (request.IsPasswordGrantType())
            {

Is this the preferred flow: ? 
- Validate the username/passsword (grand_type=password)
- Get a refresh token (grand_type=refresh_token)

**Comment by tim-cools** [comment]
Never mind; It does return the refresh_token. I was looking in the wrong place
