### ISSUE TITLE
Replace OpenIdConnectServerHelpers.GenerateKey() by RSA.Create() when available

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#207]
The PR adding `RSA.Create()` to CoreFX [was merged today](https://github.com/dotnet/corefx/issues/2953). After making sure that it works correctly with DNX/CLI/NuGet, we should remove `OpenIdConnectServerHelpers.GenerateKey()` and use `RSA.Create()`.

**Comment by PinpointTownes** [comment]
@bartonjs hey! I was about to press the "push button" when I suddenly remembered that `RSACryptoServiceProvider` (the default implementation returned by `RSA.Create()` on .NET Desktop) used 1024-bit keys by default, that are now considered as too weak by IdentityModel.

Sadly, updating `KeySize` on the returned instance is not legal when dealing with `RSACryptoServiceProvider` and only works with `RSACng` (and probably `RSAOpenSsl`, though I haven't tested), so simply setting `KeySize` to 2048 doesn't work everywhere.

How would you deal with `RSACryptoServiceProvider` returning 1024-bits keys? I guess determining whether the instance returned by `RSA.Create()` is a `RSACryptoServiceProvider` and manually re-creating it with `dwKeySize = 2048` is the only option on .NET Desktop, right?

**Comment by bartonjs** [comment]
@PinpointTownes Ugh.  I had forgotten about that bit of quirkdom.   If you're okay with messing with process defaults you could make a one-shot that reflect-searched for CryptoConfig and then reflect registered RSACng as the RSA provider.

Assuming that you're not okay with that; yeah, a \#if for desktop is probably the best bet.  :frowning:.
