### ISSUE TITLE
Best practice to implement OpenId Connect Server with resource owner credential flow

### ISSUE THREAD

**Issue by plakhlani** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#208]
Hello,

I want to know best practice way to implement open id connect server in asp.net vnext with resource owner credentials flow.

I see provided example in samples project but I do not understand following:

1. How/Where to validate asp.net identity username and password and set claims for their user name, all roles etc?

2. How to separate authorization of the request when it comes with bearer token vs it comes from asp.net mvc application context?
3. Implement it with the best possible way to securely transmit and store bear token and refresh token (in mobile secure storage I guess).

Thanks
Prashant

**Comment by PinpointTownes** [comment]
Hey,

> I want to know best practice way to implement open id connect server in asp.net vnext with resource owner credentials flow.

I'd recommend using [OpenIddict](https://github.com/openiddict/core) for this task as it implements it for you. You can find more information on @capesean's blog: http://capesean.co.za/blog/asp-net-5-jwt-tokens

If you don't want to use OpenIddict, you can take a look at how it implements the resource owner password credentials grant: https://github.com/openiddict/core/blob/dev/src/OpenIddict.Core/OpenIddictProvider.Exchange.cs#L172-L244

> I see provided example in samples project but I do not understand following:

The sample doesn't implement the resource owner password credentials grant and favors interactive flows like code or implicit. For more information, you can read this SO answer: http://stackoverflow.com/a/30857524/542757.

> How/Where to validate asp.net identity username and password and set claims for their user name, all roles etc?

You need to override the `GrantResourceOwnerCredentials` event to implement the resource owner password credentials grant. 

> How to separate authorization of the request when it comes with bearer token vs it comes from asp.net mvc application context?

I'm not sure to understand your question, sorry.

> Implement it with the best possible way to securely transmit and store bear token and refresh token (in mobile secure storage I guess).

Easy: use transport security like SSL/TLS, as required by the OAuth2 specification :smile: 

Depending on the device platform, you may be able to use strong APIs (like the KeyChain on iOS) to store your refresh token in a safe place.

Good luck :+1:
