### ISSUE TITLE
[Authorize] attribute redirect to /Account/Login

### ISSUE THREAD

**Issue by dewebeloper** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#210]
I have implemented OpenIdConnectServer like 
```
app.UseOpenIdConnectServer(options =>
{
        options.AllowInsecureHttp = true;
        options.ApplicationCanDisplayErrors = true;
	options.TokenEndpointPath = "/token";
	options.AccessTokenLifetime = TimeSpan.FromMinutes(30);
	options.AccessTokenFormat = new WbjwtFormat(issuer, ctx);
	options.Provider = new AuthorizationServerProvider(ctx);
});
```

And also have 
```
app.UseJwtBearerAuthentication(options =>
{
	options.AutomaticAuthenticate = true;
	options.Audience = audienceId;
	options.Authority = authority ;
	options.RequireHttpsMetadata = false;
});
```

on controller I have 

```
[Route("api/companies")]
[Authorize]
public class CompaniesController : BaseController
{}

```
First issue is when I make request without Authentication header I have been redirected to /Account/Login route.
When I include Authentication header then all is fine, I get asked result.

But if my token has expired then I get 
`SecurityTokenInvalidSignatureException: IDX10503: Signature validation failed. Keys tried: 'System.IdentityModel.Tokens.RsaSecurityKey , KeyId: UQRP_TWJNGS4OHI3Z5ITEAP_FKBKQXC1W0UF7RLC`

```
System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
Microsoft.AspNet.Authentication.JwtBearer.JwtBearerHandler.<HandleAuthenticateAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNet.Authentication.JwtBearer.JwtBearerHandler.<HandleAuthenticateAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNet.Authentication.AuthenticationHandler`1.<InitializeAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNet.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
```

my dependencies are 

```
"dependencies": {
		"Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-final",
		"Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
		"Microsoft.AspNet.StaticFiles": "1.0.0-rc1-final",
		"Microsoft.AspNet.Hosting": "1.0.0-rc1-final",
		"Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
		"Microsoft.AspNet.Diagnostics": "1.0.0-rc1-final",
		"WhiteBee.CentralConfig.Data": "1.0.0-*",
		"EntityFramework.MicrosoftSqlServer": "7.0.0-rc1-final",
		"EntityFramework.SqlServerCompact40": "7.0.0-rc1-final",
		"EntityFramework.Commands": "7.0.0-rc1-final",
		"Microsoft.CSharp": "4.0.0",
		"Microsoft.AspNet.Identity": "3.0.0-rc1-final",
		"Microsoft.AspNet.Authentication.JwtBearer": "1.0.0-rc1-final",
		"AspNet.Security.OpenIdConnect.Server": "1.0.0-beta4",
		"AspNet.Security.OpenIdConnect.Extensions": "1.0.0-beta4",
		"Microsoft.AspNet.Security.DataProtection": "1.0.0-beta3",
		"WhiteBee.CentralConfig.Repo": "1.0.0-*",
		"Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-rc1-final",
		"Microsoft.Owin.Security": "3.0.1",
		"Thinktecture.IdentityModel.Core": "1.4.0"
	}

```

all that on x86 architeture

**Comment by PinpointTownes** [comment]
> First issue is when I make request without Authentication header I have been redirected to /Account/Login route.
When I include Authentication header then all is fine, I get asked result.

https://github.com/openiddict/openiddict-core/issues/58

> But if my token has expired then I get 
SecurityTokenInvalidSignatureException: IDX10503: Signature validation failed. Keys tried: 'System.IdentityModel.Tokens.RsaSecurityKey , KeyId: UQRP_TWJNGS4OHI3Z5ITEAP_FKBKQXC1W0UF7RLC

This exception happens when the signing key exposed by the JWKS endpoint doesn't correspond to the key used to sign the token. Are you using ASOS in a distributed environment? You should also share your `WbjwtFormat`, to make sure you're not missing something obvious.

**Comment by dewebeloper** [comment]
```
public string Protect(AuthenticationTicket data)
	    {
			if (data == null)
			{
				throw new ArgumentNullException(nameof(data));
			}

			string audienceId = _dbctx.Settings.Where(a => a.SettingKey == "AudienceId").Select(a => a.SettingValue).FirstOrDefault(); 
			string symmetricKeyAsBase128 = _dbctx.Settings.Where(a => a.SettingKey == "AudienceSecret").Select(a => a.SettingValue).FirstOrDefault(); 

			var keyByteArray = TextEncodings.Base64Url.Decode(symmetricKeyAsBase128);

			//var signingCredentials = new SigningCredentials(keyByteArray, SignatureAlgorithm, DigestAlgorithm);

			var issued = data.Properties.IssuedUtc;

			var expires = data.Properties.ExpiresUtc;

			var token = new JwtSecurityToken(_issuer, audienceId, data.Principal.Claims, issued?.UtcDateTime, expires?.UtcDateTime);
			//var token = new JwtSecurityToken(_issuer, audienceId, data.Principal.Claims, issued?.UtcDateTime, expires?.UtcDateTime, signingCredentials);

			var handler = new JwtSecurityTokenHandler();

			var jwt = handler.WriteToken(token);

			return jwt;
		}
```

Here I have issue with SigningCredentials. 
`The type 'SigningCredentials' exists in both 'System.IdentityModel.Tokens, Version=5.0.0.112, Culture=neutral, PublicKeyToken=31bf3856ad364e35' and 'System.IdentityModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'`
I'm not sure how to solve that. Also I'm tested token without line 
`options.AccessTokenFormat = new WbjwtFormat(issuer, ctx);`
but again have same SecurityTokenExpiredException: IDX10223: issue.

**Comment by PinpointTownes** [comment]
TBH, all this stuff looks highly suspicious :smile: 

Your custom data format uses symmetric keys but the JWT bearer middleware options will use the asymmetric generated and exposed by the JWKS endpoint. Obviously, this can't work.

ASOS beta4 (the version you're using) issues JWT access tokens by default, so there's no need to roll your own data format class. In beta5, it's no longer the default format, but you just have to call `options.UseJwtTokens()` to stop using opaque tokens.

**Comment by dewebeloper** [comment]
Ok, let me try with that, Thaks

**Comment by PinpointTownes** [comment]
FYI, the dependency issue you're seeing is due to the fact you're referencing `Thinktecture.IdentityModel.Core`, that relies on IdentityModel 4, while ASOS uses IdentityModel 5. You can't have different versions in the same app.

**Comment by dewebeloper** [comment]
What namespace is options.UseJwtTokens(); I can't reference that.
And just to be clear that is part of UseOpenIdConnectServer?
```
app.UseOpenIdConnectServer(options =>
			{
				options.AllowInsecureHttp = true;
				options.ApplicationCanDisplayErrors = true;
				options.TokenEndpointPath = "/token";
				options.AccessTokenLifetime = TimeSpan.FromMinutes(30);
				//options.AccessTokenFormat = new WbjwtFormat(issuer, ctx);
				options.UseJwtTokens();
				options.Provider = new AuthorizationServerProvider(ctx);
			});
```

**Comment by PinpointTownes** [comment]
**`UseJwtTokens()` doesn't exist in beta4 because it's the default format**. It was added in beta5.

**Comment by dewebeloper** [comment]
Beta5 is not on nuget. Where I can download beta5?

**Comment by PinpointTownes** [comment]
As indicated by the README.md file, on our nightly builds repository: https://www.myget.org/gallery/aspnet-contrib.

But note that it requires the latest ASP.NET Core RC2 packages. Expect many breaking changes.

**Comment by dewebeloper** [comment]
Ok. Thank you

**Comment by fmdufour** [comment]
Hey, i had the same issue you are having.

It took me hours to debug and find what I was doing wrong.

The problem is with having:

`app.useIdentity()` on your Startup configure.

this extension adds cookie authentication scheme.

**Comment by singlewind** [comment]
@PinpointTownes I didn't realize you have built so many extension for different services already. Thumb up!!

**Comment by PinpointTownes** [comment]
@singlewind thanks :smile:
