### ISSUE TITLE
How can I decode an idtoken manually?

### ISSUE THREAD

**Issue by singlewind** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#215]
I use ASOS for my OP. However, I need make an integration to a legacy system by decode/validate the token by following code.

`var handler = new JwtSecurityTokenHandler();
 SecurityToken jwt;
 var id = handler.ValidateToken(token, parameters, out jwt);`

If I haven't specified a certificate on the OP, by default I think ASOS signed the token by IDataProvider no matter created from IIS or DPAPI. How can I pass the application secret key to validate this token?

**Comment by PinpointTownes** [comment]
Identity tokens are never protected by the data protection block (unlike the access tokens, when you don't opt for the JWT format).

They are just signed by the signing key you register in the options or by a dynamically generated key. In both cases, you can retrieve the public key from the JWKS endpoint (http://server:port/.well-known/jwks)

**Comment by singlewind** [comment]
I see, thanks

**Comment by singlewind** [comment]
@PinpointTownes I saw your posted issue on https://github.com/aspnet/Security/issues/430, Currently, how does OpenIDAuthentication middleware work out the key if they haven't support .NET to fetch the security token on JWKS at moment?

**Comment by PinpointTownes** [comment]
The issue you mention is about exposing the client public keys so the OpenID Connect server can retrieve them to encrypt the identity token before returning.

Of course, the OIDC client middleware supports retrieving the JWK keys from the OpenID Connect server's JWKS endpoint.

**Comment by singlewind** [comment]
@PinpointTownes just could not find the source code in OIDC to fetch the keys. I think it is in one of IConfigurationManager<>. Just could not find the default implementation of it. Do you have any hint for me?

**Comment by PinpointTownes** [comment]
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/KDev/src/Microsoft.IdentityModel.Protocols.OpenIdConnect/Configuration/OpenIdConnectConfigurationRetriever.cs

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/KDev/src/Microsoft.IdentityModel.Protocols.OpenIdConnect/Configuration/OpenIdConnectConfiguration.cs

**Comment by singlewind** [comment]
Thanks very much
