### ISSUE TITLE
Coding guidelines

### ISSUE THREAD

**Issue by DovydasNavickas** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#217]
I've started working on [AspNet.Security.OAuth.Extensions/issues/2](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Extensions/issues/2) and it is quite frustrating to have code style different than https://github.com/aspnet/Security, https://github.com/aspnet/Home or basically any AspNet repository.

As it is stated in the [aspnet/Home Wiki -> Engineering guidelines -> Coding guidelines](https://github.com/aspnet/Home/wiki/Engineering-guidelines#coding-style-guidelines--general):
>The most general guideline is that we use all the VS default settings in terms of code formatting, except that we put `System` namespaces before other namespaces (this used to be the default in VS, but it changed in a more recent version of VS).
>
>1. Use four spaces of indentation (no tabs)
>2. Use `_camelCase` for private fields
>3. Avoid `this.` unless absolutely necessary
>4. Always specify member visiblity, even if it's the default (i.e. `private string _foo;` not `string _foo;`)

Which makes sense. If you want to contribute, you shouldn't care about configuring VS to custom indention, new lines or any other options OR at least as little as possible.

Now, when one wants to work on `aspnet-contrib` project, one needs to customize VS and there are even no guidelines on that in `aspnet-contrib/Home` repository as there is in `aspnet/Home` one. In fact, the `aspnet-contrib/Home` is empty at all.

Which begs the question: Why does `aspnet-contrib` code have different code style than Microsoft's `aspnet` repositories?

And more importantly: Maybe we should convert `aspnet-contrib` repositories to the same coding style that Microsoft uses in `aspnet` repositories?

As we are in a transition from `dnx` to `dotnet` CLIs, `AspNet` to `AspNetCore` namespace and even more (which is quite a big transition), it's quite a good timing to do this change.

What do guys think?

@PinpointTownes @MonkeyJamboree

**Comment by PinpointTownes** [comment]
> In fact, the aspnet-contrib/Home is empty at all.

That's @davidfowl's fault. He asked me to create a Home repo and give him write access but he totally forgot to create the README file :smile: 

> Which begs the question: Why does aspnet-contrib code have different code style than Microsoft's aspnet repositories?

For a simple (pragmatic) reason: it's the code style I prefer and use for most stuff: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/issues/31#issuecomment-138538536 :smile: 

> Which makes sense. If you want to contribute, you shouldn't care about configuring VS to custom indention, new lines or any other options OR at least as little as possible.

Actually, I'm very cool with contributions: you can submit a PR using the code style you want. I'll just update it before merging it.

**Comment by DovydasNavickas** [comment]
I feared it's gonna be your answer... :smile:
Did you settle on some tool for controlling code style conversion to K&R?

If so, I'd like to use that for vice-versa conversion then.. :smile: 
Honestly talking, I don't really care that much, what style the code is, as long as the tooling does not interfere. But as I see from the comment you referenced, the `.vssettings` are global, aren't they? Which would make my whole team mad :smile: (Except the frontend guys. We use K&R in frontend, but it's simply weird to use it with C# somewhy..)
