### ISSUE TITLE
Custom claims differences.

### ISSUE THREAD

**Issue by Stalso** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#220]
Hello, when I use last release of ASOS and want to add custom claims to access token, I should add it in `destination` key of `Claim.Properties` dictionary and the destination should have value `token`. 

But when I see in your code know (in current builds) , you add value 'access_token' in `destinations` key of `Claim.Properties` dictionary. What is the reason?

**Comment by PinpointTownes** [comment]
Hey,

> But when I see in your code know (in current builds) , you add value 'access_token' in destinations key of Claim.Properties dictionary. What is the reason?

These 2 changes are part of a more global API polishing between beta4, beta5 and the future beta version.

The `destination` property has been replaced by `destinations` to make it consistent with the other space-separated properties, that all use a plural form.

The `token` -> `access_token` change makes clearer the fact `token` is actually an access token, not just a token whose usage is not determined (refresh token, identity token, access token).

**Comment by PinpointTownes** [comment]
Oh and FYI, all the properties have been prefixed with a dot in the latest nightly builds (like the properties used internally by ASP.NET) to make sure we don't override your custom properties.

So `destinations` is now `.destinations` (BTW, you should strongly consider using our extensions instead of hardcoded strings).

**Comment by Stalso** [comment]
Thank you.  Do you have any time to make some docs and samples for the server?  It is really hard work to follow you now.  However your server is the best and clearest.  Especially in compare with IdentityServer

**Comment by PinpointTownes** [comment]
> Do you have any time to make some docs and samples for the server?

Sadly no, writing samples and documentation is really a time-consuming task. That said, it's definitely on my todo-list and will be one of my main priorities for RTM.

> It is really hard work to follow you now.

Yeah, sorry about that. Many things have changed between beta4 and beta5 but things will stabilize with the next beta, as I'll mainly focus on unit testing and performance.

> However your server is the best and clearest. Especially in compare with IdentityServer

Thanks for the kind words :smile:

**Comment by Stalso** [comment]
But how can I refactor such things?  Maybe I should wait for rc2?

**Comment by PinpointTownes** [comment]
I'd recommend using the `SetDestinations` extension: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/blob/vNext/samples/Mvc/Mvc.Server/Controllers/AuthorizationController.cs#L101-L102

Alternatively, you can also use the `AddClaim` extension that takes a params string array:

```csharp
identity.AddClaim(ClaimTypes.Name, "display name",
    OpenIdConnectConstants.Destinations.AccessToken,
    OpenIdConnectConstants.Destinations.IdentityToken);
```

> In fact, if you want I would like to contribute your project, how can I do it?

Thanks!

There are a few work items labelled with the "help wanted" tag. Here's one, that consists in adding new log messages and improving the existing ones: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/issues/52.

**Comment by BrainCrumbz** [comment]
Linked source does not work anymore (branch changed). Is that https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/blob/release/samples/Mvc/Mvc.Server/Controllers/AuthorizationController.cs#L102 now ?

**Comment by PinpointTownes** [comment]
Yep.
