### ISSUE TITLE
Hosting question in Azure

### ISSUE THREAD

**Issue by singlewind** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#221]
When we use DPAPI, the default key is stored in %LOCALAPPDATA%\ASP.NET\aspnet-contrib\aspnet-oidc-server by ASOS. However, only keys under %LOCALAPPDATA%\ASP.NET\DataProtection-Keys get synced via all the machines and isolated by application to prevent malicious access. To achieve zero configuration for scale, what do you think move the keys into its default folder?

**Comment by singlewind** [comment]
@PinpointTownes After go through your source code, I think I found the answer, if not .NET451, it will generate keys under %LOCALAPPDATA%\ASP.NET\aspnet-contrib\aspnet-oidc-server. I use .NET46, so this is the reason.

**Comment by PinpointTownes** [comment]
> What do you think move the keys into its default folder?

Storing our own keys in the default Data Protection folder would like cause weird issues as they don't use the same format at all (the format we used is much simpler), specially since the Data Protection block is particularly prone to key ring poisoning.

When going live, I recommend using a X509 certificate, stored in the machine store.

In the future, I'd like to work on a KeyManagement companion to offer a much better experience to manage asymmetric and symmetric keys (the DP KeyManagement stack cannot be extended... blame @blowdart for that).

**Comment by blowdart** [comment]
You fibber. You can write your own store. What more do you need? :p

Also, why not combine the two? Protect the keyring with a shared X509 Cert.

**Comment by PinpointTownes** [comment]
> You fibber. You can write your own store. What more do you need? :p

DP KeyManagement doesn't support asymmetric keys and doesn't allow retrieving a `RSA` instance or exporting the key materiel. For all these reasons, we can't use DP KeyManagement to manage our signing keys.

**Comment by blowdart** [comment]
Ah got you. That is on purpose. Once you need the ability to get at the private key we figure you're mature enough to switch from data protection. It's aim is to provide people with something simple they don't need to think about.

**Comment by PinpointTownes** [comment]
> Once you need the ability to get at the private key we figure you're mature enough to switch from data protection.

Actually, being able to export the private key is not mandatory for us. All we need is a `RSA` instance being able to sign stuff (this can be a `RSACryptoServiceProvider` or a `RSACng` backed with a HSM that doesn't allow exporting the private key).

**Comment by blowdart** [comment]
But we'd still need to support "just signing" then. Which is another decision for developers to make, and not one they do correctly most of the time. I'm afraid you're not the target market for data protection, it tries to reduce the number of crypto decisions people need to make in favour of doing the safest possible work.

**Comment by PinpointTownes** [comment]
> I'm afraid you're not the target market for data protection, it tries to reduce the number of crypto decisions people need to make in favour of doing the safest possible work.

TBH, I can't find a valid reason not to support advanced scenarios in the KeyManagement stack. It's definitely not a stack developers will want to use or implement themselves (in most cases, they only need `IDataProtector` anyway :smile:)

**Comment by blowdart** [comment]
The reason is it's not meant to be advanced, it's meant to be easy and foolproof. Once you get into adding bells and whistles and options it ceases to be that.

**Comment by singlewind** [comment]
@PinpointTownes Let me correct myself about this. Actually, the key do get synced in Azure. 
![image](https://cloud.githubusercontent.com/assets/7637/13944383/a286dede-f050-11e5-82f9-77134bd0036b.png)
