### ISSUE TITLE
Any sample to user both server + client in 1 application

### ISSUE THREAD

**Issue by samuraitruong** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#223]
Currently, I am looking for develop asp.net 5 + web API  support  for Angularjs front-end. After many digging they all reached me to this library. But i couldn't find any sample that we run both client + server in sample application.

reason for this is my application is quite small, I don't need to have separate openID server for it.

**Comment by PinpointTownes** [comment]
ICYMI, here's the answer @chrisjmccrum gave you on Gitter:

> I believe @capesean created an example a while back - it may be a little outdated but it should provide some direction https://github.com/capesean/openiddict-test/tree/master/src/openiddict-test/wwwroot
http://capesean.co.za/blog/asp-net-5-jwt-tokens/

**Comment by capesean** [comment]
Outdated again!? That didnt take long! :)

**Comment by PinpointTownes** [comment]
@capesean yep, a few things changed recently in both ASOS and OpenIddict :smile:
