### ISSUE TITLE
Custom formatting mechanism for error payload

### ISSUE THREAD

**Issue by vmachacek** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#240]
Hi, we are trying to unify server responses thru our API and currently OpenIdConnect.Server is not following our guidelines. It would be nice to have a option to register function which would take existing payload and transform it something else. I think the way now would be to register extra piece of middle-ware to intercept those calls I need to alter and do it on my own, even after OpenIdConnect.Server wrote to the response. 

What do you guys think? Do I'm missing something? Is it correct way of doing it?

Thanks for your effort.

**Comment by PinpointTownes** [comment]
Hey,

Currently, the `ApplyXYZResponse` (e.g `ApplyAuthorizationResponse`/`ApplyTokenResponse`) events are not invoked when an error is directly returned by ASOS to the client application so you can't intercept the error responses using the notifications model.

This is something we may change to allow customizing the error responses in the future, but it might be too late to include that in the next beta, that should be released in the next few weeks.

Writing a middleware intercepting the response body might be a good alternative in the meantime.

**Comment by PinpointTownes** [comment]
Curious: why are you trying to alter/replace the error payloads?

**Comment by vmachacek** [comment]
Hi, and thanks for such a quick response, as I described earlier, we have task related to refactoring and we should unify ALL the responses form the API to fallow same data contracts. Basically we will be returning proprietary code which will describe what happened on the server to the client.  And also enumeration info/error/warning/success and message in English. However the point is to have same data contract from the OpenIdConnect.Server as rest of the app.

**Comment by PinpointTownes** [comment]
> And also enumeration info/error/warning/success and message in English.

FYI, the ultimate plan is to use the new localization stack to offer a simple way to localize all the built-in error messages.

**Comment by PinpointTownes** [comment]
Update: I've decided to include this change in the upcoming release (ASOS beta5): all the `ApplyXYZResponse` events will now be invoked before returning an error response, including the built-in errors returned by ASOS itself as part of the basic request validation checks.

This change will give you full control over error responses and will allow you to determine how the error is serialized and returned to the caller: by using the default logic (default option), by using your own one (via `context.HandleResponse()`) or by invoking the next middleware in the pipeline (via `context.SkipToNextMiddleware()`).

The PR is ready to be sent, but it needs some additional testing. Expect a new version in the next few days.

**Comment by vmachacek** [comment]
Thanks! That's a great news!

**Comment by PinpointTownes** [comment]
Done, thanks for your patience :clap:
