### ISSUE TITLE
Visual Studio errors

### ISSUE THREAD

**Issue by Alex-111** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#244]
I tried to build the project in VS 2015 but I have the following issue:

Errors in D:\temp\AspNet.Security.OpenIdConnect.Server-dev\samples\Mvc\Mvc.Client\project.json
    "netcoreapp1.0" is an unsupported framework.

I have latest updates of VS 2015 installed...

Any ideas what goes wrong here?

**Comment by PinpointTownes** [comment]
Like the recent ASP.NET Core projects, the aspnet-contrib bits no longer work with DNX/VS.
You need to use .NET CLI to compile and run them. I'd recommend using VS Code until we get the appropriate VS tooling: http://tattoocoder.azurewebsites.net/setting-up-asp-net-core-debugging-in-vs-code/.

**Comment by viviancpy** [comment]
Could you give some hints how to use .NET CLI to compile and run ?

**Comment by PinpointTownes** [comment]
.NET CLI works similarly to DNX/DNU:

Mvc.Client: `dotnet restore` + `dotnet run --framework net451 server.urls=http://localhost:53507/`
Mvc.Server: `dotnet restore` + `dotnet run --framework net451 server.urls=http://localhost:54540/`
