### ISSUE TITLE
"jti" Claim support

### ISSUE THREAD

**Issue by MonkeyJamboree** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#246]
The Introspection RFC/Spec response has an optional "jti" Claim for a JWT token identifier that could be returned when JWT access tokens are being used.

See https://tools.ietf.org/html/rfc7662#section-2.2 for more info.

**Comment by PinpointTownes** [comment]
It's technically a new feature so it should in theory wait for ASOS beta6. That said, it's trivial enough to implement and will likely be needed by OpenIddict when introducing refresh token revocation, so I marked it for 1.0.0-beta5 and I'm about to submit a PR to merge it in the release branch.

A few details about how I've decided to implement it:
* Every authentication ticket created by ASOS (= every code/token) will now have a "unique identifier" generated by a crypto RNG that will be stored as an authentication property (`.unique_id`).

* New `AuthenticationTicket` extensions will be added to make working with this new concept easy: `AuthenticationTicket.GetUniqueId()` and `AuthenticationTicket.SetUniqueId(string identifier)`.

* When using non-opaque tokens, the serialization process is lossy so we need to flow the identifier as a claim: `token_id` if the security token handler used to serialize the token is not a JWT handler, `jti` if it is. The `.unique_id` authentication property will be automatically *restored* during deserialization using one of these 2 claims.

* The introspection endpoint will be updated to expose a `jti` claim containing the unique token identifier (it will basically call `AuthenticationTicket.GetUniqueId()`).

@MonkeyJamboree do we want to update the introspection middleware to extract this property and restore the `.unique_id` authentication property in the ticket for release?

**Comment by MonkeyJamboree** [comment]
Wow, that's quick! Some feedback:

I like the idea of using a crypto rng for the identifier, but why do that instead of using something like Guid.NewGuid()? The main concern seems to be with collisions rather than security of an identifier, since the identifier itself isn't the token itself with JWTs, and with opaque tokens, validating the data should happen anyway.

I have concerns with regard to the `.unique_id` property. It seems too close to the `UniqueIdentifier` property for the `OpenIdConnectMessage` in interactive flows. Further, I think `token_id` makes sense for all tokens, whether JWT, Opaque, or some other type of token, because a token universally would probably have an ID if persisted somewhere, unless there's an explicit reason for the discrepancy in naming?

I do think it pertinent to restore the property on the Introspection middleware, so it can then potentially be used to prevent replay attacks per https://tools.ietf.org/html/rfc7519#section-4.1.7.

**Comment by PinpointTownes** [comment]
> I like the idea of using a crypto rng for the identifier, but why do that instead of using something like Guid.NewGuid()? The main concern seems to be with collisions rather than security of an identifier, since the identifier itself isn't the token itself with JWTs, and with opaque tokens, validating the data should happen anyway.

When issuing an authorization code, we currently generate a unique cache key and return it to the client app instead of the real code, stored in the distributed cache (which allows removing the code from the cache when receiving a token request, to prevent replay attacks). The "cache key" must have enough entropy and using a crypto RNG is the best way to guarantee that. 

Since we were already generating a unique key for the authorization code, I preferred reusing it as the token identifier. The fact it's used for the other tokens is just for consistency. 

That said, if you think we should use a simpler identifier for the jti feature (e.g a GUID), I'm fine changing that. 

> I have concerns with regard to the .unique_id property. It seems too close to the UniqueIdentifier property for the OpenIdConnectMessage in interactive flows. Further, I think token_id makes sense for all tokens, whether JWT, Opaque, or some other type of token, because a token universally would probably have an ID if persisted somewhere, unless there's an explicit reason for the discrepancy in naming?

FYI, the `GetUniqueIdentifier`/`SetUniqueIdentifier` methods extending `OpenIdConnectMessage` have been renamed to `GetRequestId` and `SetRequestId` in RC2, so the risk of confusion is rather low. That said, I'm fine replacing `.unique_id` by `.token_id` if you think it's clearer (though semantically, an authentication ticket is not exactly a token).

**Comment by PinpointTownes** [comment]
> I do think it pertinent to restore the property on the Introspection middleware, so it can then potentially be used to prevent replay attacks per https://tools.ietf.org/html/rfc7519#section-4.1.7.

Do you want to send a PR? :smile:

**Comment by DovydasNavickas** [comment]
If I get to add my 5 cents, quite reasonable arguments about GUID can be found here:
http://stackoverflow.com/a/804505/845603

GUID ensures uniqueness, not security. It can be predictable, but not duplicate. Which is why it makes sense to use GUID as a unique identifier.

Also, as it is meant to be unique, we can interchange it later, if we see any problems arise (which in either case seems not really probably to me). Or maybe even make it pluggable (an event?) for generating the id. Although an event might be a bit too easy to mess up with for a bad guy who can access the code (an obscure way of adding predictable codes... Or I'm just too paranoid here :smile:)

That said, if we have crypto RNG value that is already generated, reusing that would be more efficient, I suppose. And if it has enough uniqueness, it is totally valid for the purpose.

And for the name of the property, I think it is reasonable to use `.ticket_id`, if it's gonna be used only for authentication tickets. If it's gonna identify token as well, `.unique_id` might be a better name.

**Comment by MonkeyJamboree** [comment]
> When issuing an authorization code, we currently generate a unique cache key and return it to the client app instead of the real code, stored in the distributed cache (which allows removing the code from the cache when receiving a token request, to prevent replay attacks). The "cache key" must have enough entropy and using a crypto RNG is the best way to guarantee that.

I'm not sure how the approach for looking up authorization codes is any different than approaches suggested for refresh tokens. You'd pass the ID of the saved token (that has the serialized ticket) to the Client as well, and that's the same approach I've used for opaque access tokens. It not only helps prevent replay attacks, but allows for easier revocation of those independent items.

I agree with @DovydasNavickas in that Guid should have sufficient uniqueness for this, and wonder about whether the algorithms provided by a CSPRNG would have the same level of uniqueness.

> And for the name of the property, I think it is reasonable to use .ticket_id, if it's gonna be used only for authentication tickets. If it's gonna identify token as well, .unique_id might be a better name.

I think `ticket_id` makes sense as well, if ASOS will be creating IDs for every ticket generated, regardless of whether it's for an authorization code, access token, etc. `unique_id` just seems too generic to me - it's unique, sure, but what is it unique for?

> Do you want to send a PR? :smile:

Haha, I'll see what I can do, though I may not be able to get to it... Will the PR actually be merged in within a reasonable timeframe? :wink:

**Comment by PinpointTownes** [comment]
> Also, as it is meant to be unique, we can interchange it later, if we see any problems arise (which in either case seems not really probably to me). Or maybe even make it pluggable (an event?) for generating the id. Although an event might be a bit too easy to mess up with for a bad guy who can access the code (an obscure way of adding predictable codes... Or I'm just too paranoid here :smile:)

One will be able to use the `Serialize(AccessToken)` event to override the default identifier. IMHO, there's no point having a dedicated event for such a trivial thing.

> I'm not sure how the approach for looking up authorization codes is any different than approaches suggested for refresh tokens. You'd pass the ID of the saved token (that has the serialized ticket) to the Client as well, and that's the same approach I've used for opaque access tokens. It not only helps prevent replay attacks, but allows for easier revocation of those independent items.

Refresh tokens are not stored in the distributed cache but are returned as-is so we don't have to generate a unique cache key for them.

> Haha, I'll see what I can do, though I may not be able to get to it... Will the PR actually be merged in within a reasonable timeframe? :wink:

lol, you're trolling too hard, 2 weeks was actually a reasonable timeframe (I had to wait 1 month and a half for my `SaveTokensAsClaims` PR for the OAuth2 middleware to be merged by the ASP.NET team :trollface:)

I'll update the PR to use GUIDs everywhere, but `SerializeAuthorizationCodeAsync` will keep using a cryptorandom 256-bit string for the code "cache key".

**Comment by MonkeyJamboree** [comment]
> Refresh tokens are not stored in the distributed cache but are returned as-is so we don't have to generate a unique cache key for them.

How does this change if someone is saving authorization codes to a database in the `Serialize(AuthorizationCode)` event? Is there still a reason to use the distributed cache with this? (Or, inversely, a reason to store them in a database via the serialize event since they're being cached?)

> lol, you're trolling too hard, 2 weeks was actually a reasonable timeframe (I had to wait 1 month and a half for my SaveTokensAsClaims PR for the OAuth2 middleware to be merged by the ASP.NET team :trollface:)

Ahh, My bad. This is the first project (outside of work) that I've contributed to, and you've been pretty quick with PRs before that. Over a month is a long time though haha!

**Comment by PinpointTownes** [comment]
Done :tada: 

ASOS: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/53afe6cf91e5d33360fae9cb437127ecd192165c.
Introspection middleware: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Extensions/commit/4bdc5ae8b6db735267559c6e67597a2c11ff786b.
