### ISSUE TITLE
Include All Standard User Claim Types

### ISSUE THREAD

**Issue by MonkeyJamboree** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#247]
There are claim types missing in the constants for many of the standard claims, as seen at http://openid.net/specs/openid-connect-core-1_0.html#StandardClaims. Having these values available for consumers for id token, userinfo, and introspection usage would be beneficial.

**Comment by PinpointTownes** [comment]
Good idea :smile: 

It's a minor change so if you want to include that in beta5, feel free to submit a PR targeting the `release` branch. If you think it can wait, we'll do that for beta6.

**Comment by MonkeyJamboree** [comment]
I'd like to see it in there sooner than later. I'll throw together a quick PR.

**Comment by PinpointTownes** [comment]
Done, thanks @MonkeyJamboree: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/9190ab49d9ab2696ca7937bb74c2eef64fd23767 :tada: 

I opened a separate ticket to determine whether the claims should be grouped in the next version: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/issues/257.
