### ISSUE TITLE
Add support for the claims parameter

### ISSUE THREAD

**Issue by MonkeyJamboree** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#248]
Something a bit more advanced that would be nice to have is support for the `claims` parameter, as shown in http://openid.net/specs/openid-connect-core-1_0.html#ClaimsParameter. This parameter seems to be meant as a way to get non-standard claims from the AS, as well as a way to dictate what claims should be returned in what places (id token vs userinfo request).

**Comment by PinpointTownes** [comment]
Closing, as the `claims` parameter (exposed as a `JObject`) is now a first class citizen in ASOS 1.0 RTM: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/pull/410/commits/65651cf90e7b1c22300fea82ed49c757dbf93749
