### ISSUE TITLE
How to send additional user info when token is generated?

### ISSUE THREAD

**Issue by BrainCrumbz** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#266]
We're aware that one can add custom claims in authentication provider and have them sent back to the client (e.g. as asked in #199 ).

But, from a web app client, we're not able to see any added `AuthenticationProperties`. We've also been through this [SO thread](http://stackoverflow.com/questions/26357054/return-more-info-to-the-client-using-oauth-bearer-tokens-generation-and-owin-in) and their linked projects, [from Leftyx](https://github.com/Leftyx/OwinWebApiBearerToken/blob/7e2c409d9a01bd14a045d8f8973c9fd0d5616bbf/OwinWebApiBearerToken/Providers/MyAuthorizationServerProvider.cs#L131) and [from tjoudeh](https://github.com/tjoudeh/AngularJSAuthentication/blob/e8e76c1f97649449a2f52d9fe5b59d9cd0d5fbc1/AngularJSAuthentication.API/Providers/SimpleAuthorizationServerProvider.cs#L145). 

Both of them override `TokenEndpoint` in order to take items from `AuthenticationProperties` and pass them to another set of parameters. API seem to have changed since their examples, here are the code bits we're trying with:

```cs
override async Task GrantResourceOwnerCredentials(GrantResourceOwnerCredentialsContext context)
{
    // ...
    identity
        .AddClaim(ClaimTypes.NameIdentifier, user.Id.ToString(), claimDestination)
        .AddClaim(ClaimTypes.Name, user.UserName, claimDestination)
        .AddClaim("CompanyName", "ACME Inc.", claimDestination);

    var ticket = new AuthenticationTicket(
        new ClaimsPrincipal(identity),
        new AuthenticationProperties(new Dictionary<string, string>()
        {
            {  "CompanyName2", "ACME Inc.2" },
        }),
        options.AuthenticationScheme);
   // ...
}

const string claimDestination = "id_token token";

public override Task TokenEndpoint(TokenEndpointContext context)
{
    var authenticationProperties = context.Ticket.Properties;

    foreach (KeyValuePair<string, string> property in authenticationProperties.Items)
    {
        /* TODO This API does not exist anymore, what's its replacement?
        context.AdditionalResponseParameters.Add(property.Key, property.Value);
        */
    }

    return EmptyTask();
}
```

On JS web app side, we can successfully see the `access_token` and decode that and find custom claims, but there's no trace of custom authentication property:

```js
access_token: "..."
expires_in: "3600"
resource: "web-admin-settings"
scope: "profile"
token_type: "bearer"
```

**Comment by BrainCrumbz** [comment]
Don't know if it has anything to do with this Asp.Net Security bug: https://github.com/aspnet/Security/issues/546

**Comment by PinpointTownes** [comment]
http://stackoverflow.com/a/34093112/542757 should put you on the right track (FYI, `TokenEndpointResponse` was renamed to `ApplyTokenResponse` in ASOS beta5, the upcoming version).

Note that doing that is now considered as a bad practice: if you don't need to support legacy clients, I'd recommend exposing the additional properties as claims in the identity token.
If you really want to do that, please avoid copying all the properties to the token response: instead, manually pick the properties you need or consider using a prefix for "public properties".

**Comment by BrainCrumbz** [comment]
1st, thanks for quick reply. Just to mention that at the moment we're working with AspNet.Security.OpenIdConnect.Server 1.0.0-beta4, and in general we're sticking with asp.net core rc1-final for now, until rc2 or better is out.

We don't need to support legacy clients, so we have free hands on that. Our scenario is to add a few bits of user info *in clear* (e.g. company name, not ID, full name, ...), things that will end up showing on UI for "aesthetic" needs, so to say. We'd like the server to send them to web client upon user authentication (resource owner password grant), so to avoid a further HTTP API call just for those visual info.

I understood that if one needs to add some bits of user info in clear, it is a waste to use token, as it makes token unnecessarily larger, and token will travel back and forth for every futher API call. That info will not be used anyway by the API server to authenticate calls, and yet has to be decrypted everytime. So it makes sense to use the AuthenticationProperties for that, as I read on some other post.

Why is this considered as a bad practice?

**Comment by PinpointTownes** [comment]
> I understood that if one needs to add some bits of user info in clear, it is a waste to use token, as it makes token unnecessarily larger, and token will travel back and forth for every futher API call. That info will not be used anyway by the API server to authenticate calls, and yet has to be decrypted everytime. So it makes sense to use the AuthenticationProperties for that, as I read on some other post.

Don't mix up access and identity tokens: those are two different things. The access token is the token you use to query an API, while the identity token is a standardized JWT token used to share authentication details with the client. You can learn more about `id_token` by reading the corresponding section in the OIDC spec: http://openid.net/specs/openid-connect-core-1_0.html#IDToken.

`identity.AddClaim("CompanyName", "ACME Inc.", "id_token")` will allow you to share your additional details via `id_token` without ever impacting the access token size.

> Why is this considered as a bad practice?

Because it's not standard. `id_token` has been specifically created for that, so there's no reason not to use it.

**Comment by BrainCrumbz** [comment]
Ok, thanks for explaining. I'll go through that section. Cheers!

**Comment by BrainCrumbz** [comment]
Argh, this will now turn into an OpenIdConnect general issue, sorry in advance:

Scenario:

1. User lands on web app login page, 
1. She enters email/pw credentials, 
1. Web app sends login request to REST API,
1. After successful reply from REST API, user can see protected pages, and web app can access protected resources through REST API

Architecture:

* Client web app running in user browser
* Only one server, responsible for: 
  * providing web app pages and JS code
  * providing REST API to authenticate user upon login
  * accessing DB to authenticate user credentials
  * providing REST API to access protected resources

... so basically that plays all roles: authentication server, identity server, resource server, ... 

Idea was that:

1. upon user trying login, web app client sends a single request to server in order to:
  1. authenticate user by credentials
  1. get a few bits of user info to show on page
  1. get a (access) token to later access protected resources
1. upon showing some page with data, web app client sends needed requests to access protected resources, also sending the token

Does all this make sense? (Thank you)

**Comment by PinpointTownes** [comment]
> Does all this make sense? (Thank you)

Yep.

**Comment by BrainCrumbz** [comment]
Now, our login request from client to server REST API returns only an `access_token` as far as I can see. That of course should be used for later accessing protected resources. 

From what I understood just now in this thread, we should also ask/receive an ID Token, containing those bits of user info, that conversely is not really needed to access protected resources. If this understanding is right, how do we obtain an ID Token *as well as* an access token from that same login REST API request?

**Comment by PinpointTownes** [comment]
> If this understanding is right, how do we obtain an ID Token as well as an access token from that same login REST API request?

It is. Just add `scope=openid` and you'll get an identity token.

**Comment by BrainCrumbz** [comment]
Thanks a lot. While skimmig through OpenId reads ([here](http://connect2id.com/learn/openid-connect)) we arrived where it says: 

> __scope__ Used to specify the scope of the requested authorisation in OAuth. The scope value `openid` signals a request for OpenID authentication and ID token.

Now it also makes more sense what is that *claim destination* parameter for. In our server, in `OpenIdConnectServerProvider`-derived class, in `GrantResourceOwnerCredentials`, when adding claims, until now they were added to `id_token token`. But now I'm sure we can add the resource access-related claims to just `token`, and the user info-related ones to just `id_token`.

**Comment by PinpointTownes** [comment]
> But now I'm sure we can add the resource access-related claims to just token, and the user info-related ones to just id_token.

Yep. As you already figured out, we improved the syntax in beta5: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/blob/release/samples/Mvc/Mvc.Server/Controllers/AuthorizationController.cs#L102. `token` was renamed to `access_token` as part of this change.

On an unrelated note, if you want to implement refresh token support in your app, don't miss these posts: 
  - http://stackoverflow.com/a/34979776/542757
  - http://stackoverflow.com/a/35732159/542757
  - http://stackoverflow.com/a/35747870/542757

**Comment by BrainCrumbz** [comment]
Yes, good to know, thank you. I like that clearer syntax. We're not switching to beta5 as of now, mostly fearing breaking changes or even newer dependencies w.r.t to beta4 (of course, please prove me wrong if needed). We're already swinging more than enough with Asp.Net Core, EF Core, Angular 2, Webpack ... you name it!

Thanks also for the pointers, will store them. We'll definitely implement refresh tokens as well, they're on our backlog.

One sub-product of this thread: please, when creating documentation, do provide a scenario like this and possibly like others. It's going to be one of the most common ever.

**Comment by PinpointTownes** [comment]
> Yes, good to know, thank you. I like that clearer syntax. We're not switching to beta5 as of now, mostly fearing breaking changes or even newer dependencies w.r.t to beta4 (of course, please prove me wrong if needed). We're already swinging more than enough with Asp.Net Core, EF Core, Angular 2, Webpack ... you name it!

It's probably better to wait a week or two, until the RC2 tooling and the final packages are released. ASOS beta5-final will be released at the same period.

> One sub-product of this thread: please, when creating documentation, do provide a scenario like this and possibly like others. It's going to be one of the most common ever.

Sure. Unfortunately, documentation is not on my radar yet, as I'd like to give OpenIddict (the ASOS implementation I recommend when using ASP.NET Core Identity) more love in the next few weeks.

**Comment by BrainCrumbz** [comment]
Yep, I read about both of those at some point. Thanks for fantastic support. Feel free to close or leave open this issue, if it might be helpful. Maybe, until documentation will be ready, can make sense to have a sort of FAQ markdown page, collecting useful Github issues / SO links, pieces of discussions.

It's not the best documentation ever, but it's better than nothing. BTW, there's a tiny doc-related PR waiting, if you have time.

**Comment by PinpointTownes** [comment]
> Maybe, until documentation will be ready, can make sense to have a sort of FAQ markdown page, collecting useful Github issues / SO links, pieces of discussions.

Good idea. Let's leave this ticket open in the meantime.

> It's not the best documentation ever, but it's better than nothing. BTW, there's a tiny doc-related PR waiting, if you have time.

Merged, thanks! :+1:

**Comment by BrainCrumbz** [comment]
Re-titled so to grab more attention by people looking for this topic.

**Comment by srivch** [comment]
hi -
i am following the grant_type='password' sample provided your samples section... (https://github.com/openiddict/openiddict-samples/tree/master/samples/PasswordFlow)
i have custom claims that get added, but i always get the access_token only...(which gets bigger and bigger) i dont see any item called id_token in my response? Am i missing something?

Note: i am not using JWT
