### ISSUE TITLE
Harden the automatic RSA key generation feature

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#269]
I've really tried my best to make this feature great, but we're still seeing `UnauthorizedAccessException`s when going to production when ASOS is unable to persist the generated keys due to a lack of write access on the keys folder (even TEMP may not be writable on some machines...).

We should probably remove this feature and force developers to use a X509 certificate or a pre-generated RSA key.

https://github.com/openiddict/openiddict-core/issues/106#issuecomment-218479102

**Comment by DovydasNavickas** [comment]
Probably a short step-by-step guide how to use X509 certificate and/or pre-generated RSA key would be quite a good solution to this.
As for for dev environments, I'd still leave the automatic key generation.

**Comment by PinpointTownes** [comment]
> As for for dev environments, I'd still leave the automatic key generation.

TBH, I'd really like to keep this feature. I'm currently testing a different approach (basically, try/catch everything related to key generation :smile:) and I'm really torn between trying to harden it and removing it completely.

**Comment by DovydasNavickas** [comment]
Well, it is super convenient up until you scale your identity server to multiple instances. But when you scale - applying certificate is a pleasant problem, well... Because you're scaling already :smile:
Try/catch all of the possible ways of writing the keys into disk could be the solution here also.

**Comment by PinpointTownes** [comment]
> Well, it is super convenient up until you scale your identity server to multiple instances.

Sure, that's why I refuse to make this feature configurable (at least, as-is) and recommend using a X.509 stored in the machine store :smile:

**Comment by singlewind** [comment]
To use the key generation feature, the DataProtector folder need persistent on the cluster and need CRUD permission on that folder. Which a lot of system administrators doesn't agree with this.

**Comment by PinpointTownes** [comment]
Yeah, it sucks. Using the registry and the special registry keys isolated by WAS offers a much safer experience anyway.

**Comment by PinpointTownes** [comment]
We'll finally keep the key generation feature, but I've added a few more try/catch to prevent weird exceptions: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/f8a56a4bdec47a62d4d7b4c2964303e574784f7d.

**Comment by PinpointTownes** [comment]
For the record: this feature was removed in beta7.
