### ISSUE TITLE
Authentication failed because the access token was invalid

### ISSUE THREAD

**Issue by cuiliang** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#276]
Hi guys, 
I just started a project using ASOS and Implicit flow.
But when calling api using access_token,  the authentication always fail with the flowing message:

`Exception thrown: 'System.FormatException' in mscorlib.ni.dll
AspNet.Security.OAuth.Validation.OAuthValidationMiddleware:Information: Bearer was not authenticated. Failure message: Authentication failed because the access token was invalid.
`

I debug code find the flowing line will return null:
`            var ticket = Options.AccessTokenFormat.Unprotect(token);
`
[LINK](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Extensions/blob/dev/src/AspNet.Security.OAuth.Validation/OAuthValidationHandler.cs#L141)

here is Startup.cs code:
`
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            loggerFactory.AddDebug();

            app.UseApplicationInsightsRequestTelemetry();

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseDatabaseErrorPage();
                app.UseBrowserLink();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
            }

            app.UseApplicationInsightsExceptionTelemetry();

            // 启用IdentityServer

            app.UseWhen(context => context.Request.Path.StartsWithSegments(new PathString("/api")), branch => {

                branch.UseCors(builder =>
                {
                    builder.AllowAnyOrigin()
                    .AllowAnyHeader()
                    .AllowAnyMethod();                    
                });

                branch.UseOAuthValidation(new OAuthValidationOptions
                {
                    AutomaticAuthenticate = true,
                    AutomaticChallenge = true
                });
            });

            app.UseWhen(context => !context.Request.Path.StartsWithSegments(new PathString("/api")), branch => {               

                branch.UseIdentity();

                // Add external authentication middleware below. To configure them please see http://go.microsoft.com/fwlink/?LinkID=532715
                branch.UseGoogleAuthentication(new GoogleOptions
                {
                    ClientId = "560027070069-37ldt4kfuohhu3m495hk2j4pjp92d382.apps.googleusercontent.com",
                    ClientSecret = "n2Q-GEw9RQjzcRbU3qhfTj8f"
                });

                branch.UseTwitterAuthentication(new TwitterOptions
                {
                    ConsumerKey = "6XaCTaLbMqfj6ww3zvZ5g",
                    ConsumerSecret = "Il2eFzGIrYhz6BWjYhVXBPQSfZuS4xoHpSSyD9PI"
                });
            });

            app.UseOpenIdConnectServer(options =>
            {
                options.Provider = new ItemzOidcProvider();
                options.ApplicationCanDisplayErrors = true;
                options.AllowInsecureHttp = true;

                var cert = new X509Certificate2(Path.Combine(_env.ContentRootPath, "idsrv3test.pfx"), "idsrv3test");
                options.SigningCredentials.AddCertificate(cert);
            });

            app.UseStaticFiles();            

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");

                routes.MapRoute(
                    name: "api",
                    template: "api/{controller=Home}/{action=Index}/{id?}"
                    );
            });
        }
`

the access_token generated is like this:
`
"CfDJ8E95-BR6LAFFirm_J6KDHhdErYj0CxnBm44qobhg_e9mVVI1W4g3pnOhGRqxw4-6vyJhwATTGkn5TqyblGD7OddaibuR-llEXfEh--euPJDsHde-HKDOtgT3DLGvJIMZnTT-LXepzl4W8WpAOOlO2vAhdUY6w8iRhIaeOJkbizqm8s3TIqhFF0B9ak0J-irse4X7JSEH-1nu0XD6lnBSjpKX5fnR-OJibYrx5fe59Oe3D86n_XfSAptZxkZPwR4NaoairO1PBeEEcQTN43RUBby6HR2jNMWugjy89FGeg9KSLnNxy_eV5J27W7XtlhAri3EyHiKAiQmV5iJOcKY7Vdy4OpG4Fe68CoNzhIfNeZg0CQDzs4qxlqI8rVVtGIlrsccIsBjmm8dAPZYy_Hd1Dzj2XZf4q_bS1EQO-iXAoI4VlJxK794vJ2IPpp8fzk9lOXQS0elWiz8TqS8qvvxYo-PX-HQp07TBq9kcXp09EFNCGontCqU-ijOal2lo1dV-dSe-K4KsHYMUCCZdHDzS5ouYPTJQzRugqSinf574jVX-ylECcqsNFVfR2BCD7tvcnWIV2N0KaVjsN_uyP_-kcSD6sh4uU1ZF0QqdYgpyT5IcDl5Mz2oTlQGvfT_tRyrh-5CecilXJ51iT7Dvkx-5voAXHQcKCbVNJ_dI0iLCZwNX6im91Z1nhF7qjL1k9JlcYJE7w712E49kMpJSIrUfid6sn67SlLg_pzCEAOi2T7dx15KW6RrNqnM6bz4UmdeZ0YRl9NgsEOE__9DLmB7s8u30EVT4krNlBnPKG3BPWEWCWdaZtp_KNtBYXHGC3n2TGh4fDDftyqaDEkdNgCU0sxKSQtOi8twSBYt35TBOQcurK3Mo8mRUomrC4mgy2AtAplJ_mzYuBY6_OKf9z797618seNru47D3mWkaD8N5JsT1XDJOO_KAbcPJSoHssW_DaVhJWCcRP6_i6Q1oeAaZq7wOKjdbjpoZZcHehxEVp570qk17WXeAlpkPa2199kJ0dL_mzkcuVMwVVxmfJJWjFzM"
`

I can't find out what is making the validation fail, please help me, thank you~

**Comment by PinpointTownes** [comment]
Hey,

Have you tried to use a lower log level to see if there's something interesting logged by the Data Protection stack?

`loggerFactory.AddDebug(LogLevel.Debug);`

Alternatively, sharing a repro would help.

**Comment by cuiliang** [comment]
It turned out to be a client problem. 
I send Bearer token with extra " wrapper. 
Request will success if " removed.
Thanks.
