### ISSUE TITLE
How to get new access_token before expire in implicit flow

### ISSUE THREAD

**Issue by cuiliang** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#277]
Dear authors, I am using implicit flow to separate server and client project.
Now I have the following two questions:
1. Because the default access_token format is not jwt, how to check it's expiration time in the client?
2. What is the official way to get a new access_token before the old one expire?

Thanks.

**Comment by PinpointTownes** [comment]
> Because the default access_token format is not jwt, how to check it's expiration time in the client?

An `expires_in` property is returned to the client application as part of the authorization response.

> What is the official way to get a new access_token before the old one expire?

You can implement `prompt=none` support in your authorization controller or at the middleware level. For more information, take a look at http://stackoverflow.com/a/36064475/542757.

Alternatively, you can use the authorization code flow to get a refresh token.

**Comment by cuiliang** [comment]
@PinpointTownes Thanks.
