### ISSUE TITLE
Cann't open the projects in vs 2015 

### ISSUE THREAD

**Issue by Elrashid** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#278]
Cann't open the projects in vs 2015 
Microsoft.DotNet.Props was not found. Confirm that the path in the <Import> declaration is correct

**Comment by PinpointTownes** [comment]
Have you installed the .NET Core tooling for VS?

**Comment by Elrashid** [comment]
https://www.microsoft.com/net/core#windows
Install .NET Core SDK
Before you start
Remove all previous versions of .NET Core from your system by using Add/Remove programs.

Visual Studio users
The best way to develop with .NET Core on Windows is to download the Visual Studio official MSI Installer [https://go.microsoft.com/fwlink/?LinkId=798481](https://go.microsoft.com/fwlink/?LinkId=798481) and the latest NuGet Manager extension for Visual Studio [https://dist.nuget.org/visualstudio-2015-vsix/v3.5.0-beta/NuGet.Tools.vsix](https://dist.nuget.org/visualstudio-2015-vsix/v3.5.0-beta/NuGet.Tools.vsix) .
