### ISSUE TITLE
Refresh tokens not generated on IIS-deployed application

### ISSUE THREAD

**Issue by videege** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#283]
I have an ASP.NET Core app using ASOS.  Locally (IIS Express), everything works great - I can get access tokens just fine and requesting the "offline_access" scope ensures the response will include a refresh token.

When I deploy this application to IIS, everything still works OK, but I am unable to retrieve refresh tokens.  I'm still requesting the "offline_access" scope but it doesn't affect the response.  Here's my configuration for ASOS:

    app.UseOpenIdConnectServer(options =>
            {
                options.Provider = new AuthorizationProvider();
                options.UseSlidingExpiration = true;
                options.AllowInsecureHttp = false;
                options.ApplicationCanDisplayErrors = true;
                options.SigningCredentials.AddKey(new RsaSecurityKey(rsa));
            });

The RSA key is different between the environments but I don't think that's the issue, since I am able to retrieve access tokens in each environment.  My authorization provider doesn't do any tampering with the refresh token - it only provides implementations of the password and refresh token grant flows.

I'm pretty stumped as to why I'm unable to get refresh tokens when the app is deployed to IIS - any ideas?

**Comment by PinpointTownes** [comment]
From `GrantResourceOwnerCredentials`, do you call `ticket.SetScopes(...)` with `offline_access` to allow ASOS to issue a refresh token?

Related topic: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/issues/186.

**Comment by videege** [comment]
Yes, I am calling `ticket.SetScopes` with a list that includes offline_access - this works locally but in the deployed version I never get a refresh token.  In `TokenEndpointResponse`, the "refresh_token" payload is null.

**Comment by PinpointTownes** [comment]
Interesting. Have you tried to enable logging to see if it has something interesting to say?

I suppose you're using ASOS beta4 (for ASP.NET Core RC1)? In the previous version, all the serialization exceptions were caught and logged, which could lead to a null refresh token. This changed in beta5 (we no longer catch exceptions)

**Comment by videege** [comment]
Yes, sorry, I should've mentioned that up front - I'm on beta4.  Thanks for the tip on logging, I will investigate and see what comes from that.

**Comment by videege** [comment]
Thanks for your help - I think I worked it out.  Logs on the server suggested a problem with permissions to the data protection folders.  I needed to change IIS to load the user profile of the user running the application pool - once I did, I started getting refresh tokens back.

**Comment by PinpointTownes** [comment]
Nice :clap: 

> I needed to change IIS to load the user profile of the user running the application pool - once I did, I started getting refresh tokens back.

Note that it's not the recommended approach. Instead, consider running [this Powershell script](https://github.com/aspnet/DataProtection/blob/dev/Provision-AutoGenKeys.ps1) to allow IIS to access the isolated AutoGenKeys registry key. The data protection stack will then store its key ring in the registry instead of the file system.

**Comment by videege** [comment]
Good to know - thanks again for your help and for your work on this awesome library!

**Comment by PinpointTownes** [comment]
Thanks for the kind word :smile:
