### ISSUE TITLE
Support ASP.NET Core RC2

### ISSUE THREAD

**Issue by robertsundstrom** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#298]
What are your plans for supporting ASP.NET Core RC2? 

Is it possible to target it with little effort?

**Comment by PinpointTownes** [comment]
If by `R2` you mean `RC2`, then it's already supported: https://www.nuget.org/packages/AspNet.Security.OpenIdConnect.Server/1.0.0-beta5-final

**Comment by robertsundstrom** [comment]
@PinpointTownes Yes. The "C" was meant to be there. 

Aha. I had a look at the sample projects earlier and noticed that they are targeting an earlier version of the framework. I did not bother to look in the main repo.  But now I see that you do indeed support RC2.

Thanks.

**Comment by robertsundstrom** [comment]
Alright. Thanks! I'll have a look at those 🙂

BTW. I'm new to this and I would like some advice.

My use case is a SPA for which the user has to be authenticated through one or many external social login providers, like Facebook or Google, in order to register an account - and the Web API would be secured through tokens issued by leveraging this API. The plan is to build apps too.

What sample does best represent this kind of scenario? I'm thinking that the Cordova scenario might be appropriate, but I'm not sure. How do I then handle external providers in code?

**Comment by PinpointTownes** [comment]
> What sample does best represent this kind of scenario?

The OpenIddict sample relies on the `AccountController` that comes with the default VS templates, so it supports both local authentication and external authentication, just like any other ASP.NET Core Identity-based web app would :smile:

**Comment by robertsundstrom** [comment]
Great! I'll have a look at it. Thanks! 🙂
