### ISSUE TITLE
Where I migrate my code from Grant* 

### ISSUE THREAD

**Issue by Crazyht** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#303]
I try to migrate my web project from Asp Core Rc2 and ASOS beta 5 to Asp Core 1.0.0 & ASOS last version. But my code for override OpenIdConnectServerProvider don't compile, I have put into Grant* method my logic to check data from DB. 

Where I can migrate this logic ?

**Comment by PinpointTownes** [comment]
> Where I can migrate this logic ?

All the `Grant*` events have been merged into `HandleTokenRequest`: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/pull/295

E.g:

```csharp
public override async Task GrantResourceOwnerCredentials(GrantResourceOwnerCredentialsContext context) {
    // ...
}
```

->

```csharp
public override async Task HandleTokenRequest(HandleTokenRequestContext context) {
    if (context.Request.IsPasswordGrantType()) {
        // ...
    }
}
```

**Comment by Crazyht** [comment]
Thanks done

**Comment by PinpointTownes** [comment]
I'll likely post a tiny guide on how to migrate to ASOS beta6 when it's officially released. In the meantime, I'll leave your ticket open to make sure it's visible.

**Comment by lcalabrese** [comment]
This ticket was pretty easy to find. Thanks. :+1: 

While we're on the topic, there were a couple other changes I discovered:
* `GrantResourceOwnerCredentialsContext.Password` is now `HandleTokenRequestContext.Request.Password`
* `GrantResourceOwnerCredentialsContext.UserName` is now `HandleTokenRequestContext.Request.Username` (note the lowercase "n" now)
