### ISSUE TITLE
Migrate 1.0.0-beta4 to beta6-final in RC1 to RTM migration

### ISSUE THREAD

**Issue by BrainCrumbz** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#310]
Hello, we've checked issue #284 and so we're merging `ValidateClientAuthentication` into `ValidateTokenRequest`. Just to be sure we're on the right track, before we used to (in pseudo-code):

```c#
// in ValidateClientAuthentication
validateClient();
if (clientIsValid)
  skipContext(); // JavaScript client is not trusted anyway
else
  rejectContext();

// in ValidateTokenRequest
validateToken();
if (tokenIsValid)
  validateContext();
else
  rejectContext();
```

now, with ASOS 1.0.0-beta6-final, we should do:

```c#
// in ValidateTokenRequest
validateClient();
if (!clientIsValid)
{
  rejectContext();
  return; // skip the rest
}

validateToken();
if (tokenIsValid)
  validateContext();
else
  rejectContext();
```

Are those the right steps in order to process validation? Thanks a lot

**Comment by PinpointTownes** [comment]
Pretty much, yep :+1: 

Note that you can/should still call `context.Skipped()` from `ValidateTokenRequest` to skip token request validation for public clients that are not able to authenticate.

If you have a doubt, you can take a look at OpenIddict's implementation: https://github.com/openiddict/openiddict-core/blob/dev/src/OpenIddict.Core/Infrastructure/OpenIddictProvider.Exchange.cs. It's probably more complex than what you need as it supports both confidential and public clients, but you should get the idea.

**Comment by BrainCrumbz** [comment]
Thanks for reply, as usual! 

Now I'm not sure I got it correctly. Is `ValidateTokenRequest` going to be called multiple times, e.g. once for client validation, then for token validation? I mean, is this case similar to `HandleTokenRequest`, where I now have to check: *"Are you calling me for a IsPasswordGrantType request? Or are you calling me for a XxxType request?..."*.

If that's the case, then the correct pseudo code should be:

```c#
// in ValidateTokenRequest

if (thisIsAClientValidation)
{
  validateClient();
  if (clientIsValid)
  {
    skipContext(); // JavaScript client is not trusted anyway
  }
  {
    rejectContext();
  }
  return;
}

if (thisIsATokenRequestValidation)
{
  validateToken();
  if (tokenIsValid)
    validateContext();
  else
    rejectContext();
  }
  return;
}
// ...
```

**Comment by PinpointTownes** [comment]
> Now I'm not sure I got it correctly. Is ValidateTokenRequest going to be called multiple times, e.g. once for client validation, then for token validation?

No, `ValidateTokenRequest` only called once. At the minimum, you must validate the grant type and the client credentials.

When `HandleTokenRequest` is invoked, the grant type is necessarily a supported value since your custom check in `ValidateTokenRequest` is supposed to reject grants you don't want to support.

**Comment by BrainCrumbz** [comment]
So, in a call to `ValidateTokenRequest`, both the following can return true?

1. `context.Request.IsClientCredentialsGrantType()`, to check if this is a client credentials validation (i.e., the old *ValidateClientAuthentication*)
1. `context.Request.IsPasswordGrantType()`, to check if this is also a token request validation (i.e., the old *ValidateTokenRequest*)

**Comment by PinpointTownes** [comment]
Really long? Here's an example of a really long class: https://github.com/Microsoft/referencesource/blob/master/mscorlib/system/threading/Tasks/Task.cs :trollface: 

Actually, if you take a closer look, you'll see that it's mainly due to the code comments and log messages we have added. The validation logic itself is actually quite simple. 

Concerning the event, I think you're overthinking it: the entire event is all about token request validation, which includes grant type validation and client credentials. Don't mix up the client credentials grant (which is an OAuth2 grant type) with the fact you must validate client_id/client_secret with all the grant types.

**Comment by BrainCrumbz** [comment]
Re. Task.cs ... :open_mouth: :open_mouth: Re. OpenIddictProvider.Exchange.cs, jokes apart, it's not an issue, really. If one was really looking for some refactoring, it might be useful to split its methods in smaller chunks if in reality there are several phases, or steps, or branches in validation & handling, just our 2c :smiley_cat: 

Thanks for clarifying on token request validation (and its sub-parts) Vs client credential grant, that helps. Now we're getting result back from token request, but the `id_token` is missing in the response... will have to check what happens during ticket creation as before migration it was there.

**Comment by PinpointTownes** [comment]
> Now we're getting result back from token request, but the id_token is missing in the response... will have to check what happens during ticket creation as before migration it was there.

Make sure you're granting the `openid` scope when calling `SetScopes`.

**Comment by BrainCrumbz** [comment]
That was it. Before:

```c#
ticket.SetScopes(new[] {
    OpenIdConnectConstants.Scopes.Profile,
});
```

```c#
ticket.SetScopes(new[] {
    OpenIdConnectConstants.Scopes.OpenId,
    OpenIdConnectConstants.Scopes.Profile,
});
```

I guess in previous versions that scope was somehow set by default or something. Thanks for your help. 

Not sure if a new issue would be better, but now when on client we try to validate the return `access_token` (with angular2-jwt by auth0, as before) it fails saying *Error: JWT must have 3 parts*. `id_token` is still validated fine. Is there a new feature that makes `access_token` opaque to client or something similar?

**Comment by PinpointTownes** [comment]
https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/issues/185

**Comment by BrainCrumbz** [comment]
Working our way trough this: when building authentication ticket, passed ClaimsIdentity has 3 claims with following types (first 2 standard, 3rd one custom):

1. http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier
1. http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name
1. companyName

Then we set following scopes on ticket:

1. OpenIdConnectConstants.Scopes.OpenId,
1. OpenIdConnectConstants.Scopes.Profile,

In order to validate token when accessing protected resource, we're switching from former `UseJwtBearerAuthentication` to `UseOAuthValidation`. There we have the usual `ClaimsPrincipal` instance in `ControllerBase` that shows the following 3 claims instead:

1. http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier
1. scope: openid
1. scope: profile

It's like it loses some claims along the way. Are we missing some settings? Thank you

**Comment by PinpointTownes** [comment]
http://stackoverflow.com/questions/33797838/how-to-specify-the-destination-for-an-existing-claimsidentity

**Comment by BrainCrumbz** [comment]
Great. We were already setting destinations, but expressed with our own string constants:

* `"id_token"` for additional info related to user profile. Now changed to `OpenIdConnectConstants.Destinations.IdentityToken`
* `"token"` for additional info passed with resource access token. Now changed to `OpenIdConnectConstants.Destinations.AccessToken`

**Comment by BrainCrumbz** [comment]
Something more:

1. Is there an OAuthValidation equivalent of `RequireHttpsMetadata` from JwtBearerAuthentication?

1. Do we still need something like the `JwtBearerEvents.OnAuthenticationFailed()` workaround to fix MS `SecurityTokenExpiredException: IDX10223: Lifetime validation failed. The token is expired.` exception?

**Comment by PinpointTownes** [comment]
No (because there's no discovery process) and no.
