### ISSUE TITLE
Introspection multi-valued claims

### ISSUE THREAD

**Issue by brunombsilva** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#311]
When I use introspection with an user tha has multiple roles, I'm only getting one of them.

I took a look at AspNet.Security.OpenIdConnect.Server.InvokeIntrospectionEndpointAsync and it seems to be cause by 

```c#
foreach (var claim in notification.Claims) {
        // Ignore claims whose value is null.
        if (claim.Value == null) {
               continue;
       }

       // Note: make sure to use the indexer
       // syntax to avoid duplicate properties.
       response[claim.Key] = claim.Value;
}
```

only the last role claim is stored in the response.  Shouldn't an array o values been sent when a claim is multi-valued?

At least AspNet.Security.OAuth.Introspection.CreateTicketAsync seems to support JArray

**Comment by PinpointTownes** [comment]
This is by design. Having multiple items with the same name in a JSON object is generally considered as bad practice.

AFAIK, the introspection spec doesn't mention duplicate claims, but here's what the JWT spec says about them:

> The JWT Claims Set represents a JSON object whose members are the claims conveyed by the JWT. The Claim Names within a JWT Claims Set MUST be unique; JWT parsers MUST either reject JWTs with duplicate Claim Names or use a JSON parser that returns only the lexically last duplicate member name, as specified in Section 15.12 ("The JSON Object") of ECMAScript 5.1 [ECMAScript].

For the introspection endpoint, I've opted for the second approach: returning only the last occurrence. If you want to use an array, it's up to you to create it:

```csharp
context.Claims["name"] = JArray.FromObject(array);
```

**Comment by PinpointTownes** [comment]
> Shouldn't an array o values been sent when a claim is multi-valued?

Actually, it's probably not a bad idea for the claims we automatically add in the `Claims` collection before invoking the `HandleIntrospectionRequest` event.

I'll try to implement that in the next release.

**Comment by brunombsilva** [comment]
I wasn't suggesting an invalida json object with duplicated attributes.

I was reading the [OAuth 2.0 Token Introspection RFC](https://tools.ietf.org/html/rfc7662#section-2.2)

As far as JWT is concerned, it seems that the claim could be an array - [Validating a JWT](https://self-issued.info/docs/draft-ietf-oauth-json-web-token.html#Validating).

Since when I get roles from the authentication token, the roles claim comes as an array, it makes sense that it should be the case in introspection also.

If I can add multiple claims of the same type with different values for a given user, that data should flow to the client and resource servers.

**Comment by PinpointTownes** [comment]
> Since when I get roles from the authentication token, the roles claim comes as an array, it makes sense that it should be the case in introspection also.

Only because IdentityModel does some voodoo magic :smile: 

As I said in the previous comment, I'll consider adding a special case when there are multiple claims with the same name before copying them to `HandleTokenRequestContext.Claims`.
