### ISSUE TITLE
Consider disabling all the OIDC endpoints by default to reduce the attack surface

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#312]
Unlike `OAuthAuthorizationServerMiddleware`, ASOS' endpoints are all enabled by default.

To reduce the attack surface of ASOS deployments, I'm considering removing all the default endpoint paths in beta7 (except the configuration and cryptography endpoints, that are required for OIDC discovery to work properly).

I'd love to hear your thoughts about this change.

**Comment by MartinMason** [comment]
I'm all for it. In my constant head banging trying to get Aurelia and OpenIddict to work together, ended up coming to the point where the only endpoints needed was the authorization endpoint and userinfo endpoint. If resource owner password credentials grant was the only flow needed, it would have been only the token endpoint and userinfo endpoints. Are you thinking that to enable endpoints, you'd explicitly need to call .EnableAuthorizationEndpoint("~/connect/authorize") in the ConfigureServices method of StartUp. Only reservation would be the number of questions you'd get on the gitter chat.

**Comment by PinpointTownes** [comment]
> Only reservation would be the number of questions you'd get on the gitter chat.

Very good point :+1: 

My OpenIddict PR includes a few checks to ensure that at least one flow is registered (which should warn existing users about this new requirement) and that the final configuration is coherent.

![image](https://cloud.githubusercontent.com/assets/6998306/16710579/cdcb49fc-4633-11e6-8a47-a3ac234b6192.png)

So if you allow a flow to be used without enabling the corresponding endpoints, an exception is thrown during startup (e.g for the password flow, the token endpoint must be enabled ; for the authorization code flow, both the authorization and the token endpoints must be enabled).

![image](https://cloud.githubusercontent.com/assets/6998306/16710593/365dce7c-4634-11e6-9a6c-5242c02f0449.png)

![image](https://cloud.githubusercontent.com/assets/6998306/16710538/5b6fb52e-4632-11e6-84c0-ac9af33fc7e8.png)

I hope it will be clear enough.
