### ISSUE TITLE
Why client_id must not contain spaces?

### ISSUE THREAD

**Issue by xperiandri** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#315]
Is there a specification requirement that `client_id` must not contain spaces?
https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/blob/dev/src/AspNet.Security.OpenIdConnect.Extensions/OpenIdConnectExtensions.cs#L1133
Is this a purpose of this check existence?

**Comment by PinpointTownes** [comment]
> Is there a specification requirement that client_id must not contain spaces?

No. Spaces are forbidden because multiple values are (currently) stored as space-separated values.

Do you have a concrete scenario where supporting spaces would be important for you?

**Comment by xperiandri** [comment]
I've done this
``` C#
                context.Applications.Add(new OpenIddictApplication<Guid>
                {
                    ClientId = "Android test",
                });
                context.Applications.Add(new OpenIddictApplication<Guid>
                {
                    ClientId = "plaAndroid",
                });
                context.Applications.Add(new OpenIddictApplication<Guid>
                {
                    ClientId = "Windows test",
                });
```

And we could not figure out what is wrong for a week!

The exception is absolutely not descriptive and when it bubbles up you have no idea what is wrong.
Why it is necessary to store this values separated by spaces?

**Comment by PinpointTownes** [comment]
> Why it is necessary to store this values separated by spaces?

It's not. But it's an efficient serialization and until now, nobody has ever complained about this "limitation" (because well, using spaces in client_id is totally uncommon). If we wanted to support spaces, I guess we'd have to switch to a more complex serialization scheme, like JSON or XML.

**Comment by xperiandri** [comment]
We must either implement a check in https://github.com/openiddict/openiddict-core/blob/dev/src/OpenIddict.EntityFramework/Models/OpenIddictApplication.cs#L35 and rethrow a more descriptive exception up on stack.
Or eliminate this limitation.

To avoid issues.
I would prefer not to add limitations over the standard.

**Comment by jayrulez** [comment]
+1 for removing the limitation.

**Comment by PinpointTownes** [comment]
Alright. I'll consider fixing that in the next milestone :smile:
