### ISSUE TITLE
Authenticate both with cookie and token with username/password

### ISSUE THREAD

**Issue by tim-cools** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#331]
Hi,  

I try to accomplish following scenario:

I want to use both cookie and token authentication. I want the cookie used for the server page rendering and the token for the client api calls.
- A user logs in in the client application with username and password
- The username / password is validated by the token endpoint
  > The token is returned
  > A authentication cookie is set (context.HttpContext.Authentication.SignInAsync)

I tried calling context.HttpContext.Authentication.SignInAsync in ValidateTokenRequest and HandleTokenRequest of the provider. But in both cases I get: "Headers are read-only, response has already started." in AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerHandler.<SendPayloadAsync>d__9.MoveNext()

Two questions:
- It this possible to execute both the token handler and the SignIn in a single request?
- Is what I try to do a valid procedure?

Thanks in advance!

Tim

**Comment by PinpointTownes** [comment]
Hey,

> It this possible to execute both the token handler and the SignIn in a single request?

Assuming you call SignInAsync with an authentication scheme corresponding to a cookie middleware, it should be - in theory - possible (FYI, major improvements have been introduced in beta7, as the authorization response/token response logics have been unified).

> Is what I try to do a valid procedure?

Not really. Actually, it's even particularly risky as the token endpoint is not - per spec - guarded against XSRF attacks: returning a cookie from this endpoint will result in a session fixation attack being possible (which is terrible).

**Comment by tim-cools** [comment]
Thanks, makes sense...

What do you think about creating a second endpoint (POST) authenticated by the 'token' and with an additional Csrf-Token that returns the cookie?

**Comment by PinpointTownes** [comment]
Why not. But in this case, why not just using cookies everywhere? The whole point of not using is to avoid XSRF attacks: if you reintroduce them, you'll have to protect all your endpoints from XSRF, even if they use dual authentication (cookies/tokens).

**Comment by tim-cools** [comment]
Good question.

A little more info: I'm creating a React app with both client and server side rendering. 

I split  up my authentication like this:
- Web pages: cookie authentication
- Api: token authentication

The problem is that at the moment of server side rendering I don't know if a user is authenticated or 
not because their is no cookie available.

I do not to support cookies in my API, only tokens authentication. But I need to have the cookies to render my pages (GET only) with the authenticated user.

As far as my understanding I'm safe for CSRF because the cookies are only used for GETs. But you can correct me if I'm wrong?

**Comment by github-polymer-user** [comment]
"But I need to have the cookies to render my pages (GET only) with the authenticated user."

I think you app should be able to authenticate user with cookies disabled

**Comment by tim-cools** [comment]
@github-polymer-user Yes, it is possible, but it moves the authentication to the client instead of on the server. And I want to know whether a user is authenticated during server side-rendering of GET requests from the browser...
