### ISSUE TITLE
2FA support?

### ISSUE THREAD

**Issue by norcis** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#335]
Hello,

I'm creating rest api and first party native mobile app which will consume it. To authorise API access and authenticate users I want to implement OpenId Connect with 2FA.

It would look like this:

1) in the app, user enters his username/password or use Facebook/Google etc.
2) if it's validated, server send SMS with shared secret to customer associated phone number.
3) clients enters PIN code received by SMS in the app. This pin could be passed to server to get token or maybe it should be stored in app and used for signing future requests. I'm not sure which flow should be used in such case.

Any recommendations how to do that?

**Comment by PinpointTownes** [comment]
Duplicate of https://github.com/openiddict/openiddict-core/issues/222.
