### ISSUE TITLE
Invalid authentication should use 401, not 400 when using grant_type=password

### ISSUE THREAD

**Issue by dozer75** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#336]
Currently, whenever you use the `context.Reject()` method, the response returns HTTP status code 400 (bad request) no matter what the exact issue is.

I think that the status code should be more specific dependent on the type of error. E.g. whenever using the constant OpenIdConnectConstants.Errors.AccessDenied it should return 401 instead of 400.

**Comment by PinpointTownes** [comment]
That's deliberate: https://github.com/openiddict/openiddict-core/issues/221#issuecomment-245892959
