### ISSUE TITLE
In need of a Mvc 5 WebAPI client example

### ISSUE THREAD

**Issue by jhermsen** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#338]
Can anyone please direct me to an example using an Mvc 5 client to connect to an OpenIdConnect server?

I have been playing arround with the settings in Mvc5, but can't get it to work.

**Comment by PinpointTownes** [comment]
There's no MVC 5 sample, but you can take a look at the Nancy sample, that uses the OWIN/Katana OpenID Connect client middleware: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/blob/dev/samples/Nancy/Nancy.Client/Startup.cs#L28-L103
