### ISSUE TITLE
Tentative release date for ASOS - do we have one?

### ISSUE THREAD

**Issue by reazhaq** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#339]
Understand, current nuget pkg is beta6-final.  Would like to know if dates for release candidate and final release have been targeted or not, if so when.  Thanks in advance.

**Comment by PinpointTownes** [comment]
> Tentative release date for ASOS - do we have one?

We do :smile: 

ASOS beta7 will be likely released in ~2 weeks, as soon as I'm done with the unit tests (at the time of writing, we already have ~500 tests). It should be the latest beta as I'm now quite happy with the existing API.

I expect a first RC version to be released by the end of October and the RTM version in November (or December if we need a second RC).

**Comment by reazhaq** [comment]
thanks a lot

**Comment by PinpointTownes** [comment]
I had to delay the release of the beta7-final packages to match ASP.NET Core 1.1.0's release date. Unfortunately, there's a bunch of annoying bugs in 1.1.0, so all the aspnet-contrib packages still target 1.0.0.

You can find the beta7-final packages on the MyGet repo. They'll be uploaded to NuGet.org in the next few days.
