### ISSUE TITLE
Is there any way to get the domain from the various contexts?

### ISSUE THREAD

**Issue by atrauzzi** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#340]
As I'm implementing my authorization provider I receive the various contexts.  But I was wondering, is there any way to infer the domain used for the current request?

I'm looking at some multi-tenanting scenarios that could benefit from it.

**Comment by PinpointTownes** [comment]
Something like `context.HttpContext.Request.Host`?

**Comment by atrauzzi** [comment]
Wonderful!  Thanks so much :)
