### ISSUE TITLE
An appropriate error message must be returned when incorrect client credentials grant request

### ISSUE THREAD

**Issue by xperiandri** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#347]
When __Client credentials grant__ request comes to an token endpoint in form of query parameters instead of `x-www-form-urlencoded` an appropriate error message must be returned

**Comment by PinpointTownes** [comment]
1. "client credentials grant" requests are necessarily sent to the token endpoint, not the authorization endpoint.

2. ASOS already does the right thing by returning an error when the required `grant_type` parameter is missing.

3. [custom query parameters are allowed by the specification](https://tools.ietf.org/html/rfc6749#section-3.2) so we can't just check whether there's a query string to return a message error as you suggest.

**Comment by xperiandri** [comment]
1. I was wrong
3. But it would be stupid to send grant_type=client_credentials in query string in addition to a form, wouldn't it?

**Comment by PinpointTownes** [comment]
It would, tho' there's nothing that prevents it according to the spec.

Feel free to take a look at what other popular OAuth2/OIDC implementations do (e.g IdSrv, OpenAM, MITREid Connect). If they have the kind of check you suggest, I'll consider adding one to ASOS.

**Comment by xperiandri** [comment]
They does not.
I would include that into a specs.
Making a safety fence around the specs is a good practice according to [Pirkei Avot, Chapter 1, Paragraph 1](http://www.chabad.org/library/article_cdo/aid/2165/jewish/Chapter-One.htm)
My consideration here is that how many people know specs and security practices well to not make the same mistake.

**Comment by PinpointTownes** [comment]
> Making a safety fence around the specs is a good practice according to Pirkei Avot, Chapter 1, Paragraph 1

TBH, I'm not sure to know what I'm supposed to say, right now :smile:
