### ISSUE TITLE
Introspection problem

### ISSUE THREAD

**Issue by Crazyht** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#351]
Hi, 

I have multiple claim with same type (roles) in my ticket, when I use introspection, my identity contains only last claim value. 

~~In same time, if HandleIntrospection change claim list, this change are not propagated to identity ticket.~~

**Comment by Crazyht** [comment]
I see the bug was already fixed in dev branch :) 
You have plan to release beta 7 ?

**Comment by PinpointTownes** [comment]
> I see the bug was already fixed in dev branch :) 

Yep: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/issues/311.

> You have plan to release beta 7 ?

Sure :smile:

**Comment by Crazyht** [comment]
lol

**Comment by PinpointTownes** [comment]
FYI: you can find the beta7-final packages on the MyGet repo. They'll be uploaded to NuGet.org in the next few days.
