### ISSUE TITLE
Add unit tests for OpenIdConnectClient

### ISSUE THREAD

**Issue by kevinchalet** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#360]
The `AspNet.Security.OpenIdConnect.Client` package won't be published to NuGet.org as part of the beta7 release as it still needs some love, including a few unit tests. Let's do that for the next milestone.

**Comment by PinpointTownes** [comment]
Since there's no plan to (publicly) release `AspNet.Security.OpenIdConnect.Client`, this work item can wait.
