### ISSUE TITLE
Consent page skipping

### ISSUE THREAD

**Issue by georgeonofrei** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#361]
Hello,

I am using ASOS to create an id server and i have a question regarding the consent page. (obvious, right?)

I have created a consent page for the user. I would like to skip the consent page entirely when user already consented. 
What is your opinion about generating an access code using the GET request from '\~/connect/authorize' instead of showing a sort of "already consented" page with only one button 'OK' that does a post to '\~/connect/authorize/accept'.

Queote from the OpenId Connect of interest:

> 3.1.2.4.  Authorization Server Obtains End-User Consent/Authorization

>Once the End-User is authenticated, the Authorization Server MUST obtain an authorization decision before releasing information to the Relying Party. When permitted by the request parameters used, this MAY be done through an interactive dialogue with the End-User that makes it clear what is being consented to or by establishing consent via conditions for processing the request or other means (for example, via previous administrative consent). Sections 2 and 5.3 describe information release mechanisms.

Thanks in advance!
Your works is great and I have been reading your blog posts time and time again to get a deeper understanding of ASOS and OpenId Connect in general.

**Comment by PinpointTownes** [comment]
> Your works is great and I have been reading your blog posts time and time again to get a deeper understanding of ASOS and OpenId Connect in general.

Thanks for the kind words :smile: 

> What is your opinion about generating an access code using the GET request from '~/connect/authorize' instead of showing a sort of "already consented" page with only one button 'OK' that does a post to '~/connect/authorize/accept'.

That's totally fine. There are actually many implementations that prefer displaying no UI at all for trusted clients: in this case, you can directly handle the authorization request in the authorization provider (in `HandleAuthorizationRequest`).
