### ISSUE TITLE
Client Credentials flow

### ISSUE THREAD

**Issue by georgeonofrei** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#362]
Hello,

I have the following situation:

![untitled diagram](https://cloud.githubusercontent.com/assets/15815781/21184100/998fd200-c213-11e6-8c9e-ebb9466fae87.png)

"A Spa" uses implicit flow to get a token to use with "A Backend" and "A Backend" uses client credentials to get a token to use with "B Api".
Question: when using client credentials, "A Backend" can request a couple of scopes - my problem is how would be the best (standard compliant) way to restrict the scopes that can be requested? I am thinking here about a situation in which "B Api" contains data from multiple "X Backend"s so this "B Backend" needs to get the right scopes. I guess the question boils down to how can I register some scopes available for "B Backend".

Practical case: "A Spa" uses a different id identity provider than "B Api" and "A Backend" acts as a middle ground between the two. A group of users using "A Spa" (and not registered in id identity) want to use the spa to gain access to "B Api". From "B Api"s point of view, all requests come from "A Backend", but I somehow need to establish some scopes that are available only for "A Backend" (like: a_backend_scope1, a_backend_scope2).

Considerantions: Although the example uses the same id identity, the implementation is done so that "A Spa" uses another. Implicit flow is used because it is specifically designed for JS (public) clients.

Thank you!
George

**Comment by PinpointTownes** [comment]
This sounds like a very generic/general question about OAuth2 (read not really ASOS-specific). Maybe it would be better to post it on StackOverflow?

**Comment by georgeonofrei** [comment]
Thanks, if you have an opinion about it I would like to hear it. 
George
