### ISSUE TITLE
Self issued access token

### ISSUE THREAD

**Issue by longday24** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#363]
What is the best way for OpenIdConnect Server to generate an access token internally?

If the server requires access to a secured resource, how can the server generate an access token without making a "client_credentials" grant type http call?

Example resource servers could be logging or central config resources.

**Comment by PinpointTownes** [comment]
I'd recommend reading http://stackoverflow.com/a/41192112/542757.
