### ISSUE TITLE
(Question) External providers and ASOS

### ISSUE THREAD

**Issue by baseless** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#364]
Hi!
Am learning asos and using implicit password flow atm (it works very well). But i was a bit uncertain in regards to providing tokens based om 3rd party authorization (like google, facebook and so forth). As i understand, cookieauthentication is utilized in conjunction with the standard libraries but it would be nice if there were a complete sample of this flow, showing preferred practises. Is there such a project floating somewhere (couldnt find it in the samples, but i perhaps missed something).

**Comment by PinpointTownes** [comment]
Hey,

The MVC sample uses external authentication: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Samples/blob/master/samples/Mvc/Mvc.Server/Startup.cs#L57-L77

**Comment by baseless** [comment]
Ah sorry, i appear to be blind ;). Thx for the input!
