### ISSUE TITLE
Is it possible to serve multiple UserInfo endpoints?

### ISSUE THREAD

**Issue by xperiandri** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#366]
Like if i have a few types of users and each has its own set of properties.
So that I can set multiple user info URLs.

**Comment by PinpointTownes** [comment]
It's a question you already asked a few months ago and _the answer is still exactly the same: **no, it's not possible** (at least if you want to be spec-compliant, as only one userinfo endpoint can be exposed by the discovery document).

Both ASOS and OpenIddict allow you to dynamically choose the claims you want to return from the userinfo endpoint. There's really no practical reason to want multiple userinfo endpoints.

**Comment by xperiandri** [comment]
That question was different. That time I asked about auth API versioning.
Thanks for the answer.

**Comment by PinpointTownes** [comment]
![image](https://cloud.githubusercontent.com/assets/6998306/21735949/93f00d08-d46d-11e6-96ef-8b444f930bbe.png)

:trollface:
