### ISSUE TITLE
OpenIdConnectMessage.GetParameter<T> can throw FormatException

### ISSUE THREAD

**Issue by nphmuller** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#367]
OpenIdConnect.Server 1.0.0.-beta7-final.

I've overriden one of the `HandleXRequest()` methods in my own OpenIdConnectServerProvider implementation. In this method I try to retrieve my custom parameter with `context.Request.GetParameter<bool>("my_parameter")`. When the parameter in the request is no valid boolean (for example, if it's a string), a FormatException is thrown by the underlying `JToken.ToObject()` method.

Normally I would expect that I implemented the method incorrectly, but I can see that `OpenIdConnectMessage.GetParameter<T>` does some error handling and should return default(T).

Example:
Call the revocation endpoint with 'myParam' as a string to let it throw the exception.
``` c#
public class MyAuthProvider : AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerProvider
{
     public override async Task HandleRevocationRequest(HandleRevocationRequestContext context)
     {
         var myParam = context.Request.GetParameter<bool>("myParam");
     }
}
```

**Comment by PinpointTownes** [comment]
That's actually the expected behavior, the `default` code path is just an optimization for the most common case (when asking for a string).

I wish JSON.NET offered a way to safely convert a type to a specific type without ever throwing an exception, but unfortunately, there's no such thing.

Would you prefer if the `FormatException` was silently caught?

**Comment by nphmuller** [comment]
Not sure. If it was silently caught I'd prefer if if the method returned a nullable bool instead of a boolean. Or maybe the Try pattern (like with int.TryParse and bool.TryParse). Both solutions might make it all a bit too complex though... 

But if a FormatException might be thrown, please document it in the xml docs. That would already solve the confusion I had.

The easiest (and least exception prone) way to use GetParameter<T> currently seems to always use string as T and manually try to parse it to a boolean. Would you agree?

**Comment by georgeonofrei** [comment]
The TryX patterns sounds like a better idea than the nullable stuff. The problem with nullable is that null is actually a valid value, so you cannot reply on returning null value to know whether parsing was successful or not. Of course TryX has that horrible out parameter 😄 .

Some other thing i've been using every now and then was returning a custom object (similar to Tuple<T, bool>), T being the parsed value or default and the boolean the successful or not. I'm not saying to use Tuple, but use an immutable object with 2 properties: Value, Successful.

**Comment by PinpointTownes** [comment]
@nphmuller @georgeonofrei thanks for the input :+1: 

My proposal:

```csharp
// Introduce a new exception type, that could be used by ASOS
// to return error pages for exceptional errors like malformed input.
public class OpenIdConnectException : Exception {
    public OpenIdConnectException([NotNull] string code, [NotNull] string description);
}
```

```csharp
public abstract class OpenIdConnectMessage {
    // Update this method to catch formatting-related exceptions
    // and throw an OpenIdConnectException instead.
    public virtual T GetParameter<T>([NotNull] string name);

    // Introduce a new TryGet* method catching all the exceptions thrown by JSON.NET
    // and returning true or false to indicate whether the parameter can be retrieved.
    public virtual bool TryGetParameter<T>([NotNull] string name, [CanBeNull] out T value);
```

**Comment by PinpointTownes** [comment]
> The easiest (and least exception prone) way to use GetParameter currently seems to always use string as T and manually try to parse it to a boolean. Would you agree?

When the request is an authorization or a token request, using `string` and manually parsing the result to the type you want shouldn't cause any exception, as the parameters are always represented as strings by ASP.NET Core.

Unfortunately, this statement won't be always true when we start implementing dynreg, as dynamic registration requests are represented as JSON, so we have no guarantee that nodes can be cast to strings.

**Comment by PinpointTownes** [comment]
Scratch my initial proposal, I don't like it :smile: 

The current plan is to introduce a new `struct` named `OpenIdConnectParameter` that would replace `JToken` as the return type of `GetParameter` and would allow exceptionless nodes traversal. The generic `GetParameter` method would be removed, and you'd instead be encouraged to implicit conversions.

```
var payload = @"
{
    ""redirect_uris"": [""https://client.example.org/callback"", ""https://client.example.org/callback2""],
    ""client_name"": ""My Example Client"",
    ""token_endpoint_auth_method"": ""client_secret_basic"",
    ""policy_uri"": ""https://client.example.org/policy.html"",
    ""jwks"": {""keys"": [{
        ""e"": ""AQAB"",
        ""n"": ""nj3YJwsLUFl9BmpAbkOswCNVx17Eh9wMO-_AReZwBqfaWFcfG"",
        ""kty"": ""RSA""
    }]},
    ""example_extension_parameter"": ""example_value""
}";

var request = new OpenIdConnectRequest(JObject.Parse(payload));

var value = (long?) request["missing_node"]["missing_long_parameter"];
if (value == null) {
    // The parameter or the entire node was missing or invalid.
}

// An exception will be thrown if the parameter or the node was missing or invalid.
var integer = (long) request["missing_node"]["missing_long_parameter"];
```

This is something I'd like to include in RC1. I'll keep you informed.

**Comment by georgeonofrei** [comment]
Hi,

The idea sounds promising. The only uncertainty for me is that I'm wondering how the indexed accessing is going to work. If you are using a struct, it will always be an isntance,. so there's no NullRef exception possible, which is nice. Much better than the DLR version which throws exceptions 👎 .

OpenIdParameter will have all the implicit conversions, in which case what would happen if you convert it to long? How is the developer announced that actually the conversion failed? Or do you expect to have something like:

```
if( request["missing_node"]["missing_long_parameter"].IsLong()){
   var integer = (long) request["missing_node"]["missing_long_parameter"];
}
```

George

**Comment by PinpointTownes** [comment]
> OpenIdParameter will have all the implicit conversions, in which case what would happen if you convert it to long? How is the developer announced that actually the conversion failed?

It will depend on whether `OpenIdConnectMessage.GetParameter` (and the indexer) returns `OpenIdConnectParameter` or `OpenIdConnectParameter?`

With `OpenIdConnectParameter`:

```
// Note: parameter is an OpenIdConnectParameter instance.
var parameter = request["complex_node"]["long_parameter"];
if (parameter.HasValue) {
    // If the integer variable is null, this means the conversion failed.
    var integer = (long?) parameter;
}
```

With `OpenIdConnectParameter?`

```
// Note: parameter is an OpenIdConnectParameter? instance.
var parameter = request["complex_node"]?["long_parameter"];
if (parameter != null) {
    // If the integer variable is null, this means the conversion failed.
    var integer = (long?) parameter;
}
```

In both cases, **the syntax guarantees exceptionless nodes traversal** (in the second case, writing `request["complex_node"]["long_parameter"]` is illegal and results in an compilation error, which makes ultra clear values can be null at any moment)

I'm also considering throwing an `InvalidOperationException` if the requested type is a value type AND not nullable:

```
// This line will throw an exception is the node is missing or if the parameter can't be converted.
var parameter = (long) request["complex_node"]["long_parameter"];
```

**Comment by PinpointTownes** [comment]
Note: in practice, I'd expect most people to treat invalid properties like missing properties:

```csharp
var parameter = (long?) request["integer_parameter"];
if (parameter == null) {
    return BadRequest(new OpenIdConnectResponse {
        Error = OpenIdConnectConstants.Errors.InvalidRequest,
        ErrorDescription = "The mandatory 'integer_parameter' is missing or invalid."
    });
}
```

**Comment by nphmuller** [comment]
> ``` c#
> var parameter = (long?) request["integer_parameter"];
> ```

I really like this syntax. Simple and clear!

**Comment by PinpointTownes** [comment]
> I really like this syntax. Simple and clear!

Note that this syntax is not exactly new, as you can already use it with the beta7 bits (the indexer currently returns a `JToken` that can be explicitly cast to a bunch of primitive types).

**Comment by georgeonofrei** [comment]
To avoid the cast and make it a bit fluent also, what do you think about providing extension methods like: 

`var parameter = request["integer_parameter"].AsLongNullable();`
or
`var parameter = request["integer_parameter"].As.LongNullable();`
or
`var parameter = request["integer_parameter"].As<long?>();`

**Comment by PinpointTownes** [comment]
> To avoid the cast and make it a bit fluent also

Technically, it's not exactly a cast, but a conversion (using an explicit static operator).

Note that the third syntax pretty much corresponds to what we currently have in beta7 (`request["integer_parameter"].ToObject<long?>()`).

The first syntax looks good. Let's wait and see if there's enough demand to introduce it :smile:

**Comment by PinpointTownes** [comment]
Done: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/pull/375/commits/487931f270933c97e0633d01ee7b612f0f70472e.
