### ISSUE TITLE
Return the same refresh token using the refresh_token grant

### ISSUE THREAD

**Issue by georgeonofrei** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#372]
Hi,

Is it possible for ASOS to return a certain refresh token (namely the current one) instead of generating another one?

Situation: Atm I have to revoke the current refresh token and generate another one that the client app can use. I would like to just return the current refresh token and prevent another one from being generated.

Thanks,
George

**Comment by PinpointTownes** [comment]
Hey,

> Is it possible for ASOS to return a certain refresh token (namely the current one) instead of generating another one?

Yes, it is. Set `UseSlidingExpiration` to `false` in the ASOS options and it will stop issuing new refresh tokens on subsequent requests.

**Comment by georgeonofrei** [comment]
Thanks,

Noticed it while reviewing the OpenIddict solution but thought it was applicable only to the server (OpenIddict). 
Took look and found it under UseOpenIdServer options (with extensive documentation 👍 ) .

Great work!
Thanks,
George

**Comment by PinpointTownes** [comment]
> Great work!

Glad you like it :smile:

**Comment by georgeonofrei** [comment]
*Like it a lot that is 😀
