### ISSUE TITLE
What's the difference between access_token and id_token?

### ISSUE THREAD

**Issue by Jamesxql** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#381]
What's the functions of a access_token in the openid connect authentication flow?

**Comment by PinpointTownes** [comment]
http://stackoverflow.com/a/19443840/542757

**Comment by Jamesxql** [comment]
So, according to the document I see it, I think the access_token is to ensure the token response is compliant with the OAuth 2.0 spec. For basic OpenID authentication requests where only an ID token is requested this access_token is nominal and may be safely ignored. 

And, the access_token can be used to request the [UserInfo endpoint](https://openid.net/specs/openid-connect-core-1_0.html#UserInfo). For that a valid access token is required.

The ID token is used to authenticate the end-user by the resource server, the access token is useless to the resource server.

Am I right ?
