### ISSUE TITLE
ValidateAuthorizationRequestContext.Validate(expected_redirect_uri) should use Reject() instead of throwing exception

### ISSUE THREAD

**Issue by ntonyho** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#409]
the way i see it after looking at the code (and ignore code comment)
.Validate("http://foobar") ensures the redirect_uri must be http://foobar ... or at least that's the intend of the guy calling .Validate("http://foobar")
IMHO, translating failure to Reject("invalid_client", "redirect_uri doesn't match http://foobar") seems to be more appropriate than throwing exception

currently, one MUST do the following
try
{
context.Validate("http://foobar")
}
catch (Exception e)
{
context.Reject("invalid_client", "invalid redirect_uri")
}

it will be nice if one line "context.Validate("http://foobar")" is enough

**Comment by PinpointTownes** [comment]
I've thought a bit about this change, and while the new behavior deliberately differs from what `OAuthAuthorizationServerMiddleware` used to do, I think it's better than the old one, as it makes clearer the fact that `context.Validate(...)` is actually just a way to mark the context as validated and is not responsible of silently validating the `redirect_uri` for you.

**Comment by ntonyho** [comment]
You have a function call validate that takes a parameter of redirect uri. It's hard for others not to think this is doing validation
My alternate suggestion is to provide a way to set the redirect uri (either a new function or a setter which would throw exception if the original value isn't null)

This way Validate would have no overload and would have the same meaning in every notification event

Sent from my iPhone

On 23 Mar 2017, at 10:36 PM, Kévin Chalet <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #409<https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/issues/409>.
