### ISSUE TITLE
Return more informations to the client

### ISSUE THREAD

**Issue by MoiraG** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#424]
Hello,

is it possible to add additional properties to the response after the token generation?
For example like this: https://stackoverflow.com/questions/26357054/return-more-info-to-the-client-using-oauth-bearer-tokens-generation-and-owin-in 

Thank you!
Best regards

**Comment by PinpointTownes** [comment]
Hey.

Yep, it's possible: https://stackoverflow.com/questions/34074787/overriding-tokenendpoint-in-aspnet-security-openidconnect-server.

**Comment by MoiraG** [comment]
Thank you! I have no idea why I didn't find the solution on stackoverflow.

**Comment by PinpointTownes** [comment]
My pleasure 😄
