### ISSUE TITLE
removing returnuri from OpenIdConnectOptions cause some problems

### ISSUE THREAD

**Issue by farshid3003** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#439]
when you code works behind an proxy server like nginx with http protocol and from out you have https (ssl) now when you go to authority server your client redirect_uri is not valid as it will post with http not https.
it is now automatically set my current uri which is not correct for authentication

let explain more 
I have a client application which is running on linux on 5000 port : http://127.0.0.1:5000
and I have an nginx which forward https://mydomain.com to http://localhost:5000
I have an Identityserver (Identityserver4) and I configured my client in this server
on authentication time I got this error:unauthorized_client
in logs I saw that in the request return_url set to http://mydomain.com and this url is not valid in identityserver

**Comment by PinpointTownes** [comment]
Wrong place, I'm afraid.

This repository is dedicated to the OpenID Connect server middleware (that you're obviously not using).
