### ISSUE TITLE
Options gone from MatchEndpointContext

### ISSUE THREAD

**Issue by ErlendSB** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#440]
In:  
`public override Task MatchEndpoint(MatchEndpointContext context)`  
I used to have access to the OpenIdConnectServerOptions via an Options property on the context.  
Can this be added back?

**Comment by PinpointTownes** [comment]
Thanks for reporting this bug :+1: 

This is indeed an unwanted change. It will be fixed in the next servicing release (1.0.1).

**Comment by PinpointTownes** [comment]
For the record, this bug only impacts the ASP.NET Core version.

**Comment by PinpointTownes** [comment]
Fixed: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/f17d9a4d0f747dd65de83a4ff898e68b37c9d34d.

Note: the `1.0.1` package can be found on the MyGet feed. It will be pushed to NuGet.org in the next few days.
