### ISSUE TITLE
Should grant_type=client_credentials have to override HandleTokenRequest method if not skipped in ValidateTokenRequest?

### ISSUE THREAD

**Issue by ChRonX13** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#441]
Hi,

I'm currently attempting to implement a client_credential flow. Having read through http://kevinchalet.com/2016/07/13/creating-your-own-openid-connect-server-with-asos-choosing-the-right-flows/ and following the examples, it goes on to say that when the client can be trusted to keep the clientid/client secret, we should enforce and validate the context.

However, having gone through the base HandleTokenRequest code, it appears that when the context has not been skipped, it is expecting that an AuthenticationTicket has been created.

```
            // Ensure an authentication ticket has been provided or return
            // an error code indicating that the request was rejected.
            if (ticket == null)
            {
                Logger.LogError("The token request was rejected because it was not handled by the user code.");

                return await SendTokenResponseAsync(new OpenIdConnectResponse
                {
                    Error = OpenIdConnectConstants.Errors.InvalidRequest,
                    ErrorDescription = "The token request was rejected by the authorization server."
                });
            }
```

Is it expected that even if we are not doing a ROPC flow and doing a server side application flow, that we override and create a new AuthenticationTicket, which claims associated with the given service account details? 

Thanks in advance!

**Comment by PinpointTownes** [comment]
Hi,

> Is it expected that even if we are not doing a ROPC flow and doing a server side application flow, that we override and create a new AuthenticationTicket, which claims associated with the given service account details?

Yep. If you don't provide an authentication ticket, ASOS has no way to return a valid token response and returns a default error, assuming your code refused to handle the request.

**Comment by ChRonX13** [comment]
many thanks for the prompt clarification!
