### ISSUE TITLE
Authorization service does not use OpenIDConnect middleware

### ISSUE THREAD

**Issue by st2forget** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#442]
Here is my configuration:   

        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            loggerFactory.AddDebug();
            
            app.UseIdentity();

            app.UseOpenIdConnectServer(options =>
            {
                options.AllowInsecureHttp = true;
                options.TokenEndpointPath = "/token";
                options.Provider = app.ApplicationServices.GetService<SocosyOpenIdConnectProvider>();
            });

            app.UseMvc();
            
            // Hangfire
            app.UseHangfireServer();
        } 

        public void ConfigureServices(IServiceCollection services)
        {
            // needed to load configuration from appsettings.json
            services.AddOptions();

            services.AddAuthentication();

            // Add framework services.
            services.AddMvc();
        }

Here is actual result:   
```   
            Request starting HTTP/1.1 POST http://localhost:5000/api/photos  0
             Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
             Authorization failed for user: (null).
             Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
             Authorization failed for the request at filter                         'Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter'.
             Microsoft.AspNetCore.Mvc.ChallengeResult[1]
             Executing ChallengeResult with authentication schemes ().
             Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationMiddleware[12]
             AuthenticationScheme: Cookies was challenged.
             Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
             Executed action Socosy.Api.Controllers.PhotosController.Post (Socosy.Api) in 3.6464ms
             Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
             Request finished in 6.6909ms 302
             Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
             Request starting HTTP/1.1 GET http://localhost:5000/Account/Login?ReturnUrl=%2Fapi%2Fphotos
             Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
             Request finished in 2.6041ms 404
```   

It appears that the Authorization Service does not call the right AuthorizeFilter but used CookieAuthenticationMiddleware. Could anyone check this out?

Here is version of .net core:    
```
Microsoft .NET Core Shared Framework Host

  Version  : 1.1.0
  Build    : 928f77c4bc3f49d892459992fb6e1d5542cb5e86
```

**Comment by PinpointTownes** [comment]
I don't understand your question, sorry. What are you trying to do?

**Comment by st2forget** [comment]
I mean,
After follow the instruction, the "/token" endpoint seems to work, I can generate access_token & refresh_token. However, as I use POSTMAN to test [Authorization] (as you can see, /api/photos endpoint), it always use CookieAuthenticationMiddleware instead.

**Comment by PinpointTownes** [comment]
It's a very generic question then, as it's not specific to the OIDC server middleware at all (that doesn't validate tokens, BTW).

See https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/blob/dev/samples/Mvc/Mvc.Server/Startup.cs#L39-L85 for a concrete example of how you can solve that.

**Comment by st2forget** [comment]
Thanks, it leads me to AspNet.Security.OAuth.Extensions/UseOAuthValidation. However, the package is not compatible with .net core 1.1.

**Comment by PinpointTownes** [comment]
> However, the package is not compatible with .net core 1.1.

It is. All the packages built for 1.0 can be used on 1.1.

**Comment by st2forget** [comment]
My bad, it should be AspNet.Security.OAuth.Validation. 
So, I guess you should update the README file to tell consumers to install AspNet.Security.OAuth.Validation. and use OauthValidation before UseOpenIDConnect as below:

            app.UseOAuthValidation();

            app.UseOpenIdConnectServer(options =>
            {
                options.AllowInsecureHttp = true;
                options.TokenEndpointPath = "/token";
                options.Provider = app.ApplicationServices.GetService<SocosyOpenIdConnectProvider>();
            });
