### ISSUE TITLE
Issuer claim doesn't allow string override.

### ISSUE THREAD

**Issue by ejlevin1** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#443]
I am trying to get OpenIdConnect.Server to generate a JWT token that can be used for both my application as well as google firebase.  I have almost everything finished; however, google requires that the iss claim must be the service accounts email address:

![image](https://cloud.githubusercontent.com/assets/555863/26805642/80a47c50-4a12-11e7-9dd0-98180e97539d.png)

https://firebase.google.com/docs/auth/admin/create-custom-tokens

Is there a way I could override this somewhere?  Currently I only see a method to set that in the server options, and it is as a Uri.

**Comment by PinpointTownes** [comment]
> I am trying to get OpenIdConnect.Server to generate a JWT token that can be used for both my application as well as google firebase. 

ASOS is not the right tool for generating arbitrary tokens outside an OIDC request (which is the case here).

Consider using a JWT library like https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet or https://github.com/dvsekhvalnov/jose-jwt for this task.
