### ISSUE TITLE
Introspection of identity token fails

### ISSUE THREAD

**Issue by dozer75** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#444]
I have upgraded my code to the 1.0.0 release (from 1.0.0-beta6-final, yes, I know it is an old version, but haven't had time until now). 

But now when I try to do an introspection of my identity token it fails with the following stacktrace:
AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerMiddleware:Debug: An exception occured while deserializing an identity token: Microsoft.IdentityModel.Tokens.SecurityTokenInvalidSignatureException: IDX10504: Unable to validate signature, token does not have a signature: <TOKEN (should not be visible in logging mode btw)>
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerHandler.<DeserializeIdentityTokenAsync>d__27.MoveNext().

If I try to do an introspection on my access token and refresh it works, it's only the identity token that doesn't work.

It states that the token doesn't have any signature, but this worked in the beta 6 version without any code from me and all other tokens works?

How can I fix this?

**Comment by dozer75** [comment]
To answer myself on this, it seems that there is an issue that the id token generated by the library isn't signed, but the deserializing method `DeserializeIdentityTokenAsync` has the `TokenValidationParameters.RequireSignedTokens` set to `true` (which is default) and thus requires a signed token.

The question is, what is most correct? Generating a token that isn't signed or be able to deserialize an unsigned token?

Should it be configurable?

**Comment by PinpointTownes** [comment]
The behavior you're seeing is expected.

In beta7, the automatic signing key generation/storage feature was removed. If you had upgraded to beta7, ASOS would have thrown an exception telling you that no signing credentials were registered.

In rc1, we introduced a degraded mode that allows you to use ASOS without registering a signing key/certificate as long as you don't use JWT access tokens or use response_type=id_token.

Not being able to introspect identity tokens (or JWT access tokens) is expected in the degraded mode.

To fix that, register a signing key/certificate.

**Comment by dozer75** [comment]
Ok! Thanks! That explains it, it could however have passed a message that explained it? It's not obvious without analysing the source code what happens and there isn't too much examples around introspection either.

**Comment by PinpointTownes** [comment]
FYI, these two changes have been announced on my personal blog:

  - http://kevinchalet.com/2016/11/30/the-new-aspnet-contrib-packages-are-out/
  - http://kevinchalet.com/2017/03/14/migrating-to-aspnet-security-openidconnect-server-rc1/

I'll see if we can log a special trace to make that more obvious.

**Comment by dozer75** [comment]
I read those articles, but for me it wasn't clear that those affected the introspect part, anyway it is solved. So I'll close this issue :)
