### ISSUE TITLE
IIS Recycle App pool

### ISSUE THREAD

**Issue by mplesnik** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#445]
I have ASP.NET Core app deplyed on IIS.
Everything works fine until IIS recycles application pool.
After IIS recycles Application poll, the refresh tokens become invalid.
Server response:
{"error":"invalid_grant","error_description":"The specified refresh token is invalid."}

Any idea how to solve this?

For now I disabled App poll recyceling.

**Comment by PinpointTownes** [comment]
You must configure Data Protection to ensure it uses a persisted key ring. See https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview for more information.
