### ISSUE TITLE
Separate OpenIdConnect.Server For .NET Framework

### ISSUE THREAD

**Issue by dushuaihua** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#457]
Is it possible to separate a version only for .NET Framework? 
When I install "Owin.Security.OpenIdConnect.Server" from Nuget there are almost 70 packages need install.
I can only manually separate your code for my using.

**Comment by PinpointTownes** [comment]
> Is it possible to separate a version only for .NET Framework?

The OWIN/Katana version is fully compatible with >.NET 4.5.1.

> When I install "Owin.Security.OpenIdConnect.Server" from Nuget there are almost 70 packages need install.

ASOS for OWIN/Katana relies on ASP.NET Core's Data Protection stack that itself depends on .NET Standard 1.x packages. These dependencies are unfortunately **unavoidable**.

That said, it will be better in the next version (2.0) as things will be done differently in .NET Standard 2.0 (you won't have to download any additional package for the BCL types).

**Comment by dushuaihua** [comment]
Thank you for your reply.

**Comment by CameronWills** [comment]
> That said, it will be better in the next version (2.0) as things will be done differently in .NET Standard 2.0 (you won't have to download any additional package for the BCL types).

@PinpointTownes. just wondering, now that .NET Standard 2.0 has been released, is there an estimate of when the version that has a dependency on .NET Standard 2.0 might be available?

Thanks

**Comment by kevinchalet** [comment]
@CameronWills preview builds are already available (since mid-July) and can be downloaded from the MyGet feed. I'll update the README.md to reflect that.
