### ISSUE TITLE
System.IdentityModel.Tokens.JwtSecurityTokenHandler error

### ISSUE THREAD

**Issue by dushuaihua** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#458]
I upgrade the 'System.IdentityModel.Tokens.Jwt' to latest version(v5.1.4), there is an exception thrown:
```
Could not load type 'System.IdentityModel.Tokens.JwtSecurityTokenHandler' from assembly 'System.IdentityModel.Tokens.Jwt, Version=5.1.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
```
![image](https://user-images.githubusercontent.com/17045801/28679248-3128ce88-7325-11e7-83db-d0147be456e5.png)
![image](https://user-images.githubusercontent.com/17045801/28679279-4790c8a6-7325-11e7-9f0b-2458cf1a983c.png)

**Comment by PinpointTownes** [comment]
You can't use IdentityModel 5.x with OWIN/Katana. It's clearly mentioned here: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#usage.
