### ISSUE TITLE
OpenIdConnect-Server without DBConext

### ISSUE THREAD

**Issue by MarioGruda** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#460]
Hello,

till AspNet.Security.OpenIdConnect.Server - RC (or a little bit earlier?),  I was able to use it without a DbContext and without EntityFramework Core. Is it still possible, or why was it necessary to change this?

In the samples I can't find a solution,

I want to use the standard Tokenformat (not the JWT format) with password grant type.

Thank you for your great work.

Edit: Of course it works and it's super easy. I'm sorry!

**Comment by kevinchalet** [comment]
Hey,

As you figured out, yep, it's still supported. Like `OAuthAuthorizationServerMiddleware`, ASOS doesn't have - and will likely never have - any store concept.
