### ISSUE TITLE
Request accept after Signout

### ISSUE THREAD

**Issue by zote** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#461]
I'm using `return SignOut(OpenIdConnectServerDefaults.AuthenticationScheme);` to logout.
But if after that I do another authenticated request, I get status 200 not 401.

What I need to do to invalidate an Bearer token previously used on signout?

**Comment by kevinchalet** [comment]
Take a look at https://stackoverflow.com/a/35747870/542757 for more information about how you can implement token revocation (the SO question is about refresh tokens but it also applies to access tokens).
