### ISSUE TITLE
Which package for .NET Framework?

### ISSUE THREAD

**Issue by CameronWills** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#462]
Which is the correct package for .NET Framework 4.6.1 ? 
**Owin.Security.OpenIdConnect.Server** or **AspNet.Security.OpenIdConnect.Server**

There is no mention of Owin.Security.OpenIdConnect.Server in the readme.md - but @PinpointTownes you mention it in your latest blog post:

> OWIN/Katana 3.x version
>   Update-Package Owin.Security.OpenIdConnect.Server -Version 1.0.1

This is a little confusing, could this be added to the readme ?

**Comment by kevinchalet** [comment]
> Which is the correct package for .NET Framework 4.6.1 ?
Owin.Security.OpenIdConnect.Server or AspNet.Security.OpenIdConnect.Server

Both are compatible with .NET Framework 4.6.1, so the framework version is not really a good indicator to help you choose the right package :sweat_smile: 

  - If you have a `Startup` class AND if you have a `public void Configuration(IAppBuilder app)` method, then **your app is an OWIN/Katana app** and you must use `Owin.Security.OpenIdConnect.Server`.

  - If you have a `Startup` class AND if you have a `public void Configure(IApplicationBuilder app)` method, then **your app is an ASP.NET Core app** and you must use `AspNet.Security.OpenIdConnect.Server`.

  - If you have no `Startup` class at all, **your app is likely a legacy ASP.NET 4.x app**. You can easily convert it to an hybrid ASP.NET 4.x/OWIN/Katana app and use `Owin.Security.OpenIdConnect.Server`.

**Comment by CameronWills** [comment]
Also worth mentioning for anyone looking for sample code for the OWIN/Katana version. Take a look at the Nancy.Server sample:
https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/tree/dev/samples/Nancy/Nancy.Server
