### ISSUE TITLE
UserInfo endpoint claims

### ISSUE THREAD

**Issue by CameronWills** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#466]
I'm implementing the Authorization Code flow in my server.

Granting the client application (postman for now) access to these scopes:
```
/* openid: */ OpenIdConnectConstants.Scopes.OpenId,
/* email: */ OpenIdConnectConstants.Scopes.Email,
/* profile: */ OpenIdConnectConstants.Scopes.Profile,
/* offline_access: */ OpenIdConnectConstants.Scopes.OfflineAccess
```

I've added the email claim to the ticket in the `Authorize` controller endpoint:

```
// Create a new ClaimsIdentity containing the claims that will be used to create an id_token, a token or a code.
var identity = new ClaimsIdentity(
OpenIdConnectServerDefaults.AuthenticationType,
OpenIdConnectConstants.Claims.Name,
OpenIdConnectConstants.Claims.Role);


// Note: the "sub" claim is mandatory and an exception is thrown if this claim is missing.
identity.AddClaim(
  new Claim(OpenIdConnectConstants.Claims.Subject, User.Identity.Name)
  .SetDestinations(OpenIdConnectConstants.Destinations.AccessToken,
     OpenIdConnectConstants.Destinations.IdentityToken));

// Also add the email claim
identity.AddClaim(
  new Claim(OpenIdConnectConstants.Claims.Email, "user@email.com")
  .SetDestinations(OpenIdConnectConstants.Destinations.AccessToken,
  OpenIdConnectConstants.Destinations.IdentityToken));
```

However, after getting a token when I request the /connect/userinfo endpoint with the token, I only get these claims back:
```
{
    "sub": "myuser",
    "iss": "http://localhost:20170/",
    "aud": "my_client_id"
}
```

I would have thought that email would be included in this response?
I can't seem to find much information on this. Do I need to explicitly add extra claims on by overriding the `HandleUserinfoRequest` method on `OpenIdConnectServerProvider` ?
I would need to know what scopes the user has agreed to give access to..

**Comment by kevinchalet** [comment]
> I would have thought that email would be included in this response?

It should (as long as the `email` scope is granted).

Enable logging - make sure you change the default log level to `Trace`) and post the entire logs here. It will help determine why it's not working as expected.

**Comment by CameronWills** [comment]
Ok, turned out the problem was that I was not specifying scopes in the request from the client application (postman)
![image](https://user-images.githubusercontent.com/1278887/29107311-ec6975a2-7d1c-11e7-8baa-81754e77a488.png)

Once I added the scopes the claims appeared in the UserInfo response.

Thanks for your help.
