### ISSUE TITLE
Support for CORE 2

### ISSUE THREAD

**Issue by eduardotolino** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#468]
Hello.
Is support for .NET CORE 2 planned?

The same code that I use in CORE 1.1 does not compile in CORE 2.
If I create a 2.0 project and change the target to 1.1, it starts compiling.

Message:
Reference to type BaseControlContext claims it is denifed in Microsoft.AspNetCore.Authentication

This message appears when you try to use the following classes:

ValidateTokenRequestContext
-> context.Reject
-> context.Skip

HandleTokenRequestContext
-> context.Ticket
-> context.Options.AuthenticationScheme
-> context.Validate

AuthenticationTicket
-> ticket.SetScopes

Can you help me?

Thank you.

**Comment by kevinchalet** [comment]
Hey,

> Is support for .NET CORE 2 planned?

It's actually already available. ASOS 2.0.0-preview1-* nightly builds (targeting ASP.NET Core 2.0 RTM) can be found on the MyGet feed: https://www.myget.org/gallery/aspnet-contrib

**Comment by eduardotolino** [comment]
Thank you so much.
This solved almost every problem.

However, with this preview version I have two problems:

app.UseOpenIdConnectServer is not found.

I've tried manually finding the extension and even using AspNet.Security.OpenIdConnect.Server there is no implementation for IApplicationBuilder.

![err1](https://user-images.githubusercontent.com/20425889/29380725-1d5b106e-829d-11e7-8a44-94ddcda6856c.png)


context.Options.AuthenticationScheme was not found in this preview.

![err2](https://user-images.githubusercontent.com/20425889/29380731-23c7dacc-829d-11e7-96f3-e2eb2eb14e90.png)


thank you again.

**Comment by kevinchalet** [comment]
That's expected: these methods are gone in 2.0. Read https://github.com/aspnet/Announcements/issues/262 for more information.

**Comment by eduardotolino** [comment]
Do you have any example or document working?

I have tried with several and several ways and always getting the following message:

"No authenticationScheme was specified, and there was no DefaultChallengeScheme found." when I pass the token on a method [Authorize]

I know changed the authentication scheme of 1.1 pro 2.0 but could not find any documents with OpenIdConnect.

I tried:
```
services.AddAuthentication()
  .AddOpenIdConnectServer(options => {
     options.Provider = new AuthorizationProvider();
     options.TokenEndpointPath = "/connect/token";
     options.AllowInsecureHttp = true;
     options.SigningCredentials.AddEphemeralKey();
  });

```
and 

```
 var identity = new ClaimsIdentity(JwtBearerDefaults.AuthenticationScheme);
 var user = result.Data as UserInfo;

 identity.AddClaim(OpenIdConnectConstants.Claims.Subject, user.IdUser.ToString());
                identity.AddClaim(ClaimTypes.NameIdentifier, user.IdUser.ToString(), Destinations.AccessToken);
                identity.AddClaim(ClaimTypes.Name, user.Username, Destinations.AccessToken);
                identity.AddClaim(ClaimTypes.GivenName, user.FirstName, Destinations.AccessToken, Destinations.IdentityToken);
                identity.AddClaim(ClaimTypes.Email, user.Email, Destinations.AccessToken, Destinations.IdentityToken);

                var ticket = new AuthenticationTicket(
                    new ClaimsPrincipal(identity),
                    new AuthenticationProperties(),
                    JwtBearerDefaults.AuthenticationScheme
                );

                ticket.SetScopes(
                    Scopes.OpenId,
                    Scopes.OfflineAccess
                );

                context.Validate(ticket);
```

**Comment by kevinchalet** [comment]
> Do you have any example or document working?

https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/tree/dev/samples/Mvc

**Comment by eduardotolino** [comment]
I finally got it to work. 

When installing the **AspNet.Security.OpenIdConnect.Server** 2.0.0-preview1-1306 , the **AspNet.Security.OAuth.Validation** 1.0 was installed as dependency (automatically).

I was able to make it work by installing the library in the 2.0.0-preview1-0283 version.

Thanks a lot for the help.

**Comment by kevinchalet** [comment]
> When installing the AspNet.Security.OpenIdConnect.Server 2.0.0-preview1-1306 , the AspNet.Security.OAuth.Validation 1.0 was installed as dependency (automatically).

That's weird because `AspNet.Security.OpenIdConnect.Server` does not depend on `AspNet.Security.OAuth.Validation`. Are you sure you didn't reference it in your own app?
