### ISSUE TITLE
2.0.0 preview errors

### ISSUE THREAD

**Issue by mcowart123** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#469]
Hello,

How are the 2.0.0 packages coming along? I've pointed my project to the myget feed and have a few errors:

1. app.UseOAuthValidation and app.UseOpenIdConnectServer do not seem to exist anymore (here are my using statements):
`using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.IO;

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.PlatformAbstractions;
using Microsoft.Extensions.Options;
using Microsoft.AspNetCore.DataProtection.Repositories;
using Microsoft.AspNetCore.DataProtection;

using Swashbuckle.AspNetCore.Swagger;`

2. context.Options.AuthenticationScheme seems to be missing as well (using statements again):
`using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Security.Claims;

using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;
using Microsoft.AspNetCore.Authentication;

using AspNet.Security.OpenIdConnect.Primitives;
using AspNet.Security.OpenIdConnect.Extensions;
using AspNet.Security.OpenIdConnect.Server;`

Is there anything I'm missing? Code was fully working in 1.2.

Thanks

**Comment by kevinchalet** [comment]
Hey,

Read https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/issues/468 and https://github.com/aspnet/Announcements/issues/262.
