### ISSUE TITLE
AuthenticationTicket exists in two assemblies 

### ISSUE THREAD

**Issue by grishaandrianov** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#470]
I created an ASP.NET Core 2 project with target framework .NET Framework 4.7:
`<TargetFramework>net47</TargetFramework>`

and Installed nuget package AspNet.Security.OpenIdConnect.Server -Version 1.0.1:
`<PackageReference Include="AspNet.Security.OAuth.Validation" Version="1.0.0" /> <PackageReference Include="AspNet.Security.OpenIdConnect.Server" Version="1.0.0" />`

Now, when I'm trying to use AuthenticationTicket class, I'm getting an error:
`Error CS0433	The type 'AuthenticationTicket' exists in both 'Microsoft.AspNetCore.Authentication.Abstractions, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Authentication, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'`

**Comment by kevinchalet** [comment]
Massive changes have been introduced in ASP.NET Core 2.0's authentication stack and `AuthenticationTicket` being moved to a different assembly is one of them (read https://github.com/aspnet/Announcements/issues/262 for more information).

To use ASOS in an ASP.NET Core 2.0 app, use the ASOS `2.0.0-preview1-*` nightly builds (same thing for the validation middleware).

**Comment by grishaandrianov** [comment]
Now I use the latest version from the repository (not a nuget-package) and there is no such error

**Comment by kevinchalet** [comment]
Any reason not to use our MyGet feed?

**Comment by grishaandrianov** [comment]
I just haven't noticed that it is even exist, thanks
