### ISSUE TITLE
reference error on donetcore 2.0

### ISSUE THREAD

**Issue by jimmymain** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#473]
When attempting to override  `HandleTokenRequest` I receive reference errors on dotnetcore 2.0

```
    public class AuthorizationProvider : OpenIdConnectServerProvider
    {
        public override async Task HandleTokenRequest(HandleTokenRequestContext context)
        {
            // HttpContext has a reference problem.
            var manager = context.HttpContext
                            .RequestServices
                            .GetRequiredService<UserManager<ApplicationUser>>();
```

> Reference to type 'BaseControlContext' claims it is defined in 'Microsoft.AspNetCore.Authentication', but it could not be found... (perhaps due to breaking changes in dotnetcore 2.0)

**Comment by kevinchalet** [comment]
I assume you're using the ASOS 2.0.0-preview1 nightly builds, as indicated in the README?

> Note: the AspNet.Security.OpenIdConnect.Server 2.x packages are only compatible with ASP.NET Core 2.x. If your application targets ASP.NET Core 1.x, use the AspNet.Security.OpenIdConnect.Server 1.x packages.

**Comment by jimmymain** [comment]
Hi,
Sorry, I missed the preview, and I know this is probably not the correct forum, so I can ask my question on stackoverflow if necessary, but I am still battling a little with the preview with dotnetcore 2.0.

I have followed the instructions at [myget](https://www.myget.org/feed/aspnet-contrib/package/nuget/AspNet.Security.OpenIdConnect.Server).

I have managed to validate and return the bearer token by posting to `connect/token`, but when attempting to call an API with the `Authorize` attribute, the bearer token is not being validated / checked.

I have changed the cookie authentication (also present) to the following.
```
            services.ConfigureApplicationCookie(
                options =>
                {
                    options.LoginPath = "/login";
                    options.LogoutPath = "/logout";
                    options.Events.OnRedirectToLogin = _ =>
                    {
                        if (_.Request.Path.StartsWithSegments("/api")
                            && _.Response.StatusCode == (int)HttpStatusCode.OK)
                            _.Response.StatusCode = (int)HttpStatusCode.Unauthorized;
                        else
                            _.Response.Redirect(_.RedirectUri);
                        return Task.CompletedTask;
                    };
                });
```

When requesting with or without the Bearer token authorization header, I am still getting 401?

**Comment by kevinchalet** [comment]
Are your API controllers decorated with `[Authorize(AuthenticationSchemes = OAuthValidationDefaults.AuthenticationScheme)]`?

**Comment by jimmymain** [comment]
@PinpointTownes that solved the problem.
Is there any chance I can make the default authorisation cater for both cookie and token at the same time without specifically narrowing to just the one?

**Comment by kevinchalet** [comment]
@jimmymain nope (and frankly, you shouldn't): https://github.com/aspnet/Announcements/issues/262.

**Comment by jimmymain** [comment]
@PinpointTownes thanks very much.
I did manage to get it to work by adding the below code.
I will however heed your advice... Still trying to understand it all.

My client is angular 4, so I will be removing cookies altogether at some point. It's just useful for now. 

```
services.AddAuthentication(o =>
{
      o.DefaultChallengeScheme = OAuthValidationDefaults.AuthenticationScheme;
      o.DefaultAuthenticateScheme = OAuthValidationDefaults.AuthenticationScheme;
      o.DefaultSignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
})
```
