### ISSUE TITLE
OAuth Scope in RefreshToken checks

### ISSUE THREAD

**Issue by Tornhoof** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#474]
Hi,
according to OAuth RFC the scopes in a refreshtoken need to be, if specified, a subset of the scopes in the original request:
https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/blob/a499f11cc5dceaf74c60d111c7c4268452cd8ddd/src/AspNet.Security.OpenIdConnect.Server/OpenIdConnectServerHandler.Exchange.cs#L486-L498

I think it would be useful to have optionally have a method in there which specifies "what is a subset".  For example https://help.shopify.com/api/getting-started/authentication/oauth has write_XYZ and read_XYZ permissions and write includes the read permission. So if originally scope includes e.g. write_product it would not be possible to downgrade to read_product, without including the specific scope name in the original request.
As far as I understand Heroku uses a similar system: https://devcenter.heroku.com/articles/oauth#scopes
I don't know if they actually use it like that, my information is primarily from ther dev guidelines.

I unfortunately use a similar system and the old OWIN Auth Middleware did not such checks so I ran into this issue during migration. What I do basically is having the user login using password with a global scope, he then can call an endpoint returning specific user information (tenants, roles, groups) he is part of. He then can use the refresh token to limit his access token by adding e.g. a specific role to the scope. Basically he has "all scopes" with the first token and can further reduce the scope. I modelled that system after Heroku, they have the global scope too.

I understand that this is probably stretching the definition of subset of scopes quite a bit.

Having a method there solves my problem, I can simply then say that my "global" scope is the superset of any more limited scope.

**Comment by kevinchalet** [comment]
Hey,

That's an interesting scenario.

> I understand that this is probably stretching the definition of subset of scopes quite a bit.

Probably too much for my taste, yeah :sweat_smile: 

Instead, have you considered using the `ExtractTokenRequest` event to dynamically replace the requested `scope` parameter? Something like that:

```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddAuthentication()
        .AddOpenIdConnectServer(options =>
        {
            // ...

            options.Provider.OnExtractTokenRequest = context =>
            {
                var scopes = new HashSet<string>(context.Request.GetScopes());

                // If the special "global" alias was specified,
                // include all the supported read/write scopes.
                if (scopes.Contains("global"))
                {
                    scopes.Add("read_profile");
                    scopes.Add("write_profile");
                    scopes.Remove("global");
                }

                // Note: "write_profile" implies "read_profile".
                if (scopes.Contains("write_profile"))
                {
                    scopes.Add("read_profile");
                }

                // Replace the requested scopes by the computed scopes set.
                context.Request.Scope = string.Join(' ', scopes);

                return Task.CompletedTask;
            };
        });
}
```

**Comment by Tornhoof** [comment]
Thank you for suggestion, I understand your reluctance to change that.

**Comment by kevinchalet** [comment]
Please let me know when you have a chance to test my suggestion. I'm interested in knowing if it fits your needs.

**Comment by Tornhoof** [comment]
Just tried it, it works nicely. I will probably put it into DeserializeRefreshToken as I'm currently using a custom refresh token (not yet ported) and there I have full control over the ticket anyway. But my Unit Tests work for now.
Thank you again.
