### ISSUE TITLE
Cant get Session in API connect/token?

### ISSUE THREAD

**Issue by meninjanho4788** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#475]
[HttpPost("~/connect/token"), Produces("application/json")]
    [AllowAnonymous]
    public async Task<IActionResult> Exchange(OpenIdConnectRequest request)
    {   ....
        var data = HttpContext.Session.GetString("MySession");
        ....
    }
I try to get any session in api but values is null.

**Comment by kevinchalet** [comment]
It's just a regular controller, so it should work assuming the session middleware is correctly registered.

That said, you should NEVER do that: the token endpoint is an endpoint made for API clients and thus is not protected against XSRF attacks. Trying to use sessions will make your application vulnerable to this class of attack.

**Comment by meninjanho4788** [comment]
Many thank you. If use session make class easy attack i will not use this. I will try other way.
