### ISSUE TITLE
Change Signing Key

### ISSUE THREAD

**Issue by MarioGruda** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#477]
Hello,

first of all thank you for your great work.

I have a little question.

Is it possible to change the signing key without using JWT?

The goal is that the key is created independently of the machine and is therefore compatible across all instances.

I have tried 

`options.SigningCredentials.AddKey(securityKey);`

and 

`options.SigningCredentials.AddCertificate(/*.....*/.);`

but I failed. 

Maybe I made a mistake.

Thank you!

**Comment by kevinchalet** [comment]
Hey,

> Is it possible to change the signing key without using JWT?

When using the default token format, the `SigningCredentials` property is not used. Instead, ASOS directly relies on ASP.NET Core's Data Protection stack to manage the keys and sign/encrypt the tokens.

You can configure that using the regular Data Protection APIs: https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview

**Comment by MarioGruda** [comment]
Thank you. That helped me a lot!

I will take a closer look at `ProtectKeysWithCertificates(...)`.

[X.509 certificate](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/implementation/key-encryption-at-rest#x509-certificate)
