### ISSUE TITLE
Fast tutorial for green. (refresh_token)

### ISSUE THREAD

**Issue by HelloMyDevWorld** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#479]
Hello,

I would be appreciated if someone could post little sample about refresh_token from postman, and say some words about refresh_token ?

BR

**Comment by kevinchalet** [comment]
Hey,

You can find a Postman sample implementing password + refresh token in the samples repo: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Samples/tree/master/samples/Postman

**Comment by GiuseppePiscopo** [comment]
Some useful posts where referenced in an old [issue comment](https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/issues/266#issuecomment-217646273). Copying them here:

* http://stackoverflow.com/a/34979776/542757
* http://stackoverflow.com/a/35732159/542757
* http://stackoverflow.com/a/35747870/542757

**Comment by kevinchalet** [comment]
@GiuseppePiscopo :+1:
