### ISSUE TITLE
Feature Request : Documentation

### ISSUE THREAD

**Issue by davidrevoledo** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#485]
@PinpointTownes Hi Kevin, I'm starting with this package to implement a server with asp.net core 2.0 and net.core I'm having some issues cause the example for MVC and the main code doesn't work for me with the default AspNetCore Api project,
I don't found any documentation for this project.

If I don't found and this already exist, please sorry hahaha.
Otherwise I can write a small documentation for a startup project and configurations for future persons that want  to start with it.

Kind regards.
David

**Comment by kevinchalet** [comment]
Hey David,

> I don't found any documentation for this project.
If I don't found and this already exist, please sorry hahaha.

Last year I dedicated a blog posts series to ASOS 1.0.0 that you can find here: http://kevinchalet.com/2016/07/13/creating-your-own-openid-connect-server-with-asos-introduction.

I don't plan to create dedicated documentation for ASOS as it's a low-level component designed for people who are already familiar with OAuth2/OIDC or have used `OAuthAuthorizationServerMiddleware` in the past. That said, if someone wants to fund this effort, I'll probably reconsider it.
