### ISSUE TITLE
ASOS does not issue refresh tokens even though "offline_access" is set?

### ISSUE THREAD

**Issue by l3utterfly** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#487]
I have copied the Accept endpoint from the sample provided:

    // Create a new authentication ticket holding the user identity.
            var ticket = new AuthenticationTicket(
                new ClaimsPrincipal(identity),
                new AuthenticationProperties(),
                OpenIdConnectServerDefaults.AuthenticationScheme);

            // Set the list of scopes granted to the client application.
            ticket.SetScopes(new[]
            {
                OpenIdConnectConstants.Scopes.OpenId,
                OpenIdConnectConstants.Scopes.Email,
                OpenIdConnectConstants.Scopes.Profile,
                OpenIdConnectConstants.Scopes.OfflineAccess
            });

            // Set the resources servers the access token should be issued for.
            ticket.SetResources("resource_server");

            // Returning a SignInResult will ask ASOS to serialize the specified identity to build appropriate tokens.
            // Note: you should always make sure the identities you return contain ClaimTypes.NameIdentifier claim.
            return SignIn(ticket.Principal, ticket.Properties, ticket.AuthenticationScheme);

However, the response does not contain a refresh token.

When I implemented the password grant manually:

    var identity = AuthHelpers.NewUserClaimsIdentity(user);

                    var ticket = new AuthenticationTicket(
                        new ClaimsPrincipal(identity),
                        new Microsoft.AspNetCore.Authentication.AuthenticationProperties(),
                        OAuthValidationDefaults.AuthenticationScheme);

                    ticket.SetScopes(new[]
                    {
                        OpenIdConnectConstants.Scopes.OpenId,
                        OpenIdConnectConstants.Scopes.Email,
                        OpenIdConnectConstants.Scopes.Profile,
                        OpenIdConnectConstants.Scopes.OfflineAccess
                    });

                    context.Validate(ticket);

I was able to obtain a request token.

Do you know what I'm doing wrong for the ASOS SignIn method?

I am using 2.0-rc for net core 2.0

**Comment by kevinchalet** [comment]
> However, the response does not contain a refresh token.

Authorization responses can't contain a refresh token as it's explicitly forbidden by the OAuth2 specification.

**Comment by l3utterfly** [comment]
Ahh ok. Do you have any suggestion as to what is the best way to keep the
user logged in in this case?

**Comment by kevinchalet** [comment]
If your client app is a mobile or desktop app, you can use the code flow.
If it's a browser app, you can use prompt=none authorization requests, sent in an iframe. You can see this OpenIddict sample for a demo: https://github.com/openiddict/openiddict-samples/blob/dev/samples/ImplicitFlow/AuthorizationServer/Controllers/AuthorizationController.cs
