### ISSUE TITLE
Cookie auth ?

### ISSUE THREAD

**Issue by HelloMyDevWorld** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#488]
Hello,

I've question about Cookie when i set my bearer token into "Set-Cookie:",
is there any way to auth me from "Cookie: sth" ?? 

BR

**Comment by kevinchalet** [comment]
Hey,

Is that a real question? :sweat_smile:

**Comment by patsadow2** [comment]
I dont know how to use it

            .AddCookie("ClientCookie", options =>
            {
                options.Cookie.Name = CookieAuthenticationDefaults.CookiePrefix + "ClientCookie";
                options.ExpireTimeSpan = TimeSpan.FromMinutes(5);
            })

To get set-cookie: after /connect/token ?

**Comment by kevinchalet** [comment]
Never do that, it's an abomination from a security perspective. Read https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.OpenId/Controllers/AccessController.cs#L183-L187 for more information.

**Comment by patsadow2** [comment]
So it's not possible anymore in that lib ? AspNet.Security.OpenIdConnect.Server

**Comment by kevinchalet** [comment]
It should still be possible, but I won't show you how as it's insanely insecure. Consider fixing your code to use an interactive flow like code or implicit if you really need to issue cookies.

**Comment by patsadow2** [comment]
I would like to store access_token in httponly cookie and refresh it sometimes.

**Comment by patsadow2** [comment]
Strompath: "You should store JWTs in secure, HTTPS-only cookies. This prevents Cross-Site Scripting XSS attacks. We’ll cover this more in the section below, “Tokens Love Cookies” So how should be done here ?
