### ISSUE TITLE
Redirection problem during access to resources

### ISSUE THREAD

**Issue by HelloMyDevWorld** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#489]
I spent about 5h trying to find out what is wrong, after create bearer token 
i am trying to get ot resource and always "http://localhost:4000/Account/Login?ReturnUrl=%2Fapi%2Fmessage" what could be wrong ?

I missed sth important?

It looks like token is not recognized by "Authorize" attribute :)
BR

**Comment by kevinchalet** [comment]
https://github.com/openiddict/openiddict-core/issues/498#issuecomment-340254993
