### ISSUE TITLE
Token in HTTPonly Cookie.

### ISSUE THREAD

**Issue by HelloMyDevWorld** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#490]
Hello, 

Could anyone can tell me how should i setup the settings to get identity cookie from server in "Set-Cookie: HTTPonly" and then use it in request like a token (Authorize attribute automaticly read "Cookie:" ? I don't know either where should i set some kind of middleware to validate that cookie to make [Authorize] attribute work. Could anyone give some sample ? Thanks

I only know how to do that in not appropriate way.
1. Set-Cookie in response body from the code not middleware
2. Request controller with no attribute
3. Inside controller create request with header "Bearer: token" and ask api controller with [Authorize] attribute.

Any ideas codes tutorials?

Is it okey and will it work ?

```
            services.AddAuthentication(options =>
            {
                options.DefaultScheme = "ClientCookie";
            })

            .AddCookie("ClientCookie", options =>
            {
                options.Cookie.Name = CookieAuthenticationDefaults.CookiePrefix + "ClientCookie";
                options.ExpireTimeSpan = TimeSpan.FromMinutes(5);
                options.LoginPath = new PathString("/signin");
                options.LogoutPath = new PathString("/signout");
            })


```

under Controller

```
[HttpPost("~/signin")]
	public async Task<IActionResult> Login(LoginModel loginModel)
	{
		if(LoginUser(loginModel.Username, loginModel.Password))
		{
			var claims = new List<Claim>
			{
				new Claim(ClaimTypes.Name, loginModel.Username)
			};
 
			var userIdentity = new ClaimsIdentity(claims, "login");
 
			ClaimsPrincipal principal = new ClaimsPrincipal(userIdentity);
			**await HttpContext.SignInAsync(principal);** //??????????????
 
			return Redirect("/");
		}
		return View();
	}
 

```

And then:

`Request resource with [Authorize(AuthenticationSchemes = "ClientCookie")] // ??`

Am i okey with that ?

Another idea to add always cookie during /connect/token and change request from cookie to header every request in middleware ??

**Comment by kevinchalet** [comment]
As I already said, don't return any authentication cookie from the token endpoint. It's a pure abomination from a security perspective.

If you develop a JS app, use the local or session storage.
