### ISSUE TITLE
Event hooks

### ISSUE THREAD

**Issue by l3utterfly** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#491]
Is there any examples on how to hook into events? Something like this:

    services.AddAuthentication()
        .AddJwtBearer(o =>
        {
            o.Events.OnMessageReceived = context =>
            {
                context.Token = (string)context.HttpContext.Items["token"];
                return Task.CompletedTask;
            };
        });

This is one for Jwt library. There is something similar which I've found in the configuration opens for OpenIdConnect server, but the event is just an Object.

Is this still in the works? I'm using the 2.0 rc library

**Comment by kevinchalet** [comment]
> Is this still in the works? I'm using the 2.0 rc library

This is already fully supported (since the very first ASOS version, BTW). The only difference with the ASP.NET Core JWT handler is that the property is named `options.Provider` instead of `options.Events`.

Take a look at the README or at the MVC sample to see how to use it.
