### ISSUE TITLE
ValidateIntrospectionRequestContext is inherited from BaseValidatingClientContext

### ISSUE THREAD

**Issue by jasondaicoder** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#492]
Hi guys,

Can I ask why ValidateIntrospectionRequestContext  is inherited from BaseValidatingClientContext which asks the client id during the validation. Per oauth2 standard, when doing token introspection, we don't need the client information.

Thanks in advance.

Jason

**Comment by kevinchalet** [comment]
Hi @jasondaicoder,

> Per oauth2 standard, when doing token introspection, we don't need the client information.

Actually, you do need it (even though ASOS allows you to skip validation if client authentication cannot be enforced):

> To prevent token scanning attacks, the endpoint MUST also require some form of authorization to access this endpoint, such as client authentication as described in OAuth 2.0 [RFC6749] or a separate OAuth 2.0 access token such as the bearer token described in OAuth 2.0 Bearer Token Usage [RFC6750]. The methods of managing and validating these authentication credentials are out of scope of this specification.

https://tools.ietf.org/html/rfc7662#section-2.1

**Comment by jasondaicoder** [comment]
Thanks for your reply. Yes per oauth2 standard, when doing token introspection, the only required parameter is token and token_type_hint as optional. However when setting up token instrospection endpoint using ASOS ,the client_id is mandatory because the reason I listed in the question.

**Comment by kevinchalet** [comment]
> the client_id is mandatory because the reason I listed in the question.

It's not.

We have tests that ensure introspection requests are not rejected if the `client_id` is unknown (it's up to you to call `context.Skip()` like you'd do with the token endpoint). E.g:

https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/blob/b0dd45df50fe6831f3a7cb6feb210f785aec3e45/test/AspNet.Security.OpenIdConnect.Server.Tests/OpenIdConnectServerHandlerTests.Introspection.cs#L674-L738

**Comment by jasondaicoder** [comment]
Thanks a lot. I finally got it working without providing client id. Just one more thing to confirm. By default the confidential level is set to private on the ticket, this will reject the intropspection request. What I did is to override the value to public during the token generation. Is that the proper way to dot it?
