### ISSUE TITLE
Implement only token authentication as shown on "Get started" page not working.

### ISSUE THREAD

**Issue by JakubR** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#493]
Hi,
On your site : https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server 
I see "Get started" sample.
I can generate token using /connect/token, but when I implement this sample, I can't login in in to any of my controllers with attribute "[Authorize]".
Generated token is not valid, I can't decode it with jwt.io with message : Invalid Signature.

I don't want to implement cookie based authenitcation, so sample in https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/blob/dev/samples/Mvc/Mvc.Server/Startup.cs .
Could anybody help me with that?

**Comment by kevinchalet** [comment]
> Generated token is not valid, I can't decode it with jwt.io with message : Invalid Signature.

By default, the access tokens are generated using the ASP.NET Core Data Protection stack. They are not JWT tokens so they can't be validated using a JWT validator like jwt.io.

**Comment by JakubR** [comment]
Thanks for answer, I was expecting that jwt.io will work because of article : http://kevinchalet.com/2016/07/13/creating-your-own-openid-connect-server-with-asos-testing-your-authorization-server-with-postman/

But I still have no clue how to get this work...
