### ISSUE TITLE
[Antiforgery] problem in SPA

### ISSUE THREAD

**Issue by HelloMyDevWorld** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#494]
Hello,

Is there any option to make it work with [Authorization] and [Antiforgery] attribute together in SPA aplication.

Does anyone know how to say antiforgery to create X-TOKEN based on claims from Authorization and correctly validate it ?? if it's not anonymos antiforgery (random token) ??

Br

**Comment by kevinchalet** [comment]
Duplicate of https://github.com/aspnet/Security/issues/1537 (which has nothing to do with this project, BTW).

Be patient, someone from the ASP.NET team will answer your question.
