### ISSUE TITLE
When version 2.0.0 final is going to be released?

### ISSUE THREAD

**Issue by madnik7** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#497]
I have been monitoring the latest version, I see there is no commit since October. Do you have a plan to publish version 2.0.0?

**Comment by kevinchalet** [comment]
Not before the [OAuth 2.0 Token Exchange specification](https://datatracker.ietf.org/doc/draft-ietf-oauth-token-exchange/) is adopted by the OAuth WG. This specification - that I want to support ASAP - will require making changes in our OIDC primitives (e.g in the core OAuth2 specification, you couldn't specify multiple token request parameters. In this spec, it's allowed to specify multiple `resource` parameters).

That said, the RC version that was pushed to NuGet.org earlier this year is perfectly stable. You have no reason not to use it.
