### ISSUE TITLE
Client Id should not be required in ROPC (password) request

### ISSUE THREAD

**Issue by radicalapps** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#498]
The server is unable to validate a request when request.IsPasswordGrantType() returns true and the ClientId is null. I may be wrong, but I think that the ClientId is not required for this type of request. Here's a [link.](https://tools.ietf.org/html/rfc6749#section-4.3.1) to the oauth2 reference, and I believe that whilst it's not explicit in the specification, OpenID Connect supports all OAuth 2.0 flows since it is an extension of OAuth 2.0.
I think that OpenIdCOnnectServer, and OpenIdDict, shojld not require Client_id for a request int he case where context.Request.IsPasswordGrantType() returns true.
Jeff.

**Comment by kinosang** [comment]
As the OAuth 2.0 spec ([RFC6749](https://tools.ietf.org/html/rfc6749)) defined, ClientId and ClientSecret are required for all confidential clients ([#Section-2.3](https://tools.ietf.org/html/rfc6749#section-2.3)).

And the token endpoint requires client authentication for confidential clients or for any client that was issued client credentials ([#Section-4.1.3](https://tools.ietf.org/html/rfc6749#section-4.1.3)).

**Comment by radicalapps** [comment]
From the OAuth2 standard (link in my initial message above), there is no mention of those parameters. What am I missing?

Access Token Request

   The client makes a request to the token endpoint by adding the
   following parameters using the "application/x-www-form-urlencoded"
   format per Appendix B with a character encoding of UTF-8 in the HTTP
   request entity-body:
   grant_type
         REQUIRED.  Value MUST be set to "password".
   username
         REQUIRED.  The resource owner username.
   password
         REQUIRED.  The resource owner password.
   scope
         OPTIONAL.  The scope of the access request as described by
         Section 3.3.

**Comment by kinosang** [comment]
@radicalapps see Section#4.1.3

**Comment by kinosang** [comment]
In Section#4.3.2:

```
 The authorization server MUST:

   o  require client authentication for confidential clients or for any
      client that was issued client credentials (or with other
      authentication requirements),

   o  authenticate the client if client authentication is included, and

   o  validate the resource owner password credentials using its
      existing password validation algorithm.
```

**Comment by radicalapps** [comment]
Right, however, a browser-based application (user-agent based application using the terminology in the spec), is a public client, and not a confidential client. The client_id is only required for confidential clients when using the ROPC access token request. This is the scenario in which I believe that the ASOS behaviour should change, 
I do note that the examples suggest using context.Skip(), which does server as a workaround. However, I would prefer to be able to use context.Validate() so that I know that any other requirements have been validated. This worked as expected in the legacy Asp.Net middleware.

**Comment by kevinchalet** [comment]
> I do note that the examples suggest using context.Skip(), which does server as a workaround.

It's certainly not a workaround as `contextSkip()` is the recommended way to tell the server client authentication was skipped. It's the API OpenIddict uses to skip client authentication for public clients.

Read http://kevinchalet.com/2016/07/13/creating-your-own-openid-connect-server-with-asos-creating-your-own-authorization-provider/ and http://kevinchalet.com/2016/07/13/creating-your-own-openid-connect-server-with-asos-implementing-the-resource-owner-password-credentials-grant/ for more information.

**Comment by radicalapps** [comment]
Ok, so a client_id is not required for a public client to access the Resource Owner Password Credentials grant, and the way to work with ASOS in this scenario is to ensure that the client authentication is skipped when a public client accesses ROPC. 
Many thanks for clearing it up.
