### ISSUE TITLE
How to access HttpContext.Items from OpenIdConnectServerProvider?

### ISSUE THREAD

**Issue by shaulbehr** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#502]
We're migrating our ASP.NET code from .NET Framework to .NET Core. In our old implementation of OAuthAuthorizationServerProvider we had access to context.OwinContext.Environment, a dictionary of values stored in the Owin context. If I've understood correctly, I need to convert our auth provider to inherit OpenIdConnectServerProvider, which seems to parallel most of the functionality, but I'm not sure what is analogous to the Environment mentioned above?  I'm guessing it's replaced by the HttpContext.Items collection. But that doesn't appear to be accessible within the OpenIdConnectServerProvider? How do I get to it?

**Comment by kevinchalet** [comment]
```csharp
public override Task HandleTokenRequest(HandleTokenRequestContext context)
{
    var items = context.HttpContext.Items;

    // ...
}
```

**Comment by shaulbehr** [comment]
@PinpointTownes I don't see any `HttpContext` property on `HandleTokenRequestContext`...?

**Comment by kevinchalet** [comment]
Take a closer look :smile:

**Comment by shaulbehr** [comment]
@PinpointTownes D'oh. I was on version 1.0.2. The preview-2.0.0 version has the property. Thanks.
