### ISSUE TITLE
Remove OpenIdConnectRequest.Resource and the GetResources() extension

### ISSUE THREAD

**Issue by kevinchalet** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#505]
In ASOS 1.0, the special `resource` parameter - defined in the [Resource Indicators for OAuth 2.0 draft](https://tools.ietf.org/html/draft-campbell-oauth-resource-indicators-02) (that was sadly never officially adopted) - can be used to allow OAuth2 clients to request access to specific named resource servers (APIs).

Unfortunately, a parameter with the same name (but with a different syntax) is going to be standardized by the `OAuth 2.0 Token Exchange` specification, that we want to support in ASOS.

Starting with 2.0.0-rc3, ASOS will no longer expose `OpenIdConnectRequest.Resource/GetResources()` to avoid confusions between the two parameters. Users that depend on these APIs are encouraged to use the `scope` parameter and determine the applicable resources based on custom scopes. E.g:

```csharp
var resources = new List<string>();
if (request.HasScope("marketing-tool"))
{
    resources.Add("marketing-api");
}

ticket.SetResources(resources);
```

Alternatively, users that prefer avoiding a breaking change can create their own helper:

```csharp
public static IEnumerable<string> GetResources(this OpenIdConnectRequest request)
{
    if (request == null)
    {
        throw new ArgumentNullException(nameof(request));
    }

    var resource = (string) request["resource"];
    if (string.IsNullOrEmpty(resource))
    {
        return Enumerable.Empty<string>();
    }

    return resource.Split(
        OpenIdConnectConstants.Separators.Space,
        StringSplitOptions.RemoveEmptyEntries).Distinct(StringComparer.Ordinal);
}
```

**Comment by xperiandri** [comment]
Not a big deal then. I will use a custom parameter. I just haven't figured out first how to do that in MS.OIDC package
