### ISSUE TITLE
Confidentiality of tokens

### ISSUE THREAD

**Issue by ghost** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#509]
Hi,

I was explaining to a collegeau about the option to skip or validate a request and the consequences (i.e. a token being marked as either confidential or non confidential). I have read that this has impact on introspection amongst other things. I couldn't find an exact, in depth, overview of the differences and consequences these have. Can someone elaborate?

**Comment by kevinchalet** [comment]
Hey,

> I have read that this has impact on introspection amongst other things.

Yup. Basically, the difference is that a token marked "confidential" is assumed to have been issued privately via the token endpoint, with client authentication enforced (i.e its only known by the client application: even the resource owner can't access it).

As a consequence, a "confidential" token can only be used on subsequent calls (e.g during a `grant_type=authorization_code` or `refresh_token` token request or an introspection/revocation request request) if the client can be authenticated (and corresponds to the client the token was issued to).
