### ISSUE TITLE
doubt about refresh token.

### ISSUE THREAD

**Issue by eduardotolino** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#511]
hello.

is there any mechanism so that after updating a .net core project (DLLs), or with the application restart (IIS), a token can be revalidated so that the user remains valid and logged in?

today with each new update of my project, the token is invalidated and the user is disconnected from the application and a new login is required.

after an update the returned message is:
The specified refresh token is invalid.

thank you so much.

**Comment by kinosang** [comment]
You are using the ephemeral keys, you should add your own signing credentials by using `options.SigningCredentials.AddCertificate()`.

**Comment by eduardotolino** [comment]
thanks for the quick response. @kinosang 

I am using as below:
options.SigningCredentials.AddCertificate(
                    typeof(Startup).GetTypeInfo().Assembly,
                    "Certificate.pfx",
                    "password");

**Comment by kinosang** [comment]
@Tolitech okay, I found #477, it's not work for the  the default token format, it uses the Data Protection APIs.

**Comment by kevinchalet** [comment]
@kinosang is right, refresh tokens are encrypted using Data Protection.

For more information about how to configure it for production, read https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?tabs=aspnetcore2x#data-protection.

**Comment by eduardotolino** [comment]
thank you, @kinosang 
thank you, @PinpointTownes 

This is a bit complicated.
When I add AddDataProtection() .NET stops working at other times, more and more settings.

After several attempts, I finally got it back in the development environment.
If it works in the stage environment (tests) I put the example code here.

However, I figured there was some way to work without having to change with Data Protection.

**Comment by eduardotolino** [comment]
I was using the `.ProtectKeysWithCertificate(X509Certificate2(` then gave a little work.
But it seems to me that only with the `.AddDataProtection()` command already works.

Tomorrow I will return with some news and more tests.

Thank you all.

**Comment by kevinchalet** [comment]
It's worth noting that in 1.x and 2.0, the certificate has to be in the machine X.509 store to be able to **decrypt** the Data Protection keys. This was very unfortunate but it's something the ASP.NET folks fixed in 2.1.

Take a look at https://github.com/aspnet/Home/issues/2321 and https://github.com/aspnet/DataProtection/pull/299 for more information.

**Comment by eduardotolino** [comment]
I believe I finally managed to make it work.
it was just a simple setup in IIS.

`LoadUserProfile=true (default is false)`

I'll test some more and return with success or failure.

thank you all for your attention.

**Comment by hwassermann** [comment]
Bravo @Tolitech, this helped me during big frustration moving from staging to production, where the key was suddenly renewed between app cycles.
