### ISSUE TITLE
Improve the built-in errors/log messages

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#52]

**Comment by MonkeyJamboree** [comment]
I see this as being important and help wanted, but I'm not entirely sure what to help with on this. What's the goal here? It seems as if all of the error responses already have descriptions.

**Comment by PinpointTownes** [comment]
The goal of this ticket is to improve all the existing OIDC errors and log messages to be more useful for the developer (i.e easier to understand, and with more pertinent data).

Thanks to its semantic logger, the vNext version could also be improved by attaching the data needed to debug a specific log message.

**Comment by PinpointTownes** [comment]
Most of the error messages have been reworked as part of https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/pull/239. We'll consider adding new info/debug messages in the next beta.
