### ISSUE TITLE
Can't set refresh token lifetime to infinite

### ISSUE THREAD

**Issue by 0xNF** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#524]
Sorry if there's other issues that deal with this - I looked through the tracker with a few different searches but couldn't find anything.

I encountered an issue when trying to set a non-expiring refresh token.
The problem comes down to this part in `OpenIdConnectServerHandler.SerializeRefreshTokenAsync`:

```csharp
// Create a new ticket containing the updated properties.
var ticket = new AuthenticationTicket(principal, properties, Scheme.Name);
ticket.Properties.IssuedUtc = Options.SystemClock.UtcNow;
ticket.Properties.ExpiresUtc = ticket.Properties.IssuedUtc;
ticket.Properties.ExpiresUtc += ticket.GetRefreshTokenLifetime() ?? Options.RefreshTokenLifetime;
```

Because the `IssuedUtc` is added to the `ExpiresUtc`,  an `Options.RefreshTokenLifetime` or `ticket.SetRefreshTokenLifeTime` set to `TimeSpan.MaxValue` throws an `ArgumentOutOfRangeException` . 

Before I get jumped on, this is how Spotify structures their refresh tokens. They do not expire, and are instead invalidated only by revocation.

Is there a preferred way to make an arbitrarily long-lived refresh token, or do I have to resort to hacks like setting it to expire in a thousand years or something?

edit: obviously this isn't only limited to refresh tokens. The identity token and access token serialization methods also set their `ExpiresUtc` field the same way.

**Comment by kevinchalet** [comment]
Tokens that never expire is frankly not a good idea. Using a long lifespan (e.g 1 year) is preferable, as it automatically rejects tokens that are potentially no longer used by apps.

To achieve what you want, you can use the `SerializeRefreshToken` event to nullify the expiration date:

```csharp
options.Provider.OnSerializeAuthorizationCode = context =>
{
    context.Ticket.Properties.ExpiresUtc = null;

    return Task.CompletedTask;
};
```

That said, I'll consider making the options nullable (with a warning indicating it's not recommended) to make that easier to configure.

**Comment by accessau-adam** [comment]
Just like to add to this that if you set null RefreshTokenLifetime to null - instead of then getting Ticket.Properties.ExpireUTC = null as a result, the value is carried over from the AuthenticateCode's lifetime (as the new ticket is constructed based on the AuthenticateCode's ticket when flowing through the /token endpoint of an authenticate_code grant_type).

If anyone wants a work around  before the code base i fixed, you can add this to the SerializeRefreshToken provider override

```
        public override Task SerializeRefreshToken(SerializeRefreshTokenContext context)
        {
            var lifetime = context.Ticket.GetRefreshTokenLifetime() ?? context.Options.RefreshTokenLifetime;
            if (lifetime.HasValue)
            {
                context.Ticket.Properties.ExpiresUtc = context.Ticket.Properties.IssuedUtc + lifetime.Value;
            }
            else
            {
                context.Ticket.Properties.ExpiresUtc = null;
            }
            return base.SerializeRefreshToken(context);
        }
