### ISSUE TITLE
Add token exchange support

### ISSUE THREAD

**Issue by kevinchalet** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#526]
In 2.0.0-rc3 and 1.1.0-preview, we adopted behavioral changes allowing to support the [token exchange RFC](https://tools.ietf.org/html/draft-ietf-oauth-token-exchange-14). This ticket tracks the addition of the complete RFC support, including new constants, new extensions, new `OpenIdConnectRequest`/`OpenIdConnectResponse` parameters and the additional logic.

**Comment by NinoFloris** [comment]
Great news! I currently have it implemented in C# and an F# app because we mainly use client oauth sdks that give us id tokens in exchange for an access token. Very happy with the approach
