### ISSUE TITLE
V2 RC3 Approval never prompted and user isn't logged in.

### ISSUE THREAD

**Issue by JohnGalt1717** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#527]
I've basically copied the sample for MVC.Server on Asp.net core 2.1. (which works)

But I'm having 2 issues that I think are related:

1. It's redirecting to /account/login instead of /signin like the sample but I can't figure out where it's doing it or why. Am I missing a setting or something that overrides it?

2. it loops through the login process with my external provider which appears to work fine but instead of prompting to accept or return to Postman it just goes right back to /account/login and according to HandleAuthorizationRequest: var principal = await context.HttpContext.AuthenticateAsync("ServerCookie"); the principle failed and it couldn't decode the token.

Looking at the call that goes through to signin-odic it has set-cookie for .AspNetCore.OpenIdConnect.Nonce and Identity.External= which then redirects.

I've been using this https://kevinchalet.com/2016/07/13/creating-your-own-openid-connect-server-with-asos-creating-your-own-authorization-provider/ which has different settings for postman but I think I filled it in right:

callback url: https://localhost:44302/signin-oidc
auth url: https://localhost:44302/connect/authorize
access token url: https://localhost:44302/connect/token
client Id: My client id
Client secret: none because this is a web app and I allow this explicitly in code.
Scope: openid offline_access
State: none

Client Authentication: Send as Basic Auth Header.

In postman it goes directly back to /account/login.  In chrome directly it goes to my redirecturi but doesn't hit anything and doesn't prompt to accept or anything so I don't have any way to get the token.

I'm planning on using this on an Angular site, so I need to be able to extract the token somehow through the process like postman should do and does with the samples.

**Comment by kevinchalet** [comment]
Assuming your app uses ASP.NET Core Identity (the MVC samples don't), you'll have to remove the cookie handlers (`AddCookie(...)`) from your `Startup` as Identity already registers some for you. You can find the list of schemes used by Identity here: https://github.com/aspnet/Identity/blob/dev/src/Identity/IdentityConstants.cs

To customize the default login path, use `services.ConfigureApplicationCookie(options => options.LoginPath = "/signin")`.

**Comment by JohnGalt1717** [comment]
Thanks! A note for anyone that comes to this, the services.ConfigureApplicationCookie call must be after the AddAuthentication call or it won't work.

The rest of the process is to not use the samples authorization code, but to instead use identity framework out of the box and you're good to go.
