### ISSUE TITLE
Is .NET 2.1 supported?

### ISSUE THREAD

**Issue by madnik7** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#529]
It couldn't migrate to NET 2.1. I am wondering is it supported at all?

I get "HTTP ERROR 404" + for when calling https://authserver/connect/token

**Comment by kevinchalet** [comment]
> It couldn't migrate to NET 2.1.

I hope you realize it's super vague.

> I am wondering is it supported at all?

It should work flawlessly. If it doesn't, it's a bug in ASP.NET Core 2.1 as it shouldn't come with breaking changes.

**Comment by madnik7** [comment]
Sorry, it was my fault. Your solution has been working successfully on NET Core 2.1
