### ISSUE TITLE
Question: CosmosDB Support

### ISSUE THREAD

**Issue by daveh101** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#531]
So, I've been looking at implementing this, server (I don't know a lot about the authentication side of things).  However, I also want it to work with CosmosDB.

Should this Identity Provider for Cosmos effectively work along with this? https://github.com/codekoenig/AspNetCore.Identity.DocumentDb

I get a little bit lost as one of the first things with the custom AuthenticationProvider is that is brings the Database context in through the constructor - would this work in the same way, or should it be something different.

Just looking for pointers to start with...

**Comment by kevinchalet** [comment]
> Should this Identity Provider for Cosmos effectively work along with this? https://github.com/codekoenig/AspNetCore.Identity.DocumentDb

ASOS is completely uncoupled from ASP.NET Core (that you can use as your membership stack or not), so whether it will work with it is actually irrelevant.

> I get a little bit lost as one of the first things with the custom AuthenticationProvider is that is brings the Database context in through the constructor - would this work in the same way, or should it be something different.

Yep, pretty much the same way. ASOS is a very low-level library that doesn't expose things like repositories/stores: `OpenIdConnectServerProvider` is the main hook and you can of course inject your CosmosDB client if you want to use it for DB operations.
