### ISSUE TITLE
Unauthorized when using same token in another service 

### ISSUE THREAD

**Issue by amitmallik** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#532]
I have an micro service scenario, where token is generated in one services and same token is used in other services.
If the controllers methods with [Authorize] keyword are in the same service that generates token with , it works fine. But when the token is sent to another service it throws Unauthorized error.
Not sure if I am missing anything.

This is the code in the other service where just validation is needed.
public void ConfigureServices(IServiceCollection services)
        {
            services.AddCors();
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);

            services
                .AddAuthentication(OAuthValidationDefaults.AuthenticationScheme)
                .AddOAuthValidation(OAuthValidationDefaults.AuthenticationScheme);
                
            services.AddScoped<MyOAuthProvider>();
            services.AddSingleton<IConfiguration>(Configuration);
        }

The provider code on the token generation side is below.
[MyOAuthProvider.zip](https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/files/2580188/MyOAuthProvider.zip)

**Comment by kevinchalet** [comment]
https://stackoverflow.com/questions/44844139/asos-token-validation-is-not-working-when-having-separate-authorization-server should put you on the right track.

**Comment by amitmallik** [comment]
It did. Thanks Kevin.
