### ISSUE TITLE
How to best check id_token_hint validity as AuthenticationMode.Active seems deprecated?

### ISSUE THREAD

**Issue by NinoFloris** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#535]
Some time has passed and we're looking at IdP logout now, what would be the best way to go currently to validate the id_token_hint? 

It seems using AuthenticationMode.Active is not supported with middlewares (anymore?), and I don't see a nice method to call into any ASOS token validation afterwards. Obviously I could just manually check it with JwtSecurityTokenHandler but at that point I felt the need to check with you.

**Comment by kevinchalet** [comment]
Simply use the standard ASP.NET Core authentication APIs:

```csharp
var result = await HttpContext.AuthenticateAsync("ASOS");
```

If `result.Principal` is null, then the identity token is not valid (it's worth noting the expiration date is not checked: an expired identity token will return a valid identity). Depending on your policy, you may want to validate whether the logged in user is the same as the one represented by the `id_token_hint` and potentially bypass logout consent in this case. That's what I used to do for quite some time before moving to a pattern that always requires explicit user consent for logout (we now do that in OrchardCore).

**Comment by NinoFloris** [comment]
Ah great, yes that's the policy, for this app we're currently just playing IdP for an SPA, that's the only client so silent logout makes sense there. Later with audiences we'll scope that down to allow silent login just for our spa
