### ISSUE TITLE
Does not support Owin/Katana 3/4

### ISSUE THREAD

**Issue by ofairfoul** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#537]
All the versions of OpenIdConnectServerOptions have references to Microsoft.AspNetCore so will not run on OWIN/Katana and .NET Framework 4.x.
Also can't find any any samples based on OWIN/Katana.

**Comment by kevinchalet** [comment]
> All the versions of OpenIdConnectServerOptions have references to Microsoft.AspNetCore so will not run on OWIN/Katana and .NET Framework 4.x.

It definitely works on OWIN/Katana. Just make sure you're using the right package: https://www.nuget.org/packages/Owin.Security.OpenIdConnect.Server/

> Also can't find any any samples based on OWIN/Katana.

https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/blob/dev/samples/Nancy/Nancy.Server/Startup.cs
