### ISSUE TITLE
Plans for the aspnet-contrib introspection, validation and server middleware for ASP.NET Core 3.0

### ISSUE THREAD

**Issue by kevinchalet** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#538]
As part of the incoming work for supporting ASP.NET Core 3.0, I'm seriously consider merging the aspnet-contrib introspection, validation and server middleware into OpenIddict, which would become ASP.NET 4.x/OWIN-compatible and would include a degraded/bare mode offering the same low-level and stateless experience as ASOS and the other aspnet-contrib middleware.

A complete description of my plan can be found here: https://github.com/openiddict/openiddict-core/issues/736.

Got any questions or remarks? Feel free to share them here or on Gitter!

**Comment by nikolaipaul** [comment]
Do you have a timeline in mind for .NET Core 3 support?

**Comment by kevinchalet** [comment]
For ASOS: never, as explained in my post.
For OpenIddict... soon 😄

**Comment by mscrivo** [comment]
For those of us upgrading to asp.net core 3 and are currently using ASOS 2.x ... can you comment on the compatibility of the existing package with asp.net core 3.0?  

Superficially, it compiles and our flows seem to work and I haven't seen any issues yet, but we haven't gone to production yet and I'm worried there will be a gotcha that I'm unaware of.

**Comment by kevinchalet** [comment]
ASOS 2.x should work flawlessly on ASP.NET Core 3.x. I haven't seen any report indicating there would be compat' issues.

On a related note, OpenIddict 3.x will be compatible with ASP.NET Core 2.1, 2.2 and 3.0. Once officially available, ASOS users will be encouraged to migrate to OpenIddict 3.0.

**Comment by mscrivo** [comment]
Perfect! Thanks for the clarification.
