### ISSUE TITLE
Support Source Link

### ISSUE THREAD

**Issue by hermanho** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#539]
Support Source Link on NuGet will improve the experiences on source debugging.

Ref:
https://github.com/dotnet/sourcelink

**Comment by kevinchalet** [comment]
@martincostello is it something you'd be interested in? If so, should we do that as part of 2.1?

**Comment by martincostello** [comment]
@PinpointTownes I've done this in libraries before, so it should be relatively simple to plug in (just a NuGet package and maybe a few MSBuild properties).

**Comment by martincostello** [comment]
@PinpointTownes See https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/pull/312.

**Comment by kevinchalet** [comment]
Closing (we got that for free when migrating OpenIddict to Arcade 😄)
