### ISSUE TITLE
Serve ui endpoints in separate web client

### ISSUE THREAD

**Issue by nativenolde** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#540]
Hey @PinpointTownes,

i'm working on a project that tries to serve the UI Endpoints in a separate web client application, to have the (OIDC) Server as plain as possible, without ui.

For example
UseOpenIdConnectServer > OpenIdConnectServerOptions
TokenEndpointPath: "/connect/token"
AuthorizationEndpointPath: "http://myportal.com/authorize"

in general it's very similar to this question, which unfortunately does not include implementation details:
https://stackoverflow.com/questions/39658761/openidconnect-server-third-party-providers-redirection

It would be great if you could leave a clue or a sample, if that's possible

Thanks a lot

nolde

**Comment by kevinchalet** [comment]
Hey,

I posted more details about a very similar scenario in the OpenIddict repo: https://github.com/openiddict/openiddict-core/issues/735#issuecomment-476749780

Bart wrote a sample for OpenIddict (into which ASOS will soon be merged) here: https://github.com/Bartmax/ImplicitCookiesAuthSample

Hope it'll help.

**Comment by nativenolde** [comment]
I'll definitely check this out. thank you.
