### ISSUE TITLE
get userinfo

### ISSUE THREAD

**Issue by angelru** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#543]
I have this code:

>            // Create a new ClaimsIdentity containing the claims that
>                 // will be used to create an id_token and/or an access token.
>                 var identity = new ClaimsIdentity(OpenIdConnectServerDefaults.AuthenticationScheme,
>                     OpenIdConnectConstants.Claims.PhoneNumber,
>                     OpenIdConnectConstants.Claims.Role);
> 
>                 identity.AddClaim(OpenIdConnectConstants.Claims.Subject, loginResponse.Id.ToString(),
>                     OpenIdConnectConstants.Destinations.AccessToken,
>                     OpenIdConnectConstants.Destinations.IdentityToken);
> 
>                 identity.AddClaim("idinstallation", loginResponse.IdInstallation.ToString(),
>                    OpenIdConnectConstants.Destinations.AccessToken,
>                    OpenIdConnectConstants.Destinations.IdentityToken);
> 
>                 identity.AddClaim("idrol", loginResponse.IdRol.ToString(),
>                     OpenIdConnectConstants.Destinations.AccessToken,
>                     OpenIdConnectConstants.Destinations.IdentityToken);
> 
>                 identity.AddClaim("topic", loginResponse.Topic,
>                    OpenIdConnectConstants.Destinations.AccessToken,
>                    OpenIdConnectConstants.Destinations.IdentityToken);
> 
>                 // Create a new authentication ticket holding the user identity.
>                 var ticket = new AuthenticationTicket(new ClaimsPrincipal(identity), new AuthenticationProperties(), OpenIdConnectServerDefaults.AuthenticationScheme);
> 
>                 // Set the list of scopes granted to the client application.
>                 ticket.SetScopes(new[] {
>                     /* openid: */ OpenIdConnectConstants.Scopes.OpenId,
>                     /* email: */ OpenIdConnectConstants.Scopes.Email,
>                     /* profile: */ OpenIdConnectConstants.Scopes.Profile,
>                     /* offline_access: */ OpenIdConnectConstants.Scopes.OfflineAccess
>                 }.Intersect(context.Request.GetScopes()));

but when call to /connect/userinfo with acces_token I received this:

```
{
    "sub": "1",
    "iss": "http://192.168.1.100:55799/"
}
```
without topic, idol, installation... only sub

How to I do it?

**Comment by angelru** [comment]
please, How to I do it?

**Comment by kevinchalet** [comment]
The built-in userinfo endpoint will never return custom claims specified in your tokens, only standard ones for which corresponding scopes have been granted. To return custom claims, override the `HandleUserinfoRequest` event and populate `context.Claims` with the custom claims you want to return.

**Comment by angelru** [comment]
Many thanks, it works!
