### ISSUE TITLE
open-id configuration modifications

### ISSUE THREAD

**Issue by gverstraete** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#553]
Hi,

We've been working with ASOS as an Authentication mechanism specifically for the "authorization_code" flow.

This solution is now up and running, but there is still something that seems to incorrectly configured to our open-id configuration endpoint.
The openid configuration returns for example still:

`    "grant_types_supported": [
        "authorization_code",
        "password",
        "implicit",
        "client_credentials",
        "refresh_token"
    ],`

Within our Aurhorization request, we do validate if the flow is wrong, and we Reject the request.

But, the only way I found to configure the open-id configuration so it's only returns "authorization code" in the supported grant types was by overriding `Task HandleConfigurationRequest(HandleConfigurationRequestContext context)`.

Is this really the only possible way? - Could we configure it also through startup, and so it maybe also directly get's rejected if a different authorization_code is used?

The same also applies to:
- response_types_supported
- response_modes_supported
- token_endpoint_auth_methods_supported
- revocation_endpoint_auth_methods_supported

Thanks for the feedback!

**Comment by kevinchalet** [comment]
Hey,

> Is this really the only possible way?

Yes. ASOS will try to "guess" the applicable grant/response types by determining whether the authorization and token endpoints are enabled or not, but if you want to return a more accurate list, using the `HandleConfigurationRequest` event is the right way to go.

> Could we configure it also through startup, and so it maybe also directly get's rejected if a different authorization_code is used?

The original idea was to make these things configurable per-request as much as possible (e.g to support multi-tenancy scenarios with a single ASOS instance).

OpenIddict 3.x - that will replace ASOS when it's officially released - uses a more traditional approach, that requires enabling the flows you want to support at startup. However, developers who need more flexibility will be able to override the validation logic to opt for the same approach ASOS uses.

**Comment by gverstraete** [comment]
Ok; makes sense! Thanks!
