### ISSUE TITLE
Support for ASP.Net core 3.1?

### ISSUE THREAD

**Issue by robertovaldesperez** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#554]

**Comment by kevinchalet** [comment]
https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/issues/538
https://kevinchalet.com/2020/06/11/introducing-openiddict-3-0-beta1/

**Comment by robertovaldesperez** [comment]
AllowInsecureHttp = true?

**Comment by kevinchalet** [comment]
Can you make complete sentences or are you expecting me to decipher what you're trying to say?

**Comment by robertovaldesperez** [comment]
@kevinchalet  I am sorry. Is it possible to set AllowInsecureHttp = true in openiddict-3-0-beta1?

**Comment by kevinchalet** [comment]
```csharp
services.AddOpenIddict()
    .AddServer(options =>
    {
        options.UseAspNetCore()
               .DisableTransportSecurityRequirement();
    });
```

**Comment by robertovaldesperez** [comment]
Thank you
