### ISSUE TITLE
Q: Is this still active, relevant in contemporary contexts?

### ISSUE THREAD

**Issue by mwpowellhtx** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#555]
As the subject states, is it still relevant in contemporary contexts? Besides the readme or other documentation, the last commits are 2-3 years ago from the repo indications. Thanks so much...

**Comment by kevinchalet** [comment]
This disclaimer in the README should answer your question 😃 

> :warning: **This project has been merged into OpenIddict. For more information, read [Introducing OpenIddict 3.0 beta1](https://kevinchalet.com/2020/06/11/introducing-openiddict-3-0-beta1/)**.

**Comment by mwpowellhtx** [comment]
Ah I think I'm tracking... Sounds like the low level stuff is probably mature enough and efforts, focus shifted to [openiddict](https://github.com/openiddict/openiddict-core). Thanks so much. Cheers.

**Comment by kevinchalet** [comment]
It's worth noting you can get the same low-level/database-less with OpenIddict's degraded mode (aka ASOS-like mode): https://kevinchalet.com/2020/02/18/creating-an-openid-connect-server-proxy-with-openiddict-3-0-s-degraded-mode/

**Comment by mwpowellhtx** [comment]
Nice, good point. To clarify, when we say "database-less", we're talking about the upstream tokens themselves? I think there is value in maintaining at least knowledge of the bearer tokens, or whatever makes sense to persist for user identification, alignment of claims with SPA verticals, that sort of thing, correct? I could be barking up the wrong tree there of course... I'm thinking of the single sign in type of workflow, with the possibility for external providers, while also allowing for app specific users.
