### ISSUE TITLE
Filtering claims in handler

### ISSUE THREAD

**Issue by manfredsteyer** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#69]
I've noticed that the handler filters out claims without a destination. What's the reason for that?

Wishes,
Manfred

**Comment by PinpointTownes** [comment]
With access tokens now being JWT tokens by default, the behavior described in my previous post has changed:
* __Refresh tokens__ and __authorization codes__: when they are not explicitly provided through the `CreateAuthorizationCode`/`CreateRefreshToken` notifications, authorization codes and refresh tokens are serialized using a data protector and claims are never filtered.

* __Identity tokens__ and __access tokens__: these tokens can be natively created using a security token handler, a data protector or using the `CreateIdentityToken`/`CreateAccessToken` notifications.
    * When they are created using `CreateIdentityToken`/`CreateAccessToken`, it's up to the implementer to correctly filter the identities before serialization if the returned tokens are not opaque. To make it easier, new `ClaimsIdentity.Clone` extensions have been added to the extensions package: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/blob/dev/src/Owin.Security.OpenIdConnect.Extensions/OpenIdConnectExtensions.cs#L305

    * When they are created using a security token handler, claims are automatically excluded if they don't explicitly contain the `id_token` or `token` destination.

    * When they are created using a data protector, these tokens are assumed to be opaque and claims are only excluded if they contain an explicit destination that doesn't include `id_token` or `token`.
