### ISSUE TITLE
Destination property check in id token

### ISSUE THREAD

**Issue by johnsonwangnz** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#71]
Great work.

There is a problem of Code flow in Owin.Security.OpenIdConnect.Server, as the properties of claims are not serialized, the destination properties are lost during serialization, when exchanging code for id token, claims that go into id token must have destination property. This is not case for access token, as default claims with no destination property are included in access token. Is this a bug or feature? thanks

**Comment by PinpointTownes** [comment]
The fixed ticket serializer has been integrated to `OpenIdConnectServerMiddleware` and is now used by default by `AuthorizationCodeFormat` and `RefreshTokenFormat` :sunglasses: 

As a side note, the token creation process has been completely reworked: access tokens are now serialized using a security token handler (`JwtSecurityTokenHandler` by default). If you prefer using opaque tokens (serialized by the data protector system), you can set `OpenIdConnectServerOptions.AccessTokenHandler` to `null` (in this case, `AccessTokenFormat` is called to serialize the access token using machine keys or DPAPI).

`AccessTokenProvider`, `RefreshTokenProvider` and `AuthorizationCodeProvider` have also been removed and replaced by new notifications exposed by `IOpenIdConnectServerProvider`.

Providing logic for storing and retrieving authorization codes is now optional: if you don't provide notifications for `IOpenIdConnectServerProvider.CreateAuthorizationCode` and `IOpenIdConnectServerProvider.ReceiveAuthorizationCode`, it will internally serialize the identity using `AuthorizationCodeFormat`, generate a unique 256 bits key, store the identity in a memory cache and return the key to the client.

To support web farm environment, you can provide your own `ObjectCache` implementation or implement `CreateAuthorizationCode` (note that the vNext version uses an `IDistributedCache` instance, whose default instance can be replaced with a cache based on Redis: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/blob/vNext/src/AspNet.Security.OpenIdConnect.Server/OpenIdConnectServerOptions.cs#L181)
