### ISSUE TITLE
Add support for user-info-endpoint

### ISSUE THREAD

**Issue by aspnet-contrib** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#8]

**Comment by Igorbek** [comment]
Hi @PinpointTownes, what's the status of this feature? Is it going to the next beta?

**Comment by PinpointTownes** [comment]
Hey. Nice coincidence, I just rebased and merged it :smile: 
Yep, it will be part of the next beta (for ASP.NET 5 RC1).

OWIN/Katana: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/1ff68b4ba89a3eb1c2bb89c2facc6865213aac60
ASP.NET 5: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/612f25c763f2e2c7eba70b28ba352a64a1a445c7

**Comment by PinpointTownes** [comment]
You can find more information on how it works on the PR: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/pull/97#issue-91612842

**Comment by Igorbek** [comment]
That's great! Thanks!
