### ISSUE TITLE
Sample not working?

### ISSUE THREAD

**Issue by jhermsen** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#82]
Whenever I start the sample server or client I get an error 500 page no details.
I use visual studio 2015 RC to build and run, debugger won't break on any thing in the starup class.

**Comment by PinpointTownes** [comment]
@jhermsen thanks for reporting this issue,

I assume you're using the ASP.NET 5 version?

Could you please run `dnvm list` and tell me which DNX version you're using?
`1.0.0-beta5-11781 clr x86` works fine on my machine. Make sure you're using the latest packages by running `dnu restore` for both `Mvc.Client` and `Mvc.Server`.

You should also enable first-chance exceptions.

**Comment by jhermsen** [comment]
Thank you for the quick response managed to look at it and running the same version.
tried also to do the restore command and that runs oke, but still the client and server return an error 500 and enabled all CLR Exception, but still no debugger.

**Comment by PinpointTownes** [comment]
I gonna try the MVC sample on a different machine.

And there's nothing written to the console logger?

**Comment by jhermsen** [comment]
No don't see anyt errors in the output.

**Comment by PinpointTownes** [comment]
I just tried `Mvc.Server` and `Mvc.Client` on a fresh new Windows 8.1 machine, and it works like a charm with WebListener (`dnx . web`).

![capture](https://cloud.githubusercontent.com/assets/6998306/7667414/ef948cba-fc06-11e4-96d5-3382e473504f.PNG)

![capture](https://cloud.githubusercontent.com/assets/6998306/7667422/1dde4408-fc07-11e4-8c4d-e07ac00814a6.PNG)

Have you tried running the MusicStore sample to see if your issue is caused by `AspNet.Security.OpenIdConnect.Server` or is the result of a more global bug?

That would be great if you could share more details about your configuration (OS, DNX used).

**Comment by jhermsen** [comment]
Just tried it also from command line and I get errors with dnx . web about some delegation issue.

Then tried a local admin account using dnx . web and it runs properly.
So I think it is some system policy issue I have here. 
Haven't had the issue creating clean web project with Visual Studio.

I'm running a recently clean installed Windows 8.1 joined to an AD domain and running latest Visual Studio 2015 RC.
Upgraded dnx to 1.0.0-beta5-11781.

**Comment by PinpointTownes** [comment]
Ah, nice! :smile: 

> Just tried it also from command line and I get errors with dnx . web about some delegation issue.

Any chance you could copy/paste the whole message?

**Comment by jhermsen** [comment]
This was the full output:

C:\Development\AspNet.Security.OpenIdConnect.Server-vNext\samples\Mvc\Mvc.Server
>dnx . web
System.Security.Cryptography.CryptographicException: The requested operation can
not be completed. The computer must be trusted for delegation and the current us
er account must be configured to allow delegation.

   at System.Security.Cryptography.CryptographicException.ThrowCryptographicExce
ption(Int32 hr)
   at System.Security.Cryptography.X509Certificates.X509Utils._LoadCertFromBlob(
Byte[] rawData, IntPtr password, UInt32 dwFlags, Boolean persistKeySet, SafeCert
ContextHandle& pCertCtx)
   at System.Security.Cryptography.X509Certificates.X509Certificate.LoadCertific
ateFromBlob(Byte[] rawData, Object password, X509KeyStorageFlags keyStorageFlags
)
   at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(Byte[
] rawData, String password)
   at Mvc.Server.Startup.GetCertificate() in C:\Development\AspNet.Security.Open
IdConnect.Server-vNext\samples\Mvc\Mvc.Server\Startup.cs:line 147
   at Mvc.Server.Startup.Configure(IApplicationBuilder app) in C:\Development\As
pNet.Security.OpenIdConnect.Server-vNext\samples\Mvc\Mvc.Server\Startup.cs:line
41

**Comment by PinpointTownes** [comment]
Ah yeah, it definitely sounds like a permissions issue.

You should maybe play with the `X509Certificate2`'s constructor taking an additional `X509KeyStorageFlags` parameter to see if a different value may solve your issue: https://msdn.microsoft.com/fr-fr/library/ms148422(v=vs.110).aspx

Alternatively, you can also store the certificate in the machine store.

**Comment by jhermsen** [comment]
Oke thanx gave it a try and that also works.

So using X509KeyStorageFlags.MachineKeySet makes it work also.

**Comment by PinpointTownes** [comment]
Thanks for the feedback! :smile: 

I'll update the samples to mention that `X509KeyStorageFlags.MachineKeySet` can be used to work around this kind of issue.

Feel free to ping me if you have any remark or question.
