### ISSUE TITLE
An OpenID Connect error has occurred invalid_client Invalid redirect_uri

### ISSUE THREAD

**Issue by AlexZeitler** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#91]
From a JavaScript client I tried to issue a token and used this URI:

`http://localhost:54540/connect/authorize?client_id=myClient&redirect_uri=http://localhost:3000/index.html&response_type=id_token&scope=openid&state=1435418504620015784112294204533&nonce=143541850462009592662733048201`

This results in an error page:

An OpenID Connect error has occurred invalid_client Invalid redirect_uri

Am I doing something wrong?

The JavaScript client is running on `http://localhost:3000/index.html` and the OpenId-Server is the one from the `/samples/Mvc/Mvc.Server` without modifications.

**Comment by PinpointTownes** [comment]
Have you tried URL-encoding the `redirect_uri` parameter?

You also need to make sure that `http://localhost:3000/index.html` is a valid `redirect_uri`.
The Mvc.Server sample overrides `ValidateClientRedirectUri` and does a database lookup to ensure that the `redirect_uri` corresponds to the client application, whose details are stored when the database is created in Startup.cs: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/blob/vNext/samples/Mvc/Mvc.Server/Startup.cs#L142

**Comment by AlexZeitler** [comment]
Adding the redirect URI in the client config fixed it, thanks :+1:
