### ISSUE TITLE
Automatically add refresh_token to grant_types_supported when the token endpoint is enabled

### ISSUE THREAD

**Issue by AlexZeitler** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#92]
Does the current implementation support refresh tokens?

`.well-known/openid-configuration` says 

````
grant_types_supported: [
"implicit",
"authorization_code"
]
````

But I've seen some other issues refering to refresh tokens so I'm not sure....

**Comment by PinpointTownes** [comment]
By default, the token endpoint doesn't serve refresh token requests if you don't override the `GrantRefreshToken` notification and call `notification.Validated()`. That's why it is not listed in the default `grant_types` supported.

That said, I'll probably change that in the near future, so that refresh tokens requests will be automatically served.

**Comment by AlexZeitler** [comment]
Thanks, I'll give it a try and let you know.

**Comment by PinpointTownes** [comment]
Note that you'll also have to use the `ConfigurationEndpoint` notification and add `refresh_token` to `notification.GrantTypes` if you want to tell the world you support the refresh token grant type :smile:

**Comment by PinpointTownes** [comment]
Meh, I must have Alzheimer's because I already made the refresh token grant purely automatic a while back... :smile: 

I'll update the documentation and fix the incorrect provider metadata response.

**Comment by PinpointTownes** [comment]
Fixed, in both the OWIN/Katana 3 version (https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/7a1155b65216ed80e04f06bb8a0109d2dc75187d) and the ASP.NET 5 version (https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/adbc3d343f257fe8e855e9ec22bc7269daf5d959) :sake:
