### ISSUE TITLE
userinfo endpoint

### ISSUE THREAD

**Issue by AlexZeitler** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#93]
Are there any plans to provide a userinfo endpoint?

**Comment by PinpointTownes** [comment]
Yup, I'll make sure it is supported when the PR adding it to the OIDC client middleware developed by MSFT is merged :+1: 

In the meantime, you can use the `id_token`` to flow data related to the user.

FYI, there's a already a ticket tracking that: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/issues/8

**Comment by AlexZeitler** [comment]
Thanks and sorry for the duplicate :smile:
