### ISSUE TITLE
Stop rejecting logout requests missing an explicit post_logout_redirect_uri

### ISSUE THREAD

**Issue by csunali** [aspnet-contrib/AspNet.Security.OpenIdConnect.Server#99]
I cannot get the OpenIdConnectServerProvider.LogoutEndpoint method called using the following configuration even though the AuthorizationController.Logout method gets called successfully.

What I was hoping was to completely remove the AuthorizationController, set the LogoutEndpointPath to "/Auth/Logout" and implement the logout functionality in my custom Authorization Provider. Any help is appreciated.

`ConfigureServices` method has the following code in it:

```
            services.AddIdentity<ApplicationUser, IdentityRole>()
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultTokenProviders();

            services.ConfigureIdentity(options =>
            {
                options.Password.RequiredLength = 8;
                options.Password.RequireNonLetterOrDigit = false;
                options.User.RequireUniqueEmail = true;
            });

            services.ConfigureIdentityApplicationCookie(options =>
            {
                options.LoginPath = new PathString("/SignIn");
                options.LogoutPath = new PathString("/SignOut");
                options.ExpireTimeSpan = TimeSpan.FromDays(1);
            });
```

`Configure` method has the following code in it:

```
            // Configure the API request pipeline.
            app.MapWhen(context => context.Request.Path.StartsWithSegments(new PathString("/api")), branch =>
            {
                app.UseOAuthBearerAuthentication(options =>
                {
                    options.AutomaticAuthentication = true;
                    options.Authority = configuration.Get("OAuth:Authority");
                    options.Audience = configuration.Get("OAuth:Audience");

                    // if the audience is null or empty, then don't validate it
                    options.TokenValidationParameters.ValidateAudience = configuration.Get("OAuth:Audience") != null;
                });

                app.UseMvc();
            });

            app.UseIdentity();

            var certificate = LoadCertificate();
            var key = new X509SecurityKey(certificate);

            var credentials = new SigningCredentials(key,
                SecurityAlgorithms.RsaSha256Signature,
                SecurityAlgorithms.Sha256Digest);

            app.UseOpenIdConnectServer(options =>
            {
                options.AuthenticationScheme = OpenIdConnectDefaults.AuthenticationScheme;

                options.Issuer = configuration.Get("OpenId:Issuer") != null ? 
                                    new Uri(configuration.Get("OpenId:Issuer")) : null;

                options.SigningCredentials = credentials;

                options.Provider = new OpenIdAuthorizationProvider();

                options.ApplicationCanDisplayErrors = true;
                options.AllowInsecureHttp = true;

                options.TokenEndpointPath = new PathString("/Auth/Token");
                options.LogoutEndpointPath = new PathString("/Auth/Logout");
            });
```

`AuthorizationController` class has the following in it:

```
    [Route("~/Auth")]
    public class AuthorizationController : Controller
    {
        public AuthorizationController()
        {
        }

        [HttpPost("Logout"), ValidateAntiForgeryToken]
        public async Task<ActionResult> Logout(CancellationToken cancellationToken)
        {
            await Context.Authentication.SignOutAsync(IdentityOptions.ApplicationCookieAuthenticationScheme);

            await Context.Authentication.SignOutAsync(OpenIdConnectDefaults.AuthenticationScheme);

            return new HttpStatusCodeResult(200);
        }
    }
```

**Comment by PinpointTownes** [comment]
Could you also paste your custom `OpenIdAuthorizationProvider`?

**Comment by csunali** [comment]
Sure, even though there is nothing special in it, please find the class below. I test if the request hits the LogoutEndpoint method using the debugger so there is no code in it besides calling the base method.

Please notice that the logout method had two calls to the Signout method for two separate schemes, so does the GrantResourceOwnerCredentials method signs in the user using two schemes as well. The reason to do so is that the `/api` branch uses bearer authentication while the frontend (regular mvc controllers) actually use cookie authentication coming from AddIdentity call.

```
    public sealed class OpenIdAuthorizationProvider : OpenIdConnectServerProvider
    {
        public override Task ValidateClientAuthentication(ValidateClientAuthenticationNotification notification)
        {
            // "Resource owner credentials" does not provide a client ID.
            if (notification.ClientId == null)
            {
                notification.Validated();
            }

            return Task.FromResult(0);
        }

        public override async Task GrantResourceOwnerCredentials(GrantResourceOwnerCredentialsNotification notification)
        {
            if (string.IsNullOrEmpty(notification.UserName) ||
                string.IsNullOrEmpty(notification.Password))
            {
                notification.SetError("invalid_grant", "The user name or password is incorrect.");
                return;
            }

            IUserService userService = 
                notification.HttpContext.RequestServices.GetService<IUserService>();

            bool isValidPassword = await userService.CheckPasswordAsync(notification.UserName, notification.Password);

            if (!isValidPassword)
            {
                notification.SetError("invalid_grant", "The user name or password is incorrect.");
                return;
            }

            ApplicationUser user = await userService.GetUserAsync(notification.UserName);

            ClaimsPrincipal tokenPrincipal = 
                await userService.GetPrincipalAsync(
                    user.Username, 
                    OpenIdConnectDefaults.AuthenticationScheme);

            notification.Validated(tokenPrincipal);

            ClaimsPrincipal cookiePrincipal =
                await userService.GetPrincipalAsync(
                    user.Username,
                    IdentityOptions.ApplicationCookieAuthenticationScheme);

            await notification.HttpContext.Authentication.SignInAsync(
                IdentityOptions.ApplicationCookieAuthenticationScheme, cookiePrincipal);
        }

        public override Task LogoutEndpoint(LogoutEndpointNotification notification)
        {
            return base.LogoutEndpoint(notification);
        }
    }
```

**Comment by PinpointTownes** [comment]
Thanks, I'll try to reproduce this issue as soon as possible :smile: 

Out of curiosity, what type of client are you using? Does it send the optional `post_logout_redirect_uri` parameter? While it is explicitly stated as optional by the OpenID Connect specs, I opted for an aggressive check in the first bits: if you don't provide this parameter or if you don't validate it in `ValidateClientLogoutRedirectUri`, the logout request will be rejected.

Of course, I'll eventually relax this policy, but I'm not sure yet what to do when this parameter is missing.

**Comment by csunali** [comment]
Thank you!

I am implementing a backend application using MVC and it is completely AJAX featured. Thus, a user might sign-in and stay signed-in for days without reloading the page but only making AJAX requests to certain API controllers. 

So I thought that I might divide the authentication into two parts: bearer and cookie. Bearer for API calls and cookie for any other MVC controller.

When a user signs-in using the "sign in form", I make a call to `/Auth/Token` endpoint using JavaScript and store the `access_token` returned in `localStorage` using `localStorage.setItem('access_token', data.access_token)`.

Then for any request made to any regular MVC controller/action, the cookie authentication (added by `UseIdentity`) does its job while any request to `/api` should actually send the `Authorization` header with the request in order for the bearer authentication to do its job.

Finally, when a user wants to logout, he clicks the logout button and is sent to /SignOut page which has the following code in it:

```
    <form id="form-signout"
          action="/Auth/Logout"
          method="post"
          enctype="application/x-www-form-urlencoded">
        @Html.AntiForgeryToken()
    </form>

    <script type="text/javascript">
        $(function () {

            $('#form-signout').ajaxSubmit({
                success: function () {

                    localStorage.removeItem(tokenKey);

                    $('#progressing').hide();
                    $('#completed').show();
                }
            });

        });
    </script>
```

Long story short, I do not have other clients using my API but just the currently logged in user. I guess I could have simply used the cookie authentication and skip implementing the bearer authentication, however, I just wanted the API methods to use the bearer authentication from the very beginning so that in case there are other applications which needs to use the API I develop in the future, it is already implemented by touching a few things here and there.

Back to your question, no, my client (being JavaScript) does not send the `post_logout_redirect_uri` parameter.

Please do not hesitate to comment on my approach if it seems wrong or unnecessary to you. Any idea or feedback is more than welcome and is appreciated.

**Comment by PinpointTownes** [comment]
Fixed (OWIN/Katana: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/893572f5e48f5d17160685e46b626c30d51c6c55; ASP.NET 5: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/7ed51cca053125db1ecf5bfec20bfefe1e6fed73)

The fixed bits have been pushed to MyGet: https://www.myget.org/F/aspnet-contrib

@csunali your approach seems totally appropriate for such an hybrid client application :+1: 

Of course, you'll have to make sure that your endpoints accepting cookies are ALL protected with an anti-forgery system (using `ValidateAntiForgeryTokenAttribute` with MVC). Returning JSON from these endpoints is also totally discouraged (http://haacked.com/archive/2008/11/20/anatomy-of-a-subtle-json-vulnerability.aspx)

**Comment by csunali** [comment]
Thank you for the quick fix! I will try the update asap and get back to you.

I've seen the article you mentioned before and it makes sense. Considering that JSON via GET method is not encouraged, what would you do yourself? Just go for POST for all API methods?

**Comment by PinpointTownes** [comment]
No, I'd simply avoid cookie authentication for API endpoints :smile:

**Comment by csunali** [comment]
Oops, am I actually not doing so? I mean, I would expect the following `MapWhen` to handle all the requests coming into `/api` endpoints. Please correct me if I am wrong.

```        
            // Configure the API request pipeline.
            app.MapWhen(context => context.Request.Path.StartsWithSegments(new PathString("/api")), branch =>
            {
                app.UseOAuthBearerAuthentication(options =>
                {
                    options.AutomaticAuthentication = true;
                    options.Authority = configuration.Get("OAuth:Authority");
                    options.Audience = configuration.Get("OAuth:Audience");

                    // if the audience is null or empty, then don't validate it
                    options.TokenValidationParameters.ValidateAudience = configuration.Get("OAuth:Audience") != null;
                });

                app.UseMvc();
            });
```

I am calling the `app.UseIdentity();` method to configure cookie authentication only right after that `MapWhen` call, which I assume gets attached only to endpoints that does not match `/api`. If that is correct, the `app.UseIdentity();` method does the following internally:

```
            app.UseCookieAuthentication(null, IdentityOptions.ExternalCookieAuthenticationScheme);
            app.UseCookieAuthentication(null, IdentityOptions.TwoFactorRememberMeCookieAuthenticationScheme);
            app.UseCookieAuthentication(null, IdentityOptions.TwoFactorUserIdCookieAuthenticationScheme);
            app.UseCookieAuthentication(null, IdentityOptions.ApplicationCookieAuthenticationScheme);
```

Here is what I will do once I have some time, I will change my sign-in method to authenticate only for cookie authentication and comment out the "validated" call for OpenId, which should sign-in the user only using cookie authentication. Then I will try to call my API methods to see what actually happens.

I will of course be keeping you posted.

**Comment by PinpointTownes** [comment]
No no, don't worry, your configuration looks fine, except one thing: you shouldn't use the `app` variable - that represents the main builder - inside the branch delegate:

```csharp
// Configure the API request pipeline.
app.MapWhen(context => context.Request.Path.StartsWithSegments(new PathString("/api")), branch => {
    (app -> branch).UseOAuthBearerAuthentication(options => {
...
    }
});
```

My remark was just a general consideration: it's extremely easy to create a new API action outside the `/api` route prefix and forget that cookie authentication will automatically apply :smile:

**Comment by csunali** [comment]
Right! I have already fixed that app>branch mistake locally but of course forgot to update it in the sample I provided, silly me :)

I really appreciate the time you spent fixing the issue and commenting on all the things I've asked.

Great job! :+1: 

P.S.: Please let me know in case I can somehow contribute to anything around here. Samples or anything else.

**Comment by PinpointTownes** [comment]
> I really appreciate the time you spent fixing the issue and commenting on all the things I've asked.

You're welcome. Don't hesitate if you still have questions :smile: 

> Great job! :+1:

> P.S.: Please let me know in case I can somehow contribute to anything around here. Samples or anything else.

Thank you very much! (and please continue reporting bugs when you see them :smile:)

FYI, @shaunluttin is currently working on a ROPC sample (that will be eventually used in a tutorial posted to docs.asp.net): feel free to share your thoughts on his PR: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/pull/98.

Thanks!

**Comment by csunali** [comment]
Just had time to try it and the LogoutEndpoint method now gets called without any problems. Thank you!

Do you suggest implementing the logout functionality within this method directly? I don't think I need a separate controller anymore, am I right?

**Comment by csunali** [comment]
By the way, I confirm that if the user is only authenticated by cookie authentication and not by bearer authentication, the user cannot reach the API endpoints by cookie authentication. Just tried that.

Your consideration is still correct. If an API endpoint does not have the `/api` route prefix, it will be authenticated by using the cookie authentication. Thank you for that remark!

One thing I saw was that if I do not call `notification.RequestCompleted();` within `LogoutEndpoint` method, the method gets called twice. If I call RequestCompleted, it works perfectly. Is that an expected thing?

**Comment by PinpointTownes** [comment]
> Do you suggest implementing the logout functionality within this method directly?

Yep, definitely. With the new `aspnet/Antiorgery` block, you can even add XSRF countermeasures directly in the authorization provider if you want to protect your logout endpoint against an unwanted sign out (aka the `superlogout.com` syndrome :smile:)

You can see this sample for more information on how to use the new `Antiforgery` class: https://github.com/aspnet/Antiforgery/blob/dev/samples/AntiforgerySample/FormPostSampleMiddleware.cs

> One thing I saw was that if I do not call notification.RequestCompleted(); within LogoutEndpoint method, the method gets called twice. If I call RequestCompleted, it works perfectly. Is that an expected thing?

Not calling `notification.RequestCompleted()` is not recommended if you don't want the request to be processed by the next middleware in the pipeline, which may have unattended effects if you already handle the logout process in `LogoutEndpoint`.

Did you keep your logout controller?

**Comment by csunali** [comment]
Thank you for the super helpful comments!

I will be reading through the new Antiforgery block. I did not know they had already taken that part out of the core MVC blocks. Great job.

If I do not call `RequestCompleted` and remove the logout controller, the logout endpoint returns 404 even though the `LogoutEndpoint` method gets called, which is normal based on your comments.

So, what I did is that, I removed the logout controller, logged out the user within the `LogoutEndpoint` method and also called the `RequestCompleted` method.

The whole code is below:

```
        public override async Task LogoutEndpoint(LogoutEndpointNotification notification)
        {
            await notification.HttpContext.Authentication
                .SignOutAsync(IdentityOptions.ApplicationCookieAuthenticationScheme);

            await notification.HttpContext.Authentication
                .SignOutAsync(OpenIdConnectDefaults.AuthenticationScheme);

            notification.RequestCompleted();
        }
```

That seems to work perfectly.

**Comment by PinpointTownes** [comment]
> If I do not call RequestCompleted and remove the logout controller, the logout endpoint returns 404 even though the LogoutEndpoint method gets called, which is normal based on your comments.

Exactly.

FYI, we will migrate to the new notification model for both the OWIN/Katana and the ASP.NET 5 versions (probably in the next few days). Don't be surprised if you see a breaking change in the next version: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/issues/96 :open_mouth:

**Comment by PinpointTownes** [comment]
Note that you can also use the optional `id_token_hint` to 'protect' your logout endpoint against an unwanted sign out, which might better suited for JS clients: https://openid.net/specs/openid-connect-session-1_0.html#RPLogout

It's natively supported by `AspNet.Security.OpenIdConnect.Server`: you can retrieve the principal corresponding to the claims contained in the `id_token_hint` using the standard ASP.NET 5 authentication APIs: 

```csharp
// Extract the principal corresponding to the `id_token_hint` sent by the JS client app.
var principal = await notification.HttpContext.Authentication.AuthenticateAsync("Bearer");

// You can compare the previous principal with the user resolved using cookie authentication:
// if the id_token_hint doesn't correspond to the connected user, you can refuse to serve the logout request.
```

**Comment by csunali** [comment]
Regarding #96 ; I have simply changed the `notification.RequestCompleted()` into `notification.HandleResponse()`. That seems to fix the breaking change issue. Thank you for warning.

Regarding the `id_token_hint` subject, I am having difficulties understanding how to implement a sample archiving it. I will try to describe what is missing from my imagination :)

- How to initially access the `id_token_hint`? Is it returned from the initial `/Token` endpoint request? The following is an example of what I get from the `/Token` endpoint. Is it the "id_token" field that I have to send back?

```
{
    "token_type":"bearer",
    "access_token":"...",
    "expires_in":"3600",
    "id_token":"...",
    "refresh_token":"..."
}
```

- How to send the `id_token_hint` value back? Is it just as part of my sign-out form which is basically the following or some specific request header field?

```
<form id="form-signout"
        action="/Auth/Logout"
        method="post"
        enctype="application/x-www-form-urlencoded">
    @Html.AntiForgeryToken()
</form>

<script type="text/javascript">
    $(function () {

        $('#form-signout').ajaxSubmit({
            success: function () {

                localStorage.removeItem(tokenKey);

                $('#progressing').hide();
                $('#completed').show();
            }
        });

    });
</script>
```

- A basic implementation in the LogoutEndpoint.

**Comment by PinpointTownes** [comment]
> Is it the "id_token" field that I have to send back?

Yes, it is! :smile: 
Note that you can send it back to the authorization server even if it is expired.

> How to send the id_token_hint value back? Is it just as part of my sign-out form which is basically the following or some specific request header field?

Directly in the request form, using the `application/x-www-form-urlencoded` format.

**Comment by csunali** [comment]
Okay, I know what field to send back now. By the way, I already send the `token_id` value back using the request's `Authorization` header. Do I really need to send it again as part of the sign-out form? I guess I should already be able to extract it from the header field.

Then what should I do? I am missing the logic regarding what to do with the current principle after getting it (using the line of method you provided).

**Comment by PinpointTownes** [comment]
> By the way, I already send the token_id value back using the request's Authorization header. Do I really need to send it again as part of the sign-out form? I guess I should already be able to extract it from the header field.

Out of curiosity, why are you doing that? Of course, you can, but that's not really specs-compliant :mask: 

> Then what should I do? I am missing the logic regarding what to do with the current principle after getting it (using the line of method you provided).

Next, you can retrieve the principal extracted from the cookie and compare one of their unique claims like `ClaimTypes.NameIdentifier`: if both are identical, then the logged-in user really corresponds to the one who made the request, and you can safely sign out.

```csharp
public override async Task LogoutEndpoint(LogoutEndpointNotification notification) {
    var tokenPrincipal = await Context.Authentication.AuthenticateAsync(OpenIdConnectDefaults.AuthenticationScheme);
    var cookiePrincipal = await Context.Authentication.AuthenticateAsync(IdentityOptions.ApplicationCookieAuthenticationScheme);

    if (tokenPrincipal != null && cookiePrincipal != null) {
        var identifier1 = tokenPrincipal.Principal.FindFirst(ClaimTypes.NameIdentifier);
        var identifier2 = cookiePrincipal.Principal.FindFirst(ClaimTypes.NameIdentifier);
    
        if (string.Equals(identifier1, identifier2, StringComparison.Ordinal)) {
            await notification.HttpContext.Authentication.SignOutAsync(IdentityOptions.ApplicationCookieAuthenticationScheme);
            await notification.HttpContext.Authentication.SignOutAsync(OpenIdConnectDefaults.AuthenticationScheme);
        }
    }

    notification.HandleResponse();
}
```

**Comment by csunali** [comment]
I am sending the `token_id` value using the `Authorization` header because I think that is how Bearer authentication extracts the authorized user, am I wrong?

To be exact, this is what I do, basically sending the Authorization header for all of the Ajax requests I have:

```
    $(document).ajaxSend(function (event, jqXHR, settings) {
        jqXHR.setRequestHeader('Authorization', 'Bearer ' + localStorage.getItem("token"));
    });
```

**Comment by PinpointTownes** [comment]
Ahhhh, but it's the access token, not the identity token :smile:

**Comment by csunali** [comment]
And you are right :) My bad!

Thank you once again for all the samples and explanations!

**Comment by csunali** [comment]
The sample you shared fails to compile at `tokenPrincipal.Principal` and the exact error is:

*Error	CS1061	'ClaimsPrincipal' does not contain a definition for 'Principal' and no extension method 'Principal' accepting a first argument of type 'ClaimsPrincipal' could be found (are you missing a using directive or an assembly reference?)	[Namespace].DNX 4.5.1*

The exact type of the tokenPrinciple is `System.Security.Claims.ClaimsPrincipal`.

By the way, it seems that the ClaimsPrinciple class has an extension method `GetUserId()` so that I can reach the user id using `tokenPrincipal.GetUserId()`. Would that help if I change the code to the following?

```
if (tokenPrincipal != null && cookiePrincipal != null)
{
    var userId1 = tokenPrincipal.GetUserId();
    var userId2 = cookiePrincipal.GetUserId();

    if (string.Equals(userId1, userId2, StringComparison.Ordinal))
    {
        await notification.HttpContext.Authentication.SignOutAsync(IdentityOptions.ApplicationCookieAuthenticationScheme);
        await notification.HttpContext.Authentication.SignOutAsync(OpenIdConnectDefaults.AuthenticationScheme);
    }
}
```

**Comment by csunali** [comment]
I am also able to make the following:

```
if (tokenPrincipal != null && cookiePrincipal != null)
{
    var identifier1 = tokenPrincipal.FindFirst(ClaimTypes.NameIdentifier).Value;
    var identifier2 = cookiePrincipal.FindFirst(ClaimTypes.NameIdentifier).Value;

    if (string.Equals(identifier1, identifier2, StringComparison.Ordinal))
    {
        await notification.HttpContext.Authentication.SignOutAsync(IdentityOptions.ApplicationCookieAuthenticationScheme);
        await notification.HttpContext.Authentication.SignOutAsync(OpenIdConnectDefaults.AuthenticationScheme);
    }
}
```

**Comment by csunali** [comment]
Sorry for posting multiple times instead of a single post but below is the GetUserId's comments:

```
        //
        // Summary:
        //     Returns the User ID claim value if present otherwise returns null.
        //
        // Parameters:
        //   principal:
        //     The System.Security.Claims.ClaimsPrincipal instance this method extends.
        //
        // Returns:
        //     The User ID claim value, or null if the claim is not present.
        //
        // Remarks:
        //     The User ID claim is identified by System.Security.Claims.ClaimTypes.NameIdentifier.
        public static string GetUserId(this ClaimsPrincipal principal);
```

They also state that the User ID is extracted using `ClaimTypes.NameIdentifier`.

The extension comes from the `System.Security.Claims` namespace and the assembly is `Microsoft.AspNet.Identity\3.0.0-beta6-12688\lib\dnx451\Microsoft.AspNet.Identity.dll`.

**Comment by PinpointTownes** [comment]
> The sample you shared fails to compile at tokenPrincipal.Principal and the exact error is:

> Error CS1061 'ClaimsPrincipal' does not contain a definition for 'Principal' and no extension method 'Principal' accepting a first argument of type 'ClaimsPrincipal' could be found (are you missing a using directive or an assembly reference?) [Namespace].DNX 4.5.1

> The exact type of the tokenPrinciple is System.Security.Claims.ClaimsPrincipal.

Ah yeah, that's what you get when copying/pasting old samples :smile: 
`AuthenticateAsync`'s signature changed last week, it now returns `ClaimsPrincipal` instead of `AuthenticationResult`.

> By the way, it seems that the ClaimsPrinciple class has an extension method GetUserId() so that I can reach the user id using tokenPrincipal.GetUserId(). Would that help if I change the code to the following?

Yep, you can use it too, it does exactly the same thing: https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNet.Identity/PrincipalExtensions.cs#L35-L42

**Comment by csunali** [comment]
Thank you :)
